### ISSUE TITLE
Why Pointer int values are not generated in golang

### ISSUE THREAD

**Issue by omjangir** [golang/protobuf#1024]
https://github.com/golang/protobuf/issues/15#issuecomment-77960477

What is the reason behind not differentiating int value 0 or NULL?

Thanks

**Comment by neild** [comment]
I presume you're referring to the design decision to not support presence in proto3. That is, while in proto2 an int32 field might have the value `0` or not be set at all (represented as an `(*int32)(nil)` in Go), in proto3 there is no "not set" status separate from `0`.

I unfortunately do not know the answer to that question, but it's a feature of the protocol buffer language and not specific to Go. We implement the protocol buffer language as specified.

**Comment by omjangir** [comment]
Thanks for the quick reply!
I will post this question on the protocol buffer language issues list.

**Comment by puellanivis** [comment]
I believe the reasons were due to the complications of supporting not just presence vs. zero value, but all the complexity of non-zero default values as well.

This was most apparent in Go, where we needed things like `Field: proto.Int32(42)` rather than the more natural `Field: 42` to get presence testing. And then to get default value support, one was technically always supposed to use the `GetField() int32` methods, which would handle properly inject the default value. But when one already knows the default value feature is not being used, and non-presence means its invalid, why not just access the raw exported value directly?

I know other languages had similar issues, but syntactic sugar or existing common language convention (Java kind of already expects Getter/Setter methods) was able to hide a lot of it from users, but internally there was still a lot of complexity necessary to support the features. The proper handling of default values was problematic across all languages, and every language required access through some getter function in some way in order to support it.

When reviewing proto3, non-zero default values were already uncommon, and cutting the feature entirely was a big efficiency gain across all languages. Once they cut non-zero default values, and mandated zero-value defaults for all fields, presence testing become completely unnecessary. And removing the feature allowed again for big efficiency gains across all languages.
