### ISSUE TITLE
jsonpb: allow byte array encoding as hex

### ISSUE THREAD

**Issue by RobertMic** [golang/protobuf#1030]
**Is your feature request related to a problem? Please describe.**
Internally we use Protobufs as our serialization structure. We would also like to archive this data in a form that is human readable for debugging/data analysis purposes. We wanted to simply marshal our protos into JSON, for the most part this is perfect, however for all of the binary fields in our protos it would be much more usable to us if we could see it as hex instead of base64.

**Describe the solution you'd like**
Expose an option on the `jsonpb.Marshaller` struct that allows the user to choose how binary data is encoded.

**Describe alternatives you've considered**
1. Write our own marshaller/unmarshaller into a human readable format. This would be a significant amount of work considering the jsonpb marshaller is almost perfect.
2. Fork this repo and add the feature ourselves. This would mean we would have to manage a fork for a fairly small change.
3. Hackily unmarshal the returned jsonpb value into a generic map and scrape every field, converting all fields that _look_ like base64 into hex. This can be error prone, there are workarounds to get more accurate but involve significant boilerplate and are still very hacky.

**Additional context**
The data we archive is first dumped to S3 and then moved to a cloud data platform. We could do the data transformation during this export process, however not all data we archive to S3 is exported. It can be bothersome to modify the data that is only in S3 when viewing it for debugging.

**Comment by dsnet** [comment]
Hi, thanks for the feature request! Handling binary data as hexadecimal rather than base64 is a reasonable expectation, but it's not what the [protobuf<->JSON specification says to do as it currently says to use base64](https://developers.google.com/protocol-buffers/docs/proto3#json).

In the `golang/protobuf` project, we strictly adhere to implementing protobufs as specified by the main protobuf project and avoid any features that are specific to Go.

I recommend filing this request in https://github.com/protocolbuffers/protobuf for the general JSON specification to support this. Without official blessing of such a feature, we can't add it.

**Comment by RobertMic** [comment]
Alright, thanks for the reply :).
