### ISSUE TITLE
Is it possible for a protobuf plugin to add a field to a message?

### ISSUE THREAD

**Issue by Raytar** [golang/protobuf#1059]
I'm working on a protobuf plugin called [Gorums](https://github.com/Raytar/gorums), and I am looking for a way to add an `ID` field to any message type. Currently, the option that Gorums exposes requires the user to manually add a field to the messages in order to use the feature. Here's an example:

```proto
service GorumsTest {
	rpc ReadOrdered(stream ReadRequest) returns (stream ReadResponse) {
		option (gorums.qc_strict_ordering) = "MsgID";
	}
}

message State {
	string Data = 1;
	uint64 Timestamp = 2;
}

message ReadRequest {
	string Key = 1;
	uint64 MsgID = 2;
}"

message ReadResponse {
	bool OK = 1;
	State State = 2;
	uint64 MsgID = 3;
}
```
Gorums will use the `MsgID` field to keep track of which requests and responses belong together.

What I want is to have the `MsgID` field injected into the messages by Gorums so that the user does not have to specify it in their messages. I have looked into `protoreflect`, but can't find any info on whether it can be used to accomplish this. I tried calling `msg.ProtoReflect().NewField()`, but that only caused a panic.

**Comment by neild** [comment]
There is no way for a plugin to inject a field into a message.

Protobufs are a language-neutral data interchange format. The shape of a protobuf message (that is, the fields that it is composed of) is defined in a `.proto` file so that it can be shared between every client of that file. Modifying the definition of a message outside the `.proto` file would run counter to the goal of protobufs being a neutral interchange format.

You might want to look into protobuf extension fields (proto2 only), which essentially allow one `.proto` file to add fields to a message defined in a different `.proto` file. However, for your use case, it might be simpler to wrap the user-provided messages in a message type of your own:

```proto
message Request {
  uint64 ID = 1;
  google.protobuf.Any message = 2; // user-provided message
}
```

**Comment by Raytar** [comment]
I see. Thanks for the suggestion, I will definitely look into that!
