### ISSUE TITLE
can proto file import remote proto file on git?

### ISSUE THREAD

**Issue by RaymondReddington** [golang/protobuf#1072]
can proto file import remote proto file on git? just like go mod, search on github or other git repo server.

**Comment by neild** [comment]
Presuming you mean a `.proto` file parsed by `protoc`: No, there is no support in `protoc` for fetching imported files from any remote location.

**Comment by RaymondReddington** [comment]
can you support this feature?
i'm a golang user. 'import' can work just like go mod.
or this may only be supported by protoc-gen-go for golang usage..

**Comment by neild** [comment]
Parsing of `.proto` files is handled entirely by the `protoc` compiler. There's no way for `protoc-gen-go` to change how imports work in the source `.proto` files, because it never sees them.

If you'd like to propose a change to `protoc`, the place to do so is in the general protobuf project at https://github.com/protocolbuffers/protobuf. I doubt that support will be added to `protoc` for fetching code from remote locations, but that's the place for a definitive answer.

**Comment by RaymondReddington** [comment]
oh i see. thank you.
