### ISSUE TITLE
proto: memory leak while Unmarshal 

### ISSUE THREAD

**Issue by vasundhara785** [golang/protobuf#1078]
Hi,

![image](https://user-images.githubusercontent.com/59416677/79107503-1a68e280-7d92-11ea-9848-8dfd9f5dfca9.png)

On load testing  Unmarshal is  consuming more memory and not releasing.The above Screenshot is done with memory profiling.Even doing GC for every 1000 cycles also not much a difference.Could u please suggest me.
This is the unmarshal code.
                protoformat = msgproto.somestrcutre{}
                err := proto.Unmarshal(Details, &protoformat)
Golang version : 1.13
Protobuf version :1.3.5

**Comment by dsnet** [comment]
The v1.3.x release is no longer receiving changes. The v1.4.x release is the future. can you try v1.4.0-rc.4? It has a completely re-written unmarshal implementation.

**Comment by dsnet** [comment]
Also, I should note that the above profile only indicates which functions allocate, but it doesn't show what data structures is actually causing the memory to stay alive. These data structures can be completely unrelated to protobufs.

**Comment by vasundhara785** [comment]
Its happening because of a goroutine leak.In the goroutine this unmarshal is presnt.So y does pprof show mmeory in unmarshal instead of  a gorutine???

**Comment by dsnet** [comment]
`pprof` does a good job answer the question: "where was the memory object allocated?" for which it is somewhat expected that `proto.Unmarshal` appear somewhere in that report.

The better question to ask when debugging a memory leak is "what reference to this piece of memory is keeping it alive (so that it doesn't get garbage collected)?" That's a much harder question to answer. It's been a while since I've needed to debug a memory leak, but I remember doing something like a core dump and analyzing the set of references to see which seem to be keeping a piece of memory alive.

I'm going to close this issue as I don't think there's anything actionable for us here.
