### ISSUE TITLE
protoc-gen-go: new message struct structure prevents struct copying in Go

### ISSUE THREAD

**Issue by tsimionescu** [golang/protobuf#1079]
**What version of protobuf and what language are you using?**
protoc-gen-go v1.20.0,   protoc v3.11.4

**What did you do?**
Re-generating code with the newer protoc-gen-go breaks code that is copying generated message structs. Go vet is showing the following error:

`assignment copies lock value to <var name>: <MsgStructType> contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex`

Previous generated code for a simple struct:
```
type AgentRegisterMessage struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Environment          string   `protobuf:"bytes,3,opt,name=Environment,proto3" json:"Environment,omitempty"`
	TestID               string   `protobuf:"bytes,4,opt,name=TestID,proto3" json:"TestID,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

Newly generated code, including the indirect reference to sync.Mutex:
```
type AgentRegisterMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IP          string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Environment string `protobuf:"bytes,3,opt,name=Environment,proto3" json:"Environment,omitempty"`
	TestID      string `protobuf:"bytes,4,opt,name=TestID,proto3" json:"TestID,omitempty"`
	Status      string `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
}
```

**What did you expect to see?**

The new message struct should be copy-able, or at least an explicit backwards compatibility change should be highlighted in the release notes.

**What did you see instead?**

`assignment copies lock value to <var name>: <MsgStructType> contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex`

**Anything else we should know about your project / environment?**

**Comment by dsnet** [comment]
This is working as intended. Generated messages to be shallow-copyable since they posses fields that are accessed atomically. This was already the case prior to the new release and has been so for several years now.

If you look at the [impl.MessageState](https://github.com/protocolbuffers/protobuf-go/blob/7dfcffe5a74a46c36b079a6e074cee6f821d85e6/internal/impl/message_reflect.go#L254-L260) type, you'll see that it embeds a [pragma.DoNotCopy](https://github.com/protocolbuffers/protobuf-go/blob/7dfcffe5a74a46c36b079a6e074cee6f821d85e6/internal/pragma/pragma.go#L24-L29) type, which is just a zero-sized array of `sync.Mutex`. The allows Go vet to flag what was already a pre-existing problem.

To copy a message, one should use [`proto.Clone`](https://pkg.go.dev/github.com/golang/protobuf/proto?tab=doc#Clone).

**Comment by tsimionescu** [comment]
This is somewhat surprising, since the old structs were often very simple Go structs, and I don't really understand what you mean by 

> Generated messages should not [be] shallow-copied since they posses fields that are accessed atomically.

I would be grateful if you could point me to some more information on this topic of atomic access vs struct copying.

Regardless, I have not been able to find any mention of this restriction in the docs, so if this was already assumed and it is now explicitly enforced, this is a clear positive change then. I will close the issue then.

Thank you for the quick reply!

**Comment by dsnet** [comment]
> posses fields that are accessed atomically.

The old XXX_sizecache, XXX_extensions, and others are examples of fields that are accessed atomically.

> I would be grateful if you could point me to some more information on this topic of atomic access vs struct copying.

In general, its not safe to shallow copy any struct type where you don't control the implementation since you have no guarantee that you aren't accidentally copying atomic variables and locks (which is exactly the case here). This expectation is not specific to protobufs, but more of a general idiom.

**Comment by mogrein** [comment]
Does that mean that I can't use range based for-loop on non-scalar repeated fields and MUST use index value to access them?
