### ISSUE TITLE
protoc-gen-go: panic when use github.com/google/go-cmp on generated messages

### ISSUE THREAD

**Issue by skipor** [golang/protobuf#1086]
I see, that there is a package `google.golang.org/protobuf/testing/protocmp` special for using `github.com/google/go-cmp` with protocolbuffers. 
Seems, that generated protobuf messages should be comparable with `cmp.Equal` and `cmp.Diff` may be used, but I got panic because of unexported fields in generated messages.

```go
func TestCmp(t *testing.T) {
	t.Log(cmp.Diff(&descriptorpb.DescriptorProto{}, &descriptorpb.DescriptorProto{}))
}
```

```
panic: cannot handle unexported field at {*descriptorpb.DescriptorProto}.state:
	"google.golang.org/protobuf/types/descriptorpb".DescriptorProto
consider using a custom Comparer; if you control the implementation of type, you can also consider using an Exporter, AllowUnexported, or cmpopts.IgnoreUnexported [recovered]
	panic: cannot handle unexported field at {*descriptorpb.DescriptorProto}.state:
	"google.golang.org/protobuf/types/descriptorpb".DescriptorProto
consider using a custom Comparer; if you control the implementation of type, you can also consider using an Exporter, AllowUnexported, or cmpopts.IgnoreUnexported
```

Package versions:
```
github.com/google/go-cmp v0.4.0
google.golang.org/protobuf v1.21.0
```

Can you clarify how `cmp` can and can't be used with generated protobuf messages?

**Comment by dsnet** [comment]
> Seems, that generated protobuf messages should be comparable with `cmp.Equal` and `cmp.Diff`

It was never intended for `cmp` to be directly used with generated protobuf messages, so this panic is working as intended. Prior to `protocmp`, it was expected that usages of `cmp` be provided with the proper way to compare protobuf messages using a custom comparer:
```go
cmp.Equal(x, y, cmp.Comparer(proto.Equal))
```
Unfortunately, there was a chance that `cmp.Equal` (or `cmp.Diff`) got the comparison "right" even if that option was not specified, giving the illusion that you don't actually need to specify the option.

For some background, I originally wrote `cmp` in mid-2017 precisely because `reflect.DeepEqual` did not work properly with protobuf messages. It had always been my vision to release a helper package to `cmp` that provided options for how to better compare protobuf messages. However, protobuf reflection did not exist in 2018, so we had to build that first. `protocmp` (at least for me) was the original motivating factor for why protobuf reflection was a necessary feature, but it was also a complex and huge undertaking and took time to convince others that it was necessary and also to actually implement. It's 2020, but we finally have `protocmp`.

> Can you clarify how cmp can and can't be used with generated protobuf messages?

Even prior to the v1.4.0 release, there has always been the presence of pseudo-internal "XXX_" fields that the compatibility document says should not be accessed (even indirectly by libraries like `reflect.DeepEqual` or `cmp.Equal`. For example, the `XXX_sizecache` field exists to speed up `proto.Marshal`. The presence of a cache means that there was always (even before v1.4.0) a decent chance that `cmp.Equal` would get the comparison wrong if it wasn't taught how to compare protobuf messages with either `cmp.Comparer(proto.Equal)` or `protocmp.Transform()`.

**Comment by skipor** [comment]
Thank you for your detailed response!  It would be great to put this examples to `protocmp` package doc.

Thank you, for proto API v2 and graceful migration schema!
My colleagues and I had written a lot in-company tools requiring proto reflection, before API v2 release. Now such tools may be written so much simpler.
