### ISSUE TITLE
protoc-gen-go: improve sizeof generated messages  

### ISSUE THREAD

**Issue by bogdandrutu** [golang/protobuf#1099]
# Background
The current generated code (seems to respect the order of declaring the proto members when generating the struct for a proto message):

Example proto:
```proto
message TestValue {
  int32 a1 = 1;
  int32 a2 = 3;
  int32 a3 = 5;
  int32 a4 = 7;
  bool b1 = 2;
  bool b2 = 4;
  bool b3 = 6;
  bool b4 = 8;
}

message TestOtherValue {
  int32 a1 = 1;
  bool b1 = 2;
  int32 a2 = 3;
  bool b2 = 4;
  int32 a3 = 5;
  bool b3 = 6;
  int32 a4 = 7;
  bool b4 = 8;
}
```

Generated struct:
```golang
type TestValue struct {
	A1                   int32    `protobuf:"varint,1,opt,name=a1,proto3" json:"a1,omitempty"`
	A2                   int32    `protobuf:"varint,3,opt,name=a2,proto3" json:"a2,omitempty"`
	A3                   int32    `protobuf:"varint,5,opt,name=a3,proto3" json:"a3,omitempty"`
	A4                   int32    `protobuf:"varint,7,opt,name=a4,proto3" json:"a4,omitempty"`
	B1                   bool     `protobuf:"varint,2,opt,name=b1,proto3" json:"b1,omitempty"`
	B2                   bool     `protobuf:"varint,4,opt,name=b2,proto3" json:"b2,omitempty"`
	B3                   bool     `protobuf:"varint,6,opt,name=b3,proto3" json:"b3,omitempty"`
	B4                   bool     `protobuf:"varint,8,opt,name=b4,proto3" json:"b4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

type TestOtherValue struct {
	A1                   int32    `protobuf:"varint,1,opt,name=a1,proto3" json:"a1,omitempty"`
	B1                   bool     `protobuf:"varint,2,opt,name=b1,proto3" json:"b1,omitempty"`
	A2                   int32    `protobuf:"varint,3,opt,name=a2,proto3" json:"a2,omitempty"`
	B2                   bool     `protobuf:"varint,4,opt,name=b2,proto3" json:"b2,omitempty"`
	A3                   int32    `protobuf:"varint,5,opt,name=a3,proto3" json:"a3,omitempty"`
	B3                   bool     `protobuf:"varint,6,opt,name=b3,proto3" json:"b3,omitempty"`
	A4                   int32    `protobuf:"varint,7,opt,name=a4,proto3" json:"a4,omitempty"`
	B4                   bool     `protobuf:"varint,8,opt,name=b4,proto3" json:"b4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

## First feature requests

Is there any option that we can pass to protoc or protoc-gen-go to generate a more compact for `TestOtherValue` similar to `TestValue`? If not can we add this as an option to order generated fields by size?

## Second feature requests

A more compact generated code:
```golang
type TestValue2 struct {
	A1                   int32    `protobuf:"varint,1,opt,name=a1,proto3" json:"a1,omitempty"`
	A2                   int32    `protobuf:"varint,3,opt,name=a2,proto3" json:"a2,omitempty"`
	A3                   int32    `protobuf:"varint,5,opt,name=a3,proto3" json:"a3,omitempty"`
	A4                   int32    `protobuf:"varint,7,opt,name=a4,proto3" json:"a4,omitempty"`
	B1                   bool     `protobuf:"varint,2,opt,name=b1,proto3" json:"b1,omitempty"`
	B2                   bool     `protobuf:"varint,4,opt,name=b2,proto3" json:"b2,omitempty"`
	B3                   bool     `protobuf:"varint,6,opt,name=b3,proto3" json:"b3,omitempty"`
	B4                   bool     `protobuf:"varint,8,opt,name=b4,proto3" json:"b4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
}
```

This test will print (**56** for TestValue and **48** for TestValue2):
```golang
func TestAttributeValue(t *testing.T) {
	t.Error(unsafe.Sizeof(TestValue{}))
	t.Error(unsafe.Sizeof(TestValue2{}))
}
```

So we should simply reorder the `XXX_sizecache` and `XXX_unrecognized` parameters gives us a nice win in the size of the struct.

**Comment by dsnet** [comment]
> Is there any option that we can pass to protoc or protoc-gen-go to generate a more compact for TestOtherValue similar to TestValue? If not can we add this as an option to order generated fields by size?

We generally avoid adding knobs and whistles to control how output looks. For something like this, it should be done automatically.

In regard to re-ordering fields, it's something we explored in the past and concluded that it was infeasible as it would break a bunch of user code that uses Go reflection and was already assuming the certain ordering. If such user code switches to protobuf reflection, the problems would go away. However, protobuf reflection was just recently released to the world and it will take time before sufficient number of users migrate.

**Comment by bogdandrutu** [comment]
@dsnet I would suggest then at least to take these suggestions in consideration for the protobuf reflection code (if they applied, have not checked that).

**Comment by neild** [comment]
Note that the more recent `protoc-gen-go` produces somewhat different output for the internal fields:

```go
type TestAllTypes struct {
        state         protoimpl.MessageState
        sizeCache     protoimpl.SizeCache
        unknownFields protoimpl.UnknownFields

        OptionalInt32          int32                                  `protobuf:"varint,1,opt,name=optional_int32,json=optionalInt32,proto3" json:"optional_int32,omitempty"`
        OptionalInt64          int64                                  `protobuf:"varint,2,opt,name=optional_int64,json=optionalInt64,proto3" json:"optional_int64,omitempty"`        // ...
}
```

We could get a small size improvement under some circumstances by moving sizeCache to the end of the header. Alternatively, we apparently could increase sizeCache to be an `int64` with no size penalty on 64-bit platforms, since the padding means it is already using 64 bits of space.

We've considered in the past that we should skip generating the size cache on some messages--it's cheap to recompute the size of a small message with no submessages, so we're better off saving the space.

An even better improvement would be to remove the size cache entirely by doing back-to-front marshaling, but that's a substantial change to the marshaler.

**Comment by dsnet** [comment]
Regarding removing size-cache for small messages, see #857. 
Regarding reducing the size of unknown fields, see #858.

**Comment by bogdandrutu** [comment]
Thanks @neild and @dsnet for your responses.

I think it will be good for the new protobuf reflection to reorder fields to save memory, especially because it is a new format we have a chance to fix this. Is there any issue to track that? Or that is not an issue in the new protobuf reflection?

**Comment by dsnet** [comment]
The issues isn't with the _implementation_ of protobuf reflection, but rather its _adoption_ which is outside our control. Our runtime implementation actually does not care about field ordering (with the exception of the `protoimpl.MessageState` field).

The issue is that _users_ of protobuf need to switch over to using protobuf reflection, and not rely on Go reflection to process protobuf messages dynamically. We do not control how many usages of go reflection there are in the world and it will take a while before adoption of protobuf reflection is sufficiently common place. Inside Google, we've been systematically migrating users from Go reflection to protobuf reflection, but it's a slow process.

**Comment by dsnet** [comment]
The order of the open-struct representation of messages is functionally frozen since much user code unfortunately depends on it through Go reflection even if it not something we guarantee (see [Hyrum's law](https://www.hyrumslaw.com/)). Since the generated order follows what is specified in the .proto source file, users who really want to optimize this can do so by re-ordering the fields in the .proto file.

Also, most message types have less than 4 fields, so focusing on #858 and #857 are likely to bear for fruit for memory reduction.
