### ISSUE TITLE
How to unmarshal from YAML?

### ISSUE THREAD

**Issue by lolin9** [golang/protobuf#1103]
The generated go files already contain `json` tags but what I want is to be able to unmarshal from `yaml` but unfortunately it requires its own tags which is complete pain and error prone for a big proto file. Is there a way, even a hacky one, to solve this?

**Comment by dsnet** [comment]
If you haven't already seen it, [the FAQ states](https://developers.google.com/protocol-buffers/docs/reference/go/faq#new-feature):

> Maybe. We always like suggestions, but we're very cautious about adding new things. See the Protocol Buffers FAQ.
>
> The Go implementation of protocol buffers strives to be consistent with the other language implementations. As such, we tend to shy away from features that are overly specialized to just Go. Go-specific features hinder the goal of protocol buffers being a language-neutral data interchange format.
>
> Unless your idea is specific to the Go implementation, you should join the protobuf discussion group and suggest it there.
>
> If you have an idea for the Go implementation, file an issue on our issue tracker: https://github.com/golang/protobuf/issues

The higher level issue of a protobuf-to-YAML conversion won't be a feature we can introduce and maintain since it's not something that the protobuf project itself has a specification for. If you want to propose that the protobuf project should have an official YAML mapping for protobuf, that should be done at https://github.com/protocolbuffers/protobuf.

Regarding hand-crafted `yaml` tags, see #52. The fact that `json` tags are even generated today is now regarded as a mistake.

In fact, the introduction of the `json` tags is a good example of why we stand by the guidance that we only do what the protobuf project itself specifies. The generated `json` tags were added before the development of the [official protobuf-to-JSON mapping](https://developers.google.com/protocol-buffers/docs/proto3) by the protobuf project because we thought it would be useful to have Go's own specific JSON mapping. However, that decision ended up hurting us badly since our variant of JSON mapping with the `json` tags is incompatible with the official protobuf-to-JSON mapping that the protobuf project did eventually define a year or two later. For that reason, the [`protojson`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) package warns that users should use that package instead of `encoding/json`.

**Comment by dsnet** [comment]
Closing since 1) any official support for YAML needs to come from the protobuf project itself, 2) attempts to declare custom tags is already captured by issue #52.

**Comment by lolin9** [comment]
I am not really sure how adding tags which is specific to Golang has anything to do with the protobuf specs. I think it is just the prevalent cult among the influential people in the Go community of not changing anything even if it's obviously correct and let everyone else simply eat shit.

**Comment by dsnet** [comment]
> let everyone else simply eat shit.

I encourage you to [read the Go code of conduct](https://golang.org/conduct).

> not changing anything even if it's obviously correct 

I don't see how adding support for YAML is "obviously correct". There is exist no official specification for how to map protobufs to YAML. If one existed, we will implement it. If it doesn't, we won't pretend like one exists. That seems like a fairly reasonable and straight forward approach.

Again, if you want to see a protobuf to YAML mapping, we're the wrong people to try and convince. Please file a proposal at https://github.com/protocolbuffers/protobuf.
