### ISSUE TITLE
Getting a deprecation warning message?

### ISSUE THREAD

**Issue by aaabhilash97** [golang/protobuf#1104]
Any idea why I'm getting this warning message?.
```
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
	A future release of golang/protobuf will delete this package,
	which has long been excluded from the compatibility promise.
```

Running these commands
```
protoc \
 		--proto_path=api/proto --proto_path=third_party/include \
  		--proto_path=third_party/ --grpc-gateway_out=logtostderr=true:pkg/api \
		  $(PROTO_ENTRY);

 protoc \
 		--proto_path=api/proto --proto_path=third_party/include \
  		--proto_path=third_party/ --grpc-gateway_out=logtostderr=true:pkg/api \
		  $(PROTO_ENTRY);
```

**Comment by dsnet** [comment]
The "github.com/golang/protobuf/protoc-gen-go/generator" package is the internal implementation of `protoc-gen-go` and was never intended for users to depend on. The reason it is publicly available is because the concept of an [`internal` package was not introduced until go1.4](https://golang.org/doc/go1.4#internalpackages). Even though the internal package mechanism did not exist back then, we have still documented that this package should not be used by users.

You're seeing the warning because either you are directly depending on the `generator` package or something you depend on is depending on the `generator` package. I recommend that you find out what is directly using the `generator` package and tell them to migrate to the [`protogen` package](https://pkg.go.dev/google.golang.org/protobuf/compiler/protogen?tab=doc) or to fork the generator package and depend on their own local fork.

**Comment by aaabhilash97** [comment]
Thanks to @dsnet .
Package [github.com/grpc-ecosystem/grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) using `generator` package internally.

**Comment by adi69** [comment]
> Thanks to @dsnet .
> Package [github.com/grpc-ecosystem/grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) using `generator` package internally.

Fix for this was merged https://github.com/grpc-ecosystem/grpc-gateway/pull/1260 and released in the version  https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.14.5

**Comment by adranwit** [comment]
Could you please silence this warning, annotation, and lack of that dependency in the future would be good enough trigger to address it, I have many 3rd party dep, it is almost impossible to get rid of that message. Once it's broken all 3rd part-owner address the issue I would think.

**Comment by jkuri** [comment]
Placing this in `go.mod` and running `go mod tidy` removes the warning for me.
```
replace (
  github.com/grpc-ecosystem/grpc-gateway => github.com/grpc-ecosystem/grpc-gateway v1.14.5
)
```
