### ISSUE TITLE
What is the expected behavior while un marshaling from the bytes that contains unknown fields?

### ISSUE THREAD

**Issue by dhruv459** [golang/protobuf#1105]
I am seeing some issues while a C++ plugin is inserting the unknown fields to a protobuf message and while the message is being unmarshalled, it is dropping the unknown fields injected earlier.

Protobuf version is `proto2` and golang version > `1.13`

**Comment by neild** [comment]
Unknown fields will be preserved when unmarshaling wire (binary) format data. When using a recent version of the code generator, they may be accessed via `m.ProtoReflect().GetUnknown()`. Unknown fields are preserved across an unmarshal/marshal cycle.

If this isn't happening for you, we'll need a reproduction case to say more about what is going on.

**Comment by dhruv459** [comment]
thanks for confirming. Is there anyway to access the unknown fields in the older version of the code generator once the data is unmarshaled? Essentially, I am looking for a way to access the unknown fields in the older code (generated without `ProtoReflect()` API).

**Comment by neild** [comment]
In older versions of the code generator, there will probably be an `XXX_unrecognized` field in the message struct containing the unknown fields.

**Comment by dsnet** [comment]
Even in older generated messages, I recommend against accessing the `XXX_unrecognized` field since you're code will be broken again once the message is regenerated with a newer generated. If you need to get a reflective view of an old messages, you can use [`proto.MessageReflect`](https://pkg.go.dev/github.com/golang/protobuf/proto?tab=doc#MessageReflect), which can be used to obtain a reflective view of a message even if it doesn't directly support it.

**Comment by dhruv459** [comment]
thanks for the quick help. I was using a generated code (from `protoc-gen-gogo`) which did not have the `XXX_unrecognized` field in the generated struct and which is why the unmarshal was dropping the unknown fields. Thanks for the valuable suggestions, will try to follow them.
