### ISSUE TITLE
Why are unknown fields getting dropped in serialization in jsonpb?

### ISSUE THREAD

**Issue by dhruv459** [golang/protobuf#1108]
Noticed that the unknown fields (`XXX_unrecognised`) are getting dropped while performing marshaling (`jsonpb.MarshalToString()` API) using jsonpb package. Is there any reason behind dropping these fields? 

Given proto.Marshal() API in `github.com/golang/protobuf/proto` persists the unknown fields while converting to wire (`binary`) format, the behavior in jsonpb seems to be deviating from it. Any thoughts?

`github.com/golang/protobuf` version at `1.3.3` and golang version is at `1.12.14`

**Comment by dsnet** [comment]
The unknown fields are expressed in the binary wire format (which loosely speaking is a sequence of field-number and value tuples). The JSON serializer does not emit unknown fields because it is fundamentally impossible to translate the unknown wire data to the JSON format: 1) the inability to convert a field number to a name 2) the binary wire format itself is insufficiently self-describing to translate an unknown value to arbitrary JSON.

**Comment by dsnet** [comment]
Closing this issue as there is nothing actionable for us here.
