### ISSUE TITLE
Protobuf 1.4.x not compatible with gogo/protobuf anymore

### ISSUE THREAD

**Issue by huydx** [golang/protobuf#1132]
I think it's not protobuf issue itself but still want to ask opinion of grpc team. Since 1.4.x release tells that

```
Backwards compatibility
This release maintains backwards compatibility with previous releases of this module. Any observable changes in behavior are to fix bugs, change unspecified behavior, or to make behavior more compliant with the protobuf specification. The compatibility document provides us the freedom to make changes in these areas.
Notable changes
```

We hope that it will not cause any problem even with 3rd party plugin like gogo/protobuf, but the release cause jsonpb could not works with (non-pointer) structs which generated by gogo/protobuf any more. For example this cast https://github.com/golang/protobuf/blob/master/jsonpb/encode.go#L131 .

**Comment by dsnet** [comment]
The `github.com/golang/protobuf` module has always had trouble operating on specialized types produced by `github.com/gogo/protobuf` module. Sometimes it worked, sometimes it failed silently, and sometimes it failed loudly (with an error), and sometimes it failed very loudly (with a panic). It is infeasible for the `github.com/golang/protobuf` module to support every variation of a type that `gogo/protobuf` produces.

Thus, either:
* types generated by `protoc-gen-gogo` should be serialized with the libraries provided by the `github.com/gogo/protobuf` module, OR
* the `github.com/gogo/protobuf` module be updated so that `protoc-gen-gogo` emits types that satisfy protobuf reflection, in which case they will work properly with the serialization functions in the `github.com/golang/protobuf` module.

> For example this cast https://github.com/golang/protobuf/blob/master/jsonpb/encode.go#L131 .

Can you explain more about why you think that cast is problematic?

**Comment by huydx** [comment]
@dsnet previous jsonpb implementation (1.3.5) does not expect field object to satisfy protobuf reflection (it expects parent object only), but with 1.4.x, it recursively do cast the field to proto.Message which make every gogoproto gen message which use non-pointer field to fail to serialize, because gogoproto with gogofaster will gen a struct looks like 

```

type struct Bar {
} 

func (b *Bar) Reset() {}
func (b *Bar) String() string {}
func (b *Bar)  ProtoMessage() {}

type struct Foo {
    b Bar ----> this due to gogofaster non-pointer option
}

``

**Comment by dsnet** [comment]
> previous jsonpb implementation (1.3.5) does not expect field object to satisfy protobuf reflection (it expects parent object only), but with 1.4.x, it recursively do cast the field to proto.Message

I'm not sure how why you believe it is not recursive in v1.3.5. See https://github.com/golang/protobuf/blob/84668698ea25b64748563aa20726db66a6b8d299/jsonpb/jsonpb.go#L175, where it checks for the custom marsahler and notice that the `marshalObject` function is called recursively.

**Comment by huydx** [comment]
I think it's better to imagine with a sample, so I make a reproduce repo at 

https://github.com/huydx/prototest

Try to replace protobuf version at go.mod to 1.4.2 will lead to below failure (while it's not with 1.3.5)

```
--- FAIL: TestHelloWorld (0.00s)
panic: message prototest.LabelMatcher is neither a v1 or v2 Message [recovered]
	panic: message prototest.LabelMatcher is neither a v1 or v2 Message

goroutine 19 [running]:
testing.tRunner.func1.1(0x15b4980, 0xc0002770b0)
	/usr/local/Cellar/go/1.14.1/libexec/src/testing/testing.go:941 +0x3d0
```

The protobuf file is copied from prometheus/prompb package https://github.com/prometheus/prometheus/tree/master/prompb which is generated by gogoproto.

**Comment by dsnet** [comment]
The fact that this worked in v1.3.x and below is accidental due to nuances in how the legacy Go reflection code is written. It wasn't intended to handle data structures other than what `protoc-gen-go` produces (with the exception of `proto.Message` types that implement `jsonpb.JSONPBMarshaler`, but this isn't the case here).

The `github.com/golang/protobuf` module's compatibility guarantees primarily cover what `protoc-gen-go` produces. The use of `protoc-gen-gogo` to tweak the generated API are in the realm of unspecified behavior and we're not obligated to keep them working.

I still stand by my earlier https://github.com/golang/protobuf/issues/1132#issuecomment-629378727:
* types generated by `protoc-gen-gogo` should be serialized with the libraries provided by the `github.com/gogo/protobuf` module, OR
* the `github.com/gogo/protobuf` module be updated so that `protoc-gen-gogo` emits types that satisfy protobuf reflection, in which case they will work properly with the serialization functions in the `github.com/golang/protobuf` module.

The former is what the user can do today, the latter is preferred, but requires the `gogo/protobuf` maintainers to implement reflection.

**Comment by huydx** [comment]
Thanks, I just want to confirm the intention from the protobuf team for this 

>  It wasn't intended to handle data structures other than what protoc-gen-go produces (with the exception of proto.Message types that implement)

I think the issue could be closed for now, thanks for quick handling.
