### ISSUE TITLE
protoreflect.ProtoMessage does not implement protoiface.MessageV1 (missing ProtoMessage method)

### ISSUE THREAD

**Issue by abhishekvaid** [golang/protobuf#1133]
I'm doing a tutorial from Youtube. Can't proceed because of this error. All information required to debug is in image. `go version: ` `1.14.3`

<img width="1440" alt="Screen Shot 2020-05-15 at 9 59 22 PM" src="https://user-images.githubusercontent.com/2530932/82074100-df8efd00-96f7-11ea-9171-3939eeda8252.png">

**Comment by dsnet** [comment]
There's a mismatch going on, since the code is trying to pass a [`"google.golang.org/protobuf/proto".Message`](https://pkg.go.dev/google.golang.org/protobuf/proto?tab=doc#Message) to [`"github.com/golang/protobuf/jsonpb".Marshaler.MarshalToString`](https://pkg.go.dev/github.com/golang/protobuf/jsonpb?tab=doc#Marshaler.MarshalToString), which expects a [`"github.com/golang/protobuf/proto".Message`](https://pkg.go.dev/github.com/golang/protobuf/proto?tab=doc#Message).

This can be resolved by either:
* Using the [`"google.golang.org/protobuf/encoding/protojson"`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson?tab=doc) package instead, which accepts the newer `Message` interface type you currently have on hand, OR
* Use the [`"github.com/golang/protobuf/proto".MessageV1`](https://pkg.go.dev/github.com/golang/protobuf/proto?tab=doc#MessageV1) adaptor function to convert the newer `Message` interface type you have to the legacy one.

I recommend the first solution:
```go
package serializer

import (
    "google.golang.org/protobuf/encoding/protojson"
    "google.golang.org/protobuf/proto"
)

func ProtobufToJSON(message proto.Message) (string, error) {
    b, err := protojson.MarshalOptions{
        Indent: true,
        UseProtoNames: true,
        EmitUnpopulated: true,
    }
    return string(b), err
}
```

**Comment by abhishekvaid** [comment]
Thanks a lot for quick turnaround.

**Comment by jatins** [comment]
Hi @dsnet Following up on this, I am still getting type mismatch. (happy to create a new issue if that helps) 

My generated code has following imports
```
import (
	proto "github.com/golang/protobuf/proto"   // <----
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)
```

My serializer has
```
package serializer

import (
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"   // <----
)

func ProtobufToJSON(message proto.Message) (string, error) {
	b, err := protojson.Marshal(message)
	return string(b), err
}
```

The code was generated using `protoc-gen-go`
```
go install google.golang.org/protobuf/cmd/protoc-gen-go
```

The legacy import in _generated_ code causes a type mismatch when I try to serialize a generated model to JSON using `ProtobufToJSON` function above . What would be the right set of packages to import here?

**Comment by jatins** [comment]
Ah, looks like I had to call the `ProtobufToJSON` like this `ProtobufToJSON(&message)`

**Comment by rohan-7-m** [comment]
try this.

func ProtobufToJSON(message proto.Message) (string, error) {
	marshaler := protojson.MarshalOptions{
		Indent:          "  ",
		UseProtoNames:   true,
		EmitUnpopulated: true,
	}
	b, err := marshaler.Marshal(message)
	return string(b), err
}
