### ISSUE TITLE
When I install protoc-gen-go, there's an error undefined: internal_gengo.SupportedFeatures, how to solve it ?

### ISSUE THREAD

**Issue by SoldierProgrammer** [golang/protobuf#1140]
$ go install github.com/golang/protobuf/protoc-gen-go/
# github.com/golang/protobuf/protoc-gen-go
github.com\golang\protobuf\protoc-gen-go\main.go:71:6: gen.SupportedFeatures undefined (type *protogen.Plugin has no field or method SupportedFeatures)
github.com\golang\protobuf\protoc-gen-go\main.go:71:27: undefined: internal_gengo.SupportedFeatures

what's wrong?

**Comment by dsnet** [comment]
Hi, it is highly likely this being run with a version of the Go toolchain without module support since the dependency on the `google.golang.org/protobuf` module is insufficiently new. Try running: `go get -u google.golang.org/protobuf/proto` and then re-running `go install github.com/golang/protobuf/protoc-gen-go`.

**Comment by dsnet** [comment]
Closing as this is most certainly an issue with the user setup and nothing actionable for us to do.
