### ISSUE TITLE
Why protoc-gen-go generate blank import `_ "${packageName}"`?

### ISSUE THREAD

**Issue by hitzhangjie** [golang/protobuf#1151]
>I know the `import _ "${packageName}"` can initialize the pakcage ${packageName}, just like register a new protofile in *.pb.go. But sometimes, this generated directives generated by protoc-gen-go are wrong, which cause build errors.

Hi, I came across a problem that protoc-gen-go will generate some blank import directives, which will cause build errors.

My directory structure is as following:

![image](https://user-images.githubusercontent.com/3725760/85042813-3b98e580-b1be-11ea-9ca3-a0a1ac755ddb.png)

each file's content is as following:

file: **helloworld.proto**
```
syntax = "proto3";
package helloworld;

import "request/request.proto";
import "response/response.proto";

service HelloWorld {
    rpc Hello(Request) returns(Response);
}
```

file: **request/request.proto**:
```
syntax = "proto3";
package helloworld;

message Request{}
```

file: **response/response.proto**:
```
syntax = "proto3";
package helloworld;

message Response{}
```

These 3 protofiles have the same pacakge directive `package helloworld`.
In this occasion, I want to organize generated helloworld.pb.go, request.pb.go and response.pb.go in the same directory, and they have the same `package helloworld` statement.

While, after I run `protoc --go_out helloworld.proto`, the generated helloworld.pb.go contains blank import statement like:
```

import (
      fmt "fmt"
      proto "github.com/golang/protobuf/proto"
      math "math"
      _ "request".         =======> causing build error
      _ "response"       =======> causing build error
)
```

Then I make some changes to the helloworld.proto. I changed helloworld.proto as following:
```
syntax = "proto3";
package helloworld;

import "request.proto";
import "response.proto";

service HelloWorld {
    rpc Hello(Request) returns(Response);
}
```

The directory and request/request.proto and response/response.proto don't change. 
Then I run command `protoc -I . -I request -I response helloworld.proto`, the generated helloworld.pb.go is right:
```
import (
      fmt "fmt"
      proto "github.com/golang/protobuf/proto"
      math "math"
)
```

In first occasion, the `import _ "request"` and `import _ "response"` is wrong, the package name is not "request" or "response", it's "helloworld".

I think it's a bug to handle package directive, I didn't test whether file option `go_package` has same problem.

**Comment by hitzhangjie** [comment]
In first occasion, If I specify the package name for each imported protofile like this:
`protoc --go_out=Mrequest/request.proto=helloworld,Mresponse/response.proto=helloworld:. helloworld.proto`
the generated helloworld.pb.go contains a self-import `import _ "helloworld"` which will also cause build errors.
![image](https://user-images.githubusercontent.com/3725760/85045041-06da5d80-b1c1-11ea-8761-27baa5aa5026.png)

**Comment by neild** [comment]
Let us say that we have `a.proto` and `b.proto`, in Go packages `packagea` and `packageb`. If `a.proto` imports `b.proto`, then `a.pb.go` will import `packageb`. If `a.pb.go` doesn't use any symbols from `packageb`, then this will be a blank import.

You need to tell the proto compiler which Go package each `.proto` file is in. (If you don't, it'll try to guess, but it'll almost certainly get it wrong.) The best way to do this is to put a `go_package` option in every `.proto` file with the full Go import path of the package for that file. Alternatively, you can provide `M` options on the command line for every `.proto` file.

>In first occasion, If I specify the package name for each imported protofile like this:
> ```
> protoc --go_out=Mrequest/request.proto=helloworld,Mresponse/response.proto=helloworld:. helloworld.proto
> ```
> the generated helloworld.pb.go contains a self-import import _ "helloworld" which will also cause build errors.

The problem here is that you're specifying a Go package for `request.proto` and `response.proto`, but not for `helloworld.proto`. Therefore, the code generator doesn't know that `helloworld.proto` is supposed to be in the same package as the others files.

The simplest fix is to put a `go_package` option in every `.proto` file. Alternatively, you could add a `M` flag for `helloworld.proto` as well.

**Comment by hitzhangjie** [comment]
@neild Thanks very much, I would try this later.
