### ISSUE TITLE
invalid generated code if using imports

### ISSUE THREAD

**Issue by strobil** [golang/protobuf#1172]
**What version of protobuf and what language are you using?**
Protobuf version: `v1.4.2` `d04d7b157bb510b1e0c10132224b616ac0e26b17`
Go version: `1.14.2 linux/amd64`
Protoc version: `3.12.2`

**What did you do?**
Unzip proto files from [proto.zip](https://github.com/golang/protobuf/files/4923818/proto.zip) and run a command below in directory with proto files.

`protoc -I . --go_out=plugins=grpc,paths=source_relative:. movie_service.proto`

**What did you expect to see?**
Valid generated code.

**What did you see instead?**
I'm getting compile error: `undefined: file_vod_link_proto_init`
If you look at `movie_service.pb.go:9436` you can see that function `file_vod_link_proto_init` is called.
But actualy it does not exists. Valid function name must be `file_movie_service_vod_link_proto_init`, what we can see in `vod_link.pb.go:431`

**Anything else we should know about your project / environment?**

**Comment by neild** [comment]
What command are you running to generate `vod_link.proto`?

The problem here is that `protoc` thinks `vod_link.proto` has different names when you generate `movie_service.pb.go` and `vod_link.pb.go`.

* `movie_service.pb.go` thinks the file is `vod_link.proto`.
* `vod_link.pb.go` thinks the file is `movie_service/vod_link.proto`.

These names need to be consistent when generating both files. A good way to ensure this is to generate both in one command (although this is not necessary):

```
protoc -I . --go_out=plugins=grpc,paths=source_relative:. movie_service.proto vod_link.proto
```

It's a bit unfortunate that the source file name matters here, but necessary to ensure proper initialization order. Since `movie_service.proto` depends on `vod_link.proto`, we need to ensure that `vod_link.pb.go`'s initializers run before `movie_service.pb.go`'s. The order of execution of `init` functions in the same Go package is not defined, so we do this by having each `init` function call the initializer for every file in the same Go package that it depends on. This requires giving a unique name to each initializer. Those names are based off the `.proto` source file name. If the name of a `.proto` file is not consistent between `protoc` calls, you can see the problem that you're having here.

**Comment by strobil** [comment]
Hello @neild! Thank you for your explanations!
So, if i have directory structure like this:

```
strobil@strobil-pc ~/work/proto $ tree  -d .
.
├── analytics_service
├── application
├── authentication_service
├── authentication_service_v2
├── authless_service
├── billing_service
├── deeplink_service
├── device
├── geo_service
├── image_service
├── interconnect
├── media_service
├── movie_service
├── promo_service
├── push_notification_log_service
├── search_service
├── signin_service
├── signup_service
├── sms_service
└── tv_service
```

Should i import `vod_link.proto` in `movie_service.proto` like this?
`import "movie_service/vod_link.proto";` instead of `import "vod_link.proto"`;

Then run protoc with these arguments? Is this correct way for me?
`protoc -I /usr/local/include/ -I /home/strobil/go/src -I /home/strobil/go/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis -I . --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:. --grpc-gateway_out=logtostderr=true,grpc_api_configuration=movie_service/movie_service.yaml,paths=source_relative:. movie_service/movie_service.proto movie_service/vod_link.proto`

**Comment by dsnet** [comment]
Maybe? The provided arguments contains relative paths (e.g., `-I .`), so without knowing where you are running the command from, we can't really confirm whether its right or not.

**Comment by strobil** [comment]
@dsnet thanks for reply. I'm closing this issue for now, my problem is resolved by running a command above. :+1:
