### ISSUE TITLE
Can you please add documentation for self-describing message usage?

### ISSUE THREAD

**Issue by Sharathnasa** [golang/protobuf#1215]
Hi Team,

Can you please add an example for self-describing message? i mean how to use this. I searched a lot but couldn't see any solid example of how to use it.

Regards,
Sharath

**Comment by dsnet** [comment]
I'm not sure what "an example for self-describing message" means. Does the documentation for the generated code help? See https://developers.google.com/protocol-buffers/docs/reference/go-generated

**Comment by Sharathnasa** [comment]
Hi dsnet,

Thank you for the reply.

What i mean is, i'm referring to this link(https://developers.google.com/protocol-buffers/docs/techniques#self-description) in order define generic container message type that would include a DescriptorSet and an Any fields.

What i'm not getting is how to build an instance of that generic message type and setting the field of type Any with an instance of your "Custom Object" message and setting the DescriptorSet field with the DescriptorSet of the"Custom Object" type.

So a small example of explaining on how to consume and use the self-describing message would help me a lot. I hope i'm explained it to you. If not please do let me know.

I saw the same discussion in the google groups 8 years back - https://groups.google.com/g/golang-nuts/c/StRsh0RscvA
, where someone was trying to add it to the official go-protobuf tutorial.

There is no blog or tuts which actually explains this. 

Regards,
Sharath

**Comment by dsnet** [comment]
You can do the following:
1. Use [`protodesc.NewFiles`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protodesc#NewFiles) to convert a `descriptorpb.FileDescriptorSet` into a `protoregistry.Files`.
2. Use the [`anypb.Any.MessageName`](https://pkg.go.dev/google.golang.org/protobuf/types/known/anypb#Any.MessageName) method to obtain the name of the underlying message in the Any and lookup a `protoreflect.MessageDescriptor` with [`protoregistry.Files.FindDescriptorByName`](https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/reflect/protoregistry#Files.FindDescriptorByName). Since the method returns a `protoreflect.Descriptor`, you'll need to do a type-assertion.
3. Use [`dynamicpb.NewMessage`](https://pkg.go.dev/google.golang.org/protobuf/types/dynamicpb#NewMessage) to create a new concrete instance of the message from the previously obtained `protoreflect.MessageDescriptor`.
4. Use the [`anypb.Any.UnmarshalTo`](https://pkg.go.dev/google.golang.org/protobuf/types/known/anypb#Any.UnmarshalTo) method to unmarshal from the Any message into the previously instantiated `dynamicpb.Message`.

**Comment by dsnet** [comment]
I should note that steps 2 to 4 could be simplified a little if we had #1216.

**Comment by Sharathnasa** [comment]
Hi Dsnet,

Thanks a lot for explaining the steps inspite of your busy schedule. Since i'm very new to GO, finding it difficult to follow here. It might be great if you explain with example(This is what i was referring it to as documentation or example)

Let me explain in detail.

1. Let's say i have Pixel.proto file as shown below and i compile it to pixel.pb.go.

`syntax = "proto3";

package testprotobuf;

message Pixel {
  // Session identifier stuff
  string session_id = 2;
}`

2. Now i define a Generic Message using self-describing feature as shown below and compile to genericmessage.pb.go.

`syntax = "proto3";

package saramaprotobuf;
import "google/protobuf/any.proto";
import "google/protobuf/descriptor.proto";

message GenericMessage {
  // Set of FileDescriptorProtos which describe the type and its dependencies.
  google.protobuf.FileDescriptorSet descriptor_set = 1;

  // The message and its type, encoded as an Any message.
  google.protobuf.Any message = 2;
}`

3. Now in the main function of the GO code as shown below i'm trying to build an instance of that generic message type and setting the field of type Any with an instance of Pixel message and setting the DescriptorSet field with the DescriptorSet of the Pixel message type. This is what i'm not getting

`func main() {
	topic := "yoyoyoyo"
	brokerList := []string{"localhost:9092"}

	producer, err := newSyncProducer(brokerList)
	if err != nil {
		log.Fatalln("Failed to start Sarama producer:", err)
	}

	go func() {
		ticker := time.NewTicker(time.Second)
		for {
			select {
			case t := <-ticker.C:
				elliot := &example.GenericMessage{
					DescriptorSet: 	"Here how to assign",
					Message:     "Here how to assign",
				}
				pixelToSend := elliot
				pixelToSendBytes, err := proto.Marshal(pixelToSend)
				if err != nil {
					log.Fatalln("Failed to marshal example:", err)
				}

				msg := &sarama.ProducerMessage{
					Topic: topic,
					Value: sarama.ByteEncoder(pixelToSendBytes),
				}

				producer.SendMessage(msg)
				log.Printf("Pixel sent: %s", pixelToSend)
			}
		}

	}()
}`

4. Then later comes at the consumer end on how to unmarshall the message, for which i can follow the steps which you explained i guess.

Please let me know if what i'm explaining is not clear

Regards,
Sharath

**Comment by dsnet** [comment]
You can obtain a obtain a new `anypb.Any` representing a message with [`anypb.New`](https://godoc.org/google.golang.org/protobuf/types/known/anypb#New).

There is not quick way to obtain a `FileDescriptorSet` for a generated message. You'll have to [do something like the following](https://play.golang.org/p/cRaxiVQOCYs):
```go
// FileDescriptorSetForMessage returns the FileDescriptorSet needed to represent m.
func FileDescriptorSetForMessage(m proto.Message) *descriptorpb.FileDescriptorSet {
	fds := new(descriptorpb.FileDescriptorSet)
	seen := map[protoreflect.FileDescriptor]bool{}
	appendFileDescriptor(m.ProtoReflect().Descriptor().ParentFile(), fds, seen)
	return fds
}
func appendFileDescriptor(fd protoreflect.FileDescriptor, fds *descriptorpb.FileDescriptorSet, seen map[protoreflect.FileDescriptor]bool) {
	if seen[fd] {
		return
	}
	seen[fd] = true

	fds.File = append(fds.File, protodesc.ToFileDescriptorProto(fd))

	imps := fd.Imports()
	for i := 0; i < imps.Len(); i++ {
		appendFileDescriptor(imps.Get(i).FileDescriptor, fds, seen)
	}
}
```
The code above may panic if the messages have not been regenerated with `google.golang.org/cmd/protoc-gen-go` since it fundamentally depends on first-class support for protobuf reflection.

**Comment by dsnet** [comment]
Closing. For questions regarding usage, it is better to ask on Slack or someone other means where you can more readily get immediate help. Consider joining the #protobuf channel or the Gophers slack workspace: https://gophers.slack.com/messages/general/


I don't think we need to add documentation for this. The fact that C++ doesn't have a pre-defined type for `SelfDescribingMessage` indicates that this is a niche and relatively rare use case. I certainly believe we need more examples in our module, but we still need to be judicious about which to add. Too many examples for use-cases that are less common is still counter-productive.
