### ISSUE TITLE
jsonpb/protojson: empty slices are omitted during serialization in APIv2

### ISSUE THREAD

**Issue by mfridman** [golang/protobuf#1229]
Upgrading to the new protobuf api v2 I noticed repeated fields are _no longer_ returned as empty lists. Marshaler is set with `EmitDefaults: false` (or `EmitUnpopulated: false`).

Flipping the marshaler to `true` will correctly return slices (nil or initialized empty) as `[]`

Problem is all existing types: `int64`, `string`, wrappers will now get returned as "0",  "" and null. As examples.

The assumption was JSON serialization would follow the Go spec, and in hindsight this was probably a bad decision (on our part to make that assumption).

1. Would you consider adding options to allow flipping the behaviour to match the Go spec with regards to JSON serialization?

2. Is there any way to keep the marshaler `EmitDefaults: false` (or `EmitUnpopulated: false`) while still being able to return an empty list?

**Comment by dsnet** [comment]
This isn't an issue with Go spec. It's an issue with regard to how the protobuf data model (call it the protobuf spec if you will), which has no distinction between a nil repeated field and an empty one. The `google.golang.org/protobuf/protojson` implementation is correct, while the `github.com/golang/protobuf/jsonpb` implementation is wrong.

> 1. Would you consider adding options to allow flipping the behaviour to match the Go spec with regards to JSON serialization?

It seems wrong to preserve what is fundamentally a bug in the old implementation into the new implementation, which aims for correctness as a first-class feature.

Furthermore, it is impossible for the new implementation to preserve the old behavior since the new implementation is written entirely in terms of protobuf reflection, which does not provide any ability to detect this distinction. So, even if we wanted to provide an option, it would not be possible to implement.

**Comment by mfridman** [comment]
> It seems wrong to preserve what is fundamentally a bug in the old implementation into the new implementation

I don't think this was a bug per se, the implementation made sense for Go, since it can detect nil vs initialized but empty. This property allowed protobuf to be a drop-in replacement where Go JSON serialization was used. 

So if anything its a limitation with protobufs and other language implementations who cannot distinguish.

It' 99% possible with `EmitUnpopulated: false` to get the desired behaviour, but the inability to return an empty list is the one feature missing. 

Anyways, if there are no solutions or workarounds for this case then it is what it is. Thanks for your time.

**Comment by cybrcodr** [comment]
I think what @mfridman pertains as Go spec, he meant the behavior in encoding/json.  However, the proto JSON serialization has its own specification that is different from that and has to behave the same across different language implementations.
