### ISSUE TITLE
No documentation about go_package option

### ISSUE THREAD

**Issue by komly** [golang/protobuf#1249]
Hi, I tried to understand what protobuf option `option go_package = ".;types"` do.
But seems like protobuf have no documentation about it.
Maybe we need to add?

We have only an old issue explaining this https://github.com/golang/protobuf/issues/139

**Comment by dsnet** [comment]
It's documented at https://developers.google.com/protocol-buffers/docs/gotutorial#defining-your-protocol-format and https://developers.google.com/protocol-buffers/docs/reference/go-generated#invocation.

The godoc package page for `protoc-gen-go` has little documentation for how it operates since it points to https://developers.google.com/protocol-buffers/ which has more comprehensive documentation about the invocation of `protoc` and the meaning of `.proto` options.

I should note that `go_package = ".;types"` is a non-sensible value since it should be set to the Go import path for the Go package that is generated for that `.proto` file. An import path of `.` is pretty meaningless.

**Comment by komly** [comment]
@dsnet  in this docs no mention about the meaning of first and second part of option value "first;second".
But if you will just follow any tutorial you will see the hint while generating: please add option go_package = ".;types"

**Comment by komly** [comment]
<img width="983" alt="Screenshot 2020-12-02 at 02 51 21" src="https://user-images.githubusercontent.com/4579028/100810308-43d19e00-3449-11eb-8fb1-4aa3971a241b.png">

**Comment by neild** [comment]
I just updated the documentation at https://developers.google.com/protocol-buffers/docs/reference/go-generated#package with a bit more detail on `go_package`.

The `go_package` option should contain the full import path of the Go package which contains the generated code for the `.proto` file. The Go package name will be derived from the last path component of the import path. The package name may be overridden by appending `;<package_name>` to the `go_package` option, but this should be seldom, if ever used, since Go package names should almost always be directly related to the package import path.

`option go_package = ".;types"` states that the Go import path is `"."` and the Go package name is `types`. Since an import path of `"."` is clearly incorrect, this is not a reasonable value for the `go_package` option.

If a tutorial is suggesting that value for the `go_package` option, the tutorial should be fixed.

**Comment by komly** [comment]
@neild Big thanks for documenting, this is just what I needed.
