### ISSUE TITLE
How to import package in *.proto if project version is v2 with go mod

### ISSUE THREAD

**Issue by bailantaotao** [golang/protobuf#1250]
Hi,

I have upgraded my project to v2, but i meet unexpected result from *.protoc.
In my go.mod file has defined:
```
module github.xxx/bbb/ccc/v2

go 1.13
```

*.proto
```
syntax = "proto3";

package pb;

import "google/api/annotations.proto";
import "github.xxx/bbb/ccc/v2/service/pb/types.proto";   <-- It's not working

```
Error message: 
```
github.xxx/bbb/ccc/v2/service/pb/types.proto: File not found.
```

But!!! if i remove the version(v2) from import string, it works! 

*.proto
```
syntax = "proto3";

package pb;

import "google/api/annotations.proto";
import "github.xxx/bbb/ccc/service/pb/types.proto";   <-- It's works.

```

Is there a better way to solve this?

**Comment by puellanivis** [comment]
The import paths for `protoc` and `go` differ in this regard. Since `protoc` has to accommodate all languages, not just Go, `protoc` is unaware of any go module pseudo-path-elements introduced by versioning.

In short, you’re not importing this file through go, so go module versioning is irrelevant to the import path.

**Comment by bailantaotao** [comment]
Thank you very much!
