### ISSUE TITLE
types/known/structpb: add convenient way to convert proto.Message to Struct.

### ISSUE THREAD

**Issue by Antonboom** [golang/protobuf#1259]
**Is your feature request related to a problem? Please describe.**
https://github.com/golang/protobuf/issues/1258

**Current workaround**
```golang
user := &User{
     Id:    "user-2",
     Email: "user2@gmail.com",
}

uData, err := protojson.Marshal(user)
failOnErr(err)

userStruct := new(structpb.Struct)
failOnErr(protojson.Unmarshal(uData, userStruct))

data, err = json.Marshal(&ResponseWithValue{
Users: map[string]*structpb.Value{
	"user-1": structpb.NewNullValue(),
	"user-2": structpb.NewStructValue(userStruct),
},
```

**Describe the solution you'd like**
```golang
user := &User{
     Id:    "user-2",
     Email: "user2@gmail.com",
}

userStruct := structpb.NewFromMessage(user, opts...)
```

Detailed example [here](https://github.com/Antonboom/protojson_map_with_null_issue/blob/master/main.go#L86).

**Comment by puellanivis** [comment]
🤔 I’m not sure how we could provide any better or simpler solution. One could potentially write a generic solution that takes a `proto.Message` and uses proto reflection to render it into a `map[string]interface{}` (or perhaps less widely useful outside of this particular interest as a `*protopb.Struct`), instead of into a wire or text format. But I’m not sure that would run any faster than a roundtrip through marshal and unmarshal.

To get anything not using generic proto reflection, it would require either the code generator (protoc, or human) to write a novel function that would do the conversion. Putting it in the protoc code generator, means potential code and binary bloat, where each message needs to have this function provided, and if elimination cannot be sure which ones will be used, then the binaries have to just keep all of them… potentially a big issue if there are thousands of protobufs in a binary.

On the other hand, maintaining a hand-coded mapping of a specific proto message to a `map[string]interface{}` is of course error prone, and maintenance overhead. But at least in that case, it can be applied sparingly only when needed, and profiling demonstrates that the generic proto reflection option wouldn’t be practical.

**Comment by dsnet** [comment]
Add a `structpb.NewFromMessage` helper would hide the fact that this is literally just a round-trip through `protojson.Marshal` and `protojson.Unmarshal` without any performance benefits at all. The relatively low use of `structpb` does not justify maintaining a specialized implementation to do something semantically equivalent that is faster.

For example, `proto.Merge` is semantically equivalent to a roundtrip `proto.Marshal` and `proto.Unmarshal`. However, that function is both a commonly used and well-defined operation where the significant implementation complexity justifies its inclusion.

Unless it can be shown that the other major protobuf implementations (i.e., C++ and Java) has equivalent functionality, we won't add this helper since one of our high-priority goals is to remain consistent with the other implementations.

**Comment by puellanivis** [comment]
Indeed. As I noted, one should really only be writing this sort of thing if/when one finds through profiling that the round-trip through marshal/unmarshal is insufficient. And in that case, a hand-written specifically narrow implementation is probably the better implementation both in terms of simplicity and speed.

This just doesn’t seem as broadly useful as would really be necessary to justify working on it. Even a generic version would likely end up being insufficient all the same as a round-trip marshal/unmarshal, if profiling shows it to be a bottleneck…

**Comment by Antonboom** [comment]
Ok, I'll make this helper in my projects.

I saw similar problems / questions from people on the Net and thought that such a function would be useful. Let it drive bytes back and forth inside.

If you have no desire to add it to `structpb`, then you can close the issue.

Thanks!

**Comment by dsnet** [comment]
Closing since it's unlikely that we add this. We don't have the bandwidth to maintain a optimized `proto.Message` to `structpb.Value` converter. Without an optimized conversion, it is easy for users to round-trip `protojson.Marshal` from a `proto.Message` and `protojson.Unmarshal` into a `structpb.Value`.

I should note that `protojson.Unmarshal` is probably much slower than `protojson.Marshal` since it needs to allocate all the individual data structures within a `structpb.Value`. Thus, I'm not even sure how much faster an optimize conversion would be since it would need to do the approximate same number of allocations.
