### ISSUE TITLE
A parsing error occurred when debugging a large string

### ISSUE THREAD

**Issue by markWEwe** [golang/protobuf#1261]
When I use debug, I want to test whether I can parse a large string with multiple line breaks, and then when my field has been parsed。
![image-20201226143844201](https://user-images.githubusercontent.com/53363670/103146703-2235af00-4788-11eb-8f6b-a57071f84d53.png)
an error, proto: UpChatMsg: illegal tag 0 (wire type 0) appears

**Comment by puellanivis** [comment]
We’re missing a lot of data to be able to help you here.

What proto file generated this message?

How did you generate the `[]byte` that you are trying to decode? It looks like it’s hitting upon a `[]byte{ …, 0x00, … }` in the encoded message for a fieldNum|wireType composition, which is invalid. Are you perhaps suffixing your data with a `NUL` character? That could potentially cause this problem. One does not need to encode the end of a byte slice with a `NUL` character, like in some languages. The length is tracked directly, rather than being indirectly calculated based on a magic `NUL` terminator.

**Comment by dsnet** [comment]
The protobuf wire form lacks any magic numbers, such that consuming random data has an almost certain chance of incorrectly parsing fine or producing a parse error that is completely unrelated to the actual problem at hand.

I suggest verifying that you really are parsing protobuf wire data. You can consider using the [`protopack`](https://pkg.go.dev/google.golang.org/protobuf/testing/protopack) package to parse the data and see if it looks like some valid wire data:
```go
import "google.golang.org/protobuf/testing/protopack"

var m protopack.Message
m.Unmarshal(b) // where bis the binary data you are trying to parse.
fmt.Println(m)
```

Also, without a reproducer, there is not much we can do.

**Comment by markWEwe** [comment]
Thank you for your help. This is a bug of mine. When using the unsafa package to process data, the data pointed to by the pointer is stored on the stack, so my data is lost. Now that the bug has been resolved, I will use the unsafa package more carefully in the future and carefully check for any possible errors. Prevent low-level mistakes
