### ISSUE TITLE
Migrating off gogo/proto to new Google Proto API

### ISSUE THREAD

**Issue by rogeralsing** [golang/protobuf#1262]
Hi.
We are currently using the gogo/proto API as it allows some custom code generation in https://Proto.Actor
Specifically this:

```protobuf
message PID {
    option (gogoproto.typedecl) = false;
    option (gogoproto.stringer) = false;
    string address = 1;
    string id = 2;
}
```

Then we have this custom type declaration for this message:

```go
type PID struct {
	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`

	p *Process   //<------ special field, not part of the message
}
```

We know this is super flaky, but it allows us to cache a performance critical value.
Not having this, we would have to resort to something like looking up the PID from a dictionary.

Is there any way to do something similar using the new Google API?

Thanks
//Roger

**Comment by dsnet** [comment]
The Google-maintained Go protobuf implementation intentionally shies away from any custom code generation options since this goes against [the goal that protocol buffers be language agnostic](https://developers.google.com/protocol-buffers/docs/reference/go/faq#custom-code). The other major language implementations (e.g., C++, Java, etc.) don't provide this functionality.

If you want/need this feature, then the [gogo/protobuf](https://github.com/gogo/protobuf) project needs to be updated to support the latest [runtime API](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect). However, that is work that is separate from what this project is specifically responsible for.
