### ISSUE TITLE
--go_opt=M$FILENAME=$IMPORT_PATH behaviour

### ISSUE THREAD

**Issue by crossworth** [golang/protobuf#1266]
Hi, I was reading the documentation about [Packages](https://developers.google.com/protocol-buffers/docs/reference/go-generated#package) and is stated that:

>  As an alternative to the go_package option, the Go import path for a .proto file may be specified on the command line with the --go_opt=M=$FILENAME=$IMPORT_PATH flag to protoc. 

But testing, I'm not sure if I understand what it really does, what I expected was that I could use the command line option as another way to set the `option go_package`.

setting the `option go_package` on the file.
a.proto
```
syntax = "proto3";

option go_package = "google.golang.org/protobuf/types/known/timestamppb";

message A {
    string field = 1;
}
```

`protoc.exe --go_out=./ a.proto` results in a file created at:
`google.golang.org/protobuf/types/known/timestamppb/a.pb.go` with package name `timestamppb`.

on the command line flag:
a.proto
```
syntax = "proto3";

message A {
    string field = 1;
}
```

`protoc.exe --go_opt=Ma.proto=google.golang.org/protobuf/types/known/timestamppb --go_out=./ a.proto` results in a file created at:
`a.pb.go` with package name `a`.

`libprotoc 3.12.4`
`protoc-gen-go.exe v1.25.0`

Is this the correct behaviour? Shouldn't the two options produce equal outputs?

**Comment by neild** [comment]
Specifying the import path in a `go_package` option vs. with `--go_opt=M` ideally should produce equal outputs.

It's been a while since I looked at this in detail, but I believe that the current behavior is originally unintentional (the various ways of setting the package name and import path grew organically over time and are frankly a mess), which was then preserved unchanged in the newer `google.golang.org/protobuf` implementation.

You can explicitly specify the package name by adding `;package_name` to the `go_package` option or `--go_opt=M` flag:

```
--go_opt=Ma.proto=google.golang.org/protobuf/types/known/timestamppb;timestamppb
```

We should update the documentation to clarify this and/or change the implementation of `--go_opt=M` to be more consistent.

**Comment by crossworth** [comment]
Using `--go_opt=Ma.proto=google.golang.org/protobuf/types/known/timestamppb;timestamppb` produces the correct package name, but will not create the folder(s).

`option go_package` creates the following folder structure:
`google.golang.org/protobuf/types/known/timestamppb/a.pb.go`

`--go_opt=Ma.proto=google.golang.org/protobuf/types/known/timestamppb;timestamppb` creates only the file `a.pb.go`.

So yeah, there seems to be some sort of inconsistency.

Thanks for the reply and clarification.

**Comment by neild** [comment]
There's definite inconsistency resulting from new features being added over time. It's one reason we're trying to be very careful about adding any new knobs customizing import paths and/or package names--too many changes that look good in isolation combine to form a bit of a mess.

In the immediate term, you should be able to get any supported behavior by explicitly specifying everything: `--go_opt=M<file>=<import_path>;<package_name>` and `--go_opt=paths=[import,source_relative]` or `--go_opt=module=<module>`.

**Comment by dsnet** [comment]
I looked into this a bit. It turns out that the issue has little to do with the "M" flag, but rather with odd behavior from the original implementation of `protoc-gen-go` that we carried forward.

In particular, the difference in behavior likely stems from here:
https://github.com/protocolbuffers/protobuf-go/blob/23ccb359e1a18a9fc77be08aeff34f00d79f4f11/compiler/protogen/protogen.go#L510-L514

**Comment by dsnet** [comment]
Release v1.26.0 will require that .proto files specify the expected Go import path either by an source-local `go_package` option or with a command-line `M` flag. We'll probably fix this behavior at the same time.

**Comment by dsnet** [comment]
https://golang.org/cl/301953/ fixes the behavior to be more regular.
