### ISSUE TITLE
How to get a `DescriptorProto` for a message from a `FieldDescriptorProto`

### ISSUE THREAD

**Issue by Abbyyan** [golang/protobuf#1267]
The same question to https://github.com/golang/protobuf/issues/821. 
How can i get  a `DescriptorProto` for a message from a `FieldDescriptorProto` just like in C# https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/reflection/field-descriptor#class_google_1_1_protobuf_1_1_reflection_1_1_field_descriptor_1abbfe2c68b372d42ae42f837e1644218c please?

Is there any progress now please? Thanks a lot.

**Comment by Abbyyan** [comment]
I've read the issue https://github.com/golang/protobuf/issues/364 , but is confused about how to get the Type message info from a `descriptor.FieldDescriptorProto`. Hope for your help. Thanks a lot.

**Comment by neild** [comment]
Going with the literal question, you can't get a `DescriptorProto` from a `FieldDescriptorProto` alone, because a `FieldDescriptorProto` doesn't contain the necessary information.

The equivalent of the referenced C# API would be [`(protoreflect.FieldDescriptor).Message`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect#FieldDescriptor).

You can get a `protoreflect.MessageDescriptor` from a generated message type's `ProtoReflect` method.

Alternatively, if you have a `descriptorpb.*Proto` message, you can convert it into a `protoreflect` descriptor type with the [`protodesc`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protodesc) package, or look up registered types in the [`protoregistry`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoregistry) package.

**Comment by dsnet** [comment]
Closing as inactionable. We try to keep this issue tracker about actionable issue. For questions regarding usage, it is better to ask on Slack or someone other means where you can more readily get immediate help. Consider joining the #protobuf channel or the Gophers slack workspace: https://gophers.slack.com/messages/general/
