### ISSUE TITLE
Why is `go_package` being required in source code?

### ISSUE THREAD

**Issue by mieubrisse** [golang/protobuf#1272]
I have `.proto` files that will be used by the server (written in Golang) and multiple clients in several languages (including Golang). It seems like it makes the most sense that the Go package is specified at generation time, so that the same `.proto` files can be used for both the server and the client (who will have different modules). I found the `--go_opt=M=....`, but it still elicits the warning:
```
2021/01/20 17:29:40 WARNING: Missing 'go_package' option in "healthcheck_service.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
```
It seems like requiring this in the source code (rather than at generation time) would mean you can get only one Go module out of a `.proto` file, thereby restricting the utility of `.proto` as an interface right?

**Comment by dsnet** [comment]
Proper use of the `M` flag avoids the missing `go_package` warning. However, the documentation for it is wrong and needs to be fixed. That is #1264.

Fundamentally, `protoc-gen-go` needs to know the Go package that types live in in order to properly resolve type references. Thus, either `go_package` option or a `M` flag must be specified.
