### ISSUE TITLE
How to reuse the same fields in two message?

### ISSUE THREAD

**Issue by CrayfishGo** [golang/protobuf#1288]
There are two message as below:
```
message FirstMessage{
  int64 id = 1;
  string category = 2;
  string description = 3;
  string name = 4;

  repeated int64 some_ids = 5;
}

message SecondMessage{
  int64 id = 1;
  string category = 2;
  string description = 3;
  string name = 4;

  repeated string same_names = 5;
  string time_str = 6;
}
```

The two message have some same fields. So How to reuse them?

**Comment by dsnet** [comment]
Hi, the protobuf language has no concept of inheritance or embedding to reuse a message's fields in another message. If you want a feature like this, I recommend filing an issue at https://github.com/protocolbuffers/protobuf.

Since this doesn't affect the Go implementation of protobufs, closing as inactionable.
