### ISSUE TITLE
encoding/protojson: Is there a way to mimic json.NewDecoder logic through protojson?

### ISSUE THREAD

**Issue by Thessiah** [golang/protobuf#1290]
Hi, I'm currently using protojson to marshal data being sent to a client but the regular encoding/json package's NewDecoder().Decode() to decode the http request body from the client. Is there a good way to mimic this behavior using protojson? I'm running into an issue where the client can't send enums as strings because it doesn't naturally unmarshal into proto structs, so I'm using the UseEnumNumbers flag but really want to move to an implementation with string enums instead of numbers. Thanks!

**Comment by dsnet** [comment]
Hi, I'm not sure what you're asking for.

> Is there a good way to mimic **this behavior** using protojson

It is unclear what exactly "this behavior" is referring to.

If you're using `protojson.Marshal` to marshal the data, you should be using `protojson.Unmarshal` to unmarshal the data. Use of `encoding/json` on the generated structs does not correctly comply with the official specification for how protobuf messages are to be serialized as JSON.

**Comment by Thessiah** [comment]
Sorry for not being clear; encoding/json has a [decoder](https://golang.org/pkg/encoding/json/#Decoder) struct which is essentially unmarshal except it unmarshals from an io.stream instead of []byte. Since http.request gives access to its body through an io.stream, this decoder is typically the recommended way to unmarshal from a request body, so I was hoping to be able to do this with protojson.

**Comment by dsnet** [comment]
Can't you accomplish the equivalent behavior by using [`io.ReadFull`](https://golang.org/pkg/io/#ReadFull) to read the contents of an `io.Reader` as a `[]byte`?

**Comment by Thessiah** [comment]
Ah yeah that works I can just manually convert it into a []byte. I think the decoder has some special stuff to handle errors and large inputs, but I can just implement that myself. Thanks!

**Comment by puellanivis** [comment]
> Since http.request gives access to its body through an io.stream, this decoder is typically the recommended way to unmarshal from a request body, so I was hoping to be able to do this with protojson.

Note that this can lead to unexpected behavior though. Doing a request with something like:
```
{} asdflkjaödskjföalkdsjföakdsjföl
```

Will typically not break `json.Decoder.Decode()`, even though there is irrelevant data t the end of the request. The difference is a subtle one, and rarely commonly comes up in normal code use, but it could leave an `http.Response.Body` with unread text, or any of a various number of weird issues. But then `io.ReadFull` comes with concerns as well…

All these things have tradeoffs, and even if you might default to `json.Decoder.Decode()` don’t assume that just because you have a `io.Reader` that you should automatically use `json.Decoder`.

More interesting concerns exist with `json.Encoder` though, where “but I have an `io.Writer`, I should use a json.Encoder, right?” meets with “under the hood, `json.Encoder` encodes into a `bytes.Buffer` the same as `json.Marshal`, so you’re really not better off.”
