### ISSUE TITLE
protoc-gen-go: unable to determine Go import path for ...

### ISSUE THREAD

**Issue by agamm** [golang/protobuf#1294]
We started getting this from today. I see that you've also created 2 releases in the past hours. 
Is this related?

Full error:
```
go generate ./mypath
protoc-gen-go: unable to determine Go import path for "something.proto"

Please specify either:
	• a "go_package" option in the .proto source file, or
	• a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--go_out: protoc-gen-go: Plugin failed with status code 1.
mypath/other.go:1: running "protoc": exit status 1
```

**Comment by vishnubabu-s** [comment]
Yes, I too started getting this error from today.

I do have script to update as below and it pulled latest
    go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
   
And error, same as above

go: found github.com/golang/protobuf/proto in github.com/golang/protobuf v1.5.1
go: found github.com/golang/protobuf/protoc-gen-go in github.com/golang/protobuf v1.5.1
go: google.golang.org/protobuf upgrade => v1.26.0
protoc-gen-go: unable to determine Go import path for "common.proto"

Please specify either:
        • a "go_package" option in the .proto source file, or
        • a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--go_out: protoc-gen-go: Plugin failed with status code 1.

**Comment by neild** [comment]
https://developers.google.com/protocol-buffers/docs/reference/go-generated#package

As the error says, you need to specify the import path of the Go package containing the .proto file. The simplest way to do this is with a go_package option:

```
option go_package = "example.com/package/name";
```

The Go protocol buffer compiler has been printing a warning about missing import paths since `v1.4.0` (released about a year ago), and stating that specifying the import path would eventually become a requirement. `v1.5.0` upgrades this warning to an error.

**Comment by dsnet** [comment]
As @neild mentioned. This change is deliberate and was announced a year ago. The need for specifying the import path always is to prevent other strange edge cases where artifacts that depend on the import path information operate in unexpected ways when it is missing.
