### ISSUE TITLE
types/known:structpb: support more custom types in constructors

### ISSUE THREAD

**Issue by torkelrogstad** [golang/protobuf#1302]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to use methods from the `structpb` package, such as `NewStruct` or `NewValue`.

Consider this program:

```go
package main

import (
	"fmt"
	"google.golang.org/protobuf/types/known/structpb"
)

type customString string

func main() {
	fmt.Println(structpb.NewValue(customString("hey")))
}
```

This errors with `proto: invalid type: main.customString`.

**Describe the solution you'd like**
I believe it makes sense for the `structpb` methods to convert custom types to its underlying types. In this case, that'd mean that doing `structpb.NewValue(customString("hey))` and `structpb.NewValue("hey")` would be identical.

**Additional context**
Go playgroud for this: https://play.golang.org/p/rtT2xqXI71u

**Comment by neild** [comment]
I don't think this would be a good change, since it would silently discard type information. Right now you can safely write this for any type T:

```go
var x T // some type T
v, err := structpb.NewValue(x)
if err != nil {
  return err
}
x2 := v.Interface().(T) // the type stored in the value is the type returned by `v.Interface`
```

Relaxing the types of values passed to `structpb.NewValue` would silently change the type stored in the value. Better to make the loss of type information explicit at creation time:

```go
v, err := structpb.NewValue(string(x)) // very clear that the structpb.Value holds a string
```

**Comment by torkelrogstad** [comment]
This is fine for a string/string variant, but quickly gets hard if you're doing this with a more complext structure with `structpb.NewStruct`. I've been working around this for now by doing a JSON marshal/unmarshal roundtrip, which feels "wrong"

**Comment by dsnet** [comment]
`structpb.NewValue` has to draw the line somewhere for what Go types it supports. The set currently supported are clearly documented and are either:
* built-in Go types for JSON primitives (i.e., JSON bool, string, number, and null)
* `[]interface{}` for JSON array
* `map[string]interface{}` for JSON object
since there is an obvious mapping for them and the implementation is pretty straight-forward.

Expanding the list of supported types to more than the above would cause the implementation of `structpb` to functionally have much of the same complexity as `encoding/json` (which is non-trivial). We're not going to maintain that (and if we did provide the feature, our implementation would probably just do a roundtrip `json.Marshal` and `json.Unmarshal` anyways).

As such, it is entirely appropriate to do a round-trip marshal and unmarshal in the application code as it clearly surfaces what is functionally happening.
