### ISSUE TITLE
protoc-gen-go: json tags on structs should honor json_name field option.

### ISSUE THREAD

**Issue by adam-azarchs** [golang/protobuf#1307]
**What version of protobuf and what language are you using?**
golang: protoc-gen-go version `v1.26.0`

**What did you do?**
Declare a simple message with a json_name field option, e.g.
```protobuf
syntax = "proto3";

message Foo {
  string bar = 1 [json_name = "thing"];
}
```

**What did you expect to see?**
I expected to see `json` tags on the struct be consistent with the proto tags, e.g.
```golang
type Foo struct {
...
	Bar string `protobuf:"bytes,1,opt,name=foo,json=thing,proto3" json:"thing,omitempty"`
}
```
**What did you see instead?**

```golang
type Foo struct {
...
	Bar string `protobuf:"bytes,1,opt,name=foo,json=thing,proto3" json:"foo,omitempty"`
}
```
For the most part, using `protojson.{Marshal,Unmarshal}` and `json.{Marshal,Unmarshal}` produce functionally equivalent results for most use cases, so this discrepancy is a bit of a land-mine when interacting with e.g. library code that is just calling `json.Marshal`.

Sure, you can always add `MarshalJSON` and `UnmarshalJSON` in a sidecar file to make them use `protojson`, and for more complex types that's probably a good idea to do that anyway, but the discrepancy seems entirely unnecessary.

Of course, at this point there may be people depending on this discrepancy.  Though if you're using different json serializations of the same objects in different places, that's pretty brittle and you'll probably end up breaking yourself.

**Comment by adam-azarchs** [comment]
The fix for this is pretty easy.  In
https://github.com/golang/protobuf/blob/ae97035608a719c7a1c1c41bed0ae0744bdb0c6f/protoc-gen-go/generator/generator.go#L2222-L2225
`jsonName` should be determined more like it is in https://github.com/golang/protobuf/blob/ae97035608a719c7a1c1c41bed0ae0744bdb0c6f/protoc-gen-go/generator/generator.go#L1537-L1541
e.g.
```golang
		fieldName, fieldGetterName := ns[0], ns[1]
		typename, wiretype := g.GoType(message, field)
		tag := "protobuf:" + g.goTag(message, field, wiretype)
		if jsonName := field.GetJsonName(); jsonName != fieldName {
			tag += fmt.Sprintf(" json:%q", jsonName+",omitempty")
		}
```

**Comment by dsnet** [comment]
> Of course, at this point there may be people depending on this discrepancy. Though if you're using different json serializations of the same objects in different places, that's pretty brittle and you'll probably end up breaking yourself.

Unfortunately, this is not a theoretical concern, but a real problem.

Generation of the `json` struct tags predates the creation of the [official protobuf-to-JSON mapping](https://developers.google.com/protocol-buffers/docs/proto3#json) back when we thought "wouldn't it be cool if you could serialize protobufs as JSON?" without checking what the main protobuf project planned on doing in this area. As you noted, they are  similar, but not the same. We now consider it a mistake to have ever generated `json` tags since it makes use of `encoding/json` with generated message incompatible with the official JSON specification. It's one of the reasons that we now have a policy of not accepting feature requests that are not generally provided by the other main protobuf implementations. As such, we consider the generation of `json` tags an unfortunate "feature" that we wish we never provided. I don't think we should change how the `json` tag is derived other than considering how we could one day remove it.

**Comment by adam-azarchs** [comment]
That makes sense, unfortunately.  In that case at this point maybe the best thing to do would be to contribute a linter to e.g. [golangci-lint](https://github.com/golangci/golangci-lint) to attempt to detect uses of `json.Marshal` or `json.Unmarshal` with proto messages and warn people away from doing that.

**Comment by adam-azarchs** [comment]
I agree that any linter changes would be a completely separate issue, in a completely separate repository, and probably not something the golang protobuf team would be expected to spend any time on themselves.  I don't agree that they wouldn't be worth doing. The metalinters such as e.g. golangci-lint are modular - it currently has [48 linter modules](https://golangci-lint.run/usage/linters/) and very few people turn on all of them (some of them in fact probably offer conflicting advice).  So if a project is depending on doing something that the linter would complain about, that's fine - they'd just not use that linter module.  The idea would be to discourage adding additional dependency on such error-prone behavior in new code.

**Comment by tonybase** [comment]
I think we should fix this problem by using ProtoBuf to define the structure and also make it easy to extend, for example by using HTTP binding parameters. We have used gogoproto and useProtoNames, both of which are not the best practices. We really hope to solve this problem. Or use flag option for compatibility.
