### ISSUE TITLE
release: provide Windows as .zip archive with binaries as .exe extensions

### ISSUE THREAD

**Issue by 89z** [golang/protobuf#1323]
I just went here:

https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.26.0

and both the Windows archives are invalid. The both contain a file, `protoc-gen-go`, which is not a valid name for Windows executables. Output should be named `protoc-gen-go.exe` or similar.

**Comment by dsnet** [comment]
Seems reasonable. I can imagine switching the archive format also from `.tar.gz` to `.zip` since the former is not particularly common on Windows. 

For prior art, both the [Go toolchain](https://golang.org/dl/) and [protobuf toolchain](https://github.com/protocolbuffers/protobuf/releases) releases for Windows are provided as a `.zip` file and executables have a `.exe` extension.
