### ISSUE TITLE
proto: Merge typed nil source panic after v1.5.0

### ISSUE THREAD

**Issue by tz70s** [golang/protobuf#1324]
**What version of protobuf and what language are you using?**

```
github.com/golang/protobuf v1.5.0
google.golang.org/protobuf v1.26.0 
```

**What did you do?**

Simple reproducer:

```go
// pb files served on etcd repo
func TestProtoMerge(t *testing.T) {
	dst := &etcdserverpb.AuthDisableRequest{}

	proto.Merge(dst, nilAuth())
}

func nilAuth() *etcdserverpb.AuthDisableRequest {
	return nil
}
```

**What did you expect to see?**

I'm not very sure whether this is an intended behavior. Current situation is:

```go
proto.Merge(dst, nil) // this one will always panic

proto.Merge(dst, (*T)(nil)) // this one will panic after v1.5.0 or by google.golang.org/protobuf v1.26.0
```

I think the reason is this CL: https://go-review.googlesource.com/c/protobuf/+/300869

Background of this CL is trying to support the `aberrant message` and the `proto.Merge` turns to use marshal and unmarshal to accomplish to work (for performance reason?).

But this happens the case when there's a "typed nil pointer" fall into interface and then the `proto.Merge` behavior is different.

Understand there's no guarantees on third party code generators but what's the expected behavior here?

We shouldn't allow nil as a source? Either a typed nil as a source? Especially the later case is probably useful:

```go
proto.Merge(dst, req.Content)
```

that we don't need to do extra nil check for `Content`.

**What did you see instead?**

As illustrated.

**Anything else we should know about your project / environment?**

Nope.

**Comment by puellanivis** [comment]
🤔 I think the case of having a typed proto.Message nil could be reasonably useful, considering that sub-messages that do not appear on the wire are typed nils.

I suppose, we’re handling that case more directly at the point where it is considered as a field, in that case not expecting one to use `proto.Merge` on a submessage itself, but that seems like something potentially useful to do at times. Though, if the caller has the typed nil directly, rather than through an interface, then a question can arise of where to efficiently test that nil value. Where that would be is before putting it into the interface and losing the ease of just `if m != nil { … }`.

**Comment by tz70s** [comment]
> Though, if the caller has the typed nil directly, rather than through an interface, then a question can arise of where to efficiently test that nil value. Where that would be is before putting it into the interface and losing the ease of just `if m != nil { … }`.

Thanks for the quick input! I think the at least for `legacyMerge` case, what about using `in.Source.IsValid` check first?

Seems won't introduce significant extra overhead.

**Comment by tz70s** [comment]
Understood, thanks for your help!
