### ISSUE TITLE
compatibility question of protobuf reflection 

### ISSUE THREAD

**Issue by yann-sjtu** [golang/protobuf#1333]
The JSON and text format implementations have been ported to use protobuf reflection under the hood instead of relying on Go reflection since v1.4.0. And there are some incompatible cases wthen processing zero values. Such as
```golang
type Reply struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=isOk,proto3" json:"isOk,omitempty"`
	Msg                  []byte   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

var reply types.Reply
err := jsonpb.UnmarshalString(`{"isOk":false, "msg":""}`, &reply)
if err != nil {
    panic(err)
}
fmt.Printf("%#v\n", reply.Msg)
```
`reply.Msg` is `[]byte{}` in version before v1.4.0 but `nil` since v1.4.0. Is it the difference between protobuf reflection and Go reflection?

**Comment by dsnet** [comment]
Hi. Yes, the difference in how nil is handled is due to the difference between protobuf reflection and Go reflection. In particular, protobuf reflection interacts with a protobuf message according to the protobuf data model, which does not preserve presence for `[]byte` in proto3. See https://github.com/golang/protobuf/releases/tag/v1.4.0#v1.4-nil-values for more information.

**Comment by yann-sjtu** [comment]
> Hi. Yes, the difference in how nil is handled is due to the difference between protobuf reflection and Go reflection. In particular, protobuf reflection interacts with a protobuf message according to the protobuf data model, which does not preserve presence for `[]byte` in proto3. See https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0#v1.20-nil-values for more information.

thanks
