### ISSUE TITLE
docs:  mutability of List/Map/Message values in Get and Set

### ISSUE THREAD

**Issue by fdymylja** [golang/protobuf#1346]
The `protoreflect.Message` interface documentation does not specify how mutabilty of `protoreflect.Value` for `Message`, `List` and `Map` types works when `Get`ting them or `Set`ting them.

For example, something that I found inconsistent was the fact that if you `Set` a `MapValue` or `MessageValue` and you modify it after, the changes are reflected in the message, this does not appear to be the case for `ListValue`.

**Comment by neild** [comment]
We're missing a line of documentation on `Message.Set`. `List.Set`, `List.Append`, and `Map.Set` all state:

```go
// When setting a composite type, it is unspecified whether the set
// value aliases the source's memory in any way.
```

`Message.Set` should have the same text.

In addition, it would be good to have a clear description of aliasing behavior somewhere. The summary is that a `protoreflect.Value` acquired from a composite value's `Get` or `Mutable` method is guaranteed to alias the original value, and that it is otherwise unspecified when aliasing occurs.

So this is a valid way to append to a repeated field:

```go
list := m.Mutable(someRepeatedFieldDesc).List()
list.Append(v) // appends v to the field in m
```

But this is not:

```
list := m.NewField(someRepeatedFieldDesc).List()
m.Set(someRepeatedFieldDesc, list)

// It is unspecified whether `list` aliases the field in `m`,
// so the next line may or may not modify m.
list.Append(v)
```

**Comment by neild** [comment]
> We're missing a line of documentation on Message.Set. List.Set, List.Append, and Map.Set all state:

Actually, this line is there. No idea how I missed it.
