### ISSUE TITLE
Generate `New....` constructors with Go bindings

### ISSUE THREAD

**Issue by mieubrisse** [golang/protobuf#1353]
**Is your feature request related to a problem? Please describe.**
Right now, if a new field is added in the .proto file, the user needs to find all instances where that message object is created and remember to add the new field. If they forget, they'll get a runtime error.

**Describe the solution you'd like**
Generating constructors would cause new fields to be a compile-time break.

**Describe alternatives you've considered**
A generated builder could be even better (to better handle the optional case), though would be more difficult to implement

**Comment by puellanivis** [comment]
I’m confused. In proto3, if I add a new field to the `proto.Message` example below, it should not create either a compile-time or runtime error:
```
p := &pb.ExampleMessage{
  ExampleInt:    42,
  ExampleString: "ohai",
}
```

In general, Go allows us to avoid making `New…` constructors for everything, because unless there is significant work that has to be done under the hood (e.g. `http.Request`), we can just use complex literals directly instead.

Using `New…` constructors does not really provide any advantage over and yet comes with all the same disadvantages of using positional literal notation.

If instead, this is a case of adding a new `required` field to a proto2 message, this is a known issue, and part of why “required considered harmful”. You cannot add new `required` fields to a proto2 and keep backwards compatibility. Unfortunately, this can only really be enforced through engineering policy (manual or automated).

**Comment by mieubrisse** [comment]
Hi @puellanivis , the desire would be to allow for intentionally creating compile breaks when adding a new field (which doesn't happen when using struct literals since Go will just silently choose the null value of that field). With generated constructors, a client using those constructors would 1) be forced to think about and initialize every value they want for every field (analogous to Rust) and 2) receive a nice compile break if they added a field.

**Comment by neild** [comment]
The fact that adding a new field to a message does not break existing code is deliberate, and consistent across all protobuf implementations that I'm familiar with.

Indeed, dealing gracefully with unknown fields in serialized messages is a primary feature of the protobuf binary encoding.

**Comment by mieubrisse** [comment]
And that backwards compatibility makes sense to me - a new field added on the sender's side shouldn't break the receiver. This request for constructors is more targeted (and wouldn't break that backwards compatibility) - for senders that choose to opt in via the constructors, it would simply make sure they remember to use the new field they added. This is how https://github.com/tokio-rs/prost does it, by leaning on Rust's "forced to instantiate all fields of the struct" mechanism.

**Comment by puellanivis** [comment]
As far as I can understand the request here, the feature request is to permit Go to function more like Rust. (Note: it is not “null value” in Go jargon it is the “zero value”)

The disadvantage noted above still exists on how to order the constructor parameters. This request additionally kind of flies in the face of Go’s design principles of sensible defaults, i.e. the zero values should always have a sensible semantic value.

**Comment by mieubrisse** [comment]
(Apologies for the delay - work's been crazy!) And thank you for the explanation; "zero value" makes more sense!

Just my $0.02 regarding constructor parameter ordering: the way I'd use it would be to just look up the constructor params and slot in what's necessary, so at least for me the ordering wouldn't matter. And if users wanted to specialize just a few values, they could always drop back to the struct literal way.

**Comment by puellanivis** [comment]
I understand that documentation can be looked up, and some IDEs even conveniently label the parameters for the coder.

But one also cannot add parameters to `NewThing` constructor in a backwards-forwards compatible way. Callers will be required to refactor their code, or call additional functions to change settings on that object. This is considered Bad Form in Go, and especially so when using protobufs in Go.

If there is no work that needs to be done on the object to make it usable, such that all the constructor is ever doing is `func NewThing(foo string) *Thing { return &Thing{ Foo: foo }` then why call a function to do something that I can be done more clearly and more understandably at the call site?

But people are in the habit of using constructors, because whatever language they are coming from usually can’t just build objects any other way… so they are stuck with using constructor functions as they have no choice. But Go has a really easy and convenient way to build complex literals, right? Why make ones life more difficult?

**Comment by neild** [comment]
Closing this, because the current behavior is deliberate. Adding a field to a protobuf message should not break existing code that uses that message.
