### ISSUE TITLE
protojson: duped field validation immediately return error without checking expecting format

### ISSUE THREAD

**Issue by ttyfky** [golang/protobuf#1362]
## What version of protobuf and what language are you using?**
Version:  1.27.1

## Summary 
An error is started to be returned when there is duped field as in [protojson/decode.go]( https://github.com/protocolbuffers/protobuf-go/blob/v1.27.1/encoding/protojson/decode.go#L203). 
However, there is a case the same field in proto is sent as different formatting like snake_case and camelCase as following example of GCP.

https://cloud.google.com/pubsub/docs/push#receiving_messages
```
{
    "message": {
        "data": "..."
        "messageId": "2070443601311540",
        "message_id": "2070443601311540",
        "publishTime": "2021-02-26T19:13:55.749Z",
        "publish_time": "2021-02-26T19:13:55.749Z",
    },
   "subscription": "projects/myproject/subscriptions/mysubscription"
}
```

I understand this is not usual usage, but this is made by Google which we don't have control.
To handle this, probably selecting the value where the field is associated with struct tag (although this needs to be done out of unmarshalMessage  of decoder...) or something else would be required rather than just returning dup error immediately.

# If possible, provide a recipe for reproducing the error.
This was found in [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) because protojson is underlying in the framework.
Related ticket which has detail: https://github.com/grpc-ecosystem/grpc-gateway/issues/2340

## What did you expect to see?
Do not return an error immediately when there is dup field as different format, but check if matching field name exists in the tag of the marshaling struct, then bind the value if exist.

## What did you see instead?
`duplicate field` error is returned immediately.

**Comment by cybrcodr** [comment]
I'm not familiar with the Cloud pubsub APIs and I don't know what the corresponding proto message for the JSON message you're pointing out.  I'm guessing here that there is a proto field named `message_id` with corresponding JSON name `messageId`, and similarly a proto field named `publish_time` with corresponding JSON name `publishTime`.

While parsers are required to accept the converted lowerCamelCase name or the proto field name, it is problematic to accept both in the same JSON input because the values for the field may be different.  Given that there are no prescribed field ordering in JSON, this means there will be ambiguity in the result.  It is also unknown which field value should be used or ignored if the values are different.  Having the parser return an error is most sensible here to avoid such issues.

The doc https://cloud.google.com/pubsub/docs/push#receiving_messages does not mention any corresponding proto message.  Implementing a grpc-gateway handler using a proto message to match the spec there would not work.  I would raise this issue with Cloud pubsub given that they have publish a spec that may not be implemented in a grpc-gateway handler using a proto message, but perhaps that may be intended?

**Comment by ttyfky** [comment]
Thanks for the comment. I think all of your points are valid and I'm also thinking same, but wanted to check if there's any workaround or idea...

> The doc does not mention any corresponding proto message. 
I'm pretty sure the message is created based on [this proto](https://github.com/googleapis/googleapis/blob/7b6a2ceed6cacf676b3918b1703b3ddd6322444c/google/pubsub/v1/pubsub.proto#L219), but Google populate two types of format for single field for historical reason that they used to be using snake_case but they changed the mind to use camelCase and eventually keep the both field format.

Anyway I'll also check with GCP if they can improve the situation...

**Comment by VJftw** [comment]
Did you find a solution for this? Just ran into this now and it seems like nothing has changed on the GCP side. I've ended up writing a HTTP middleware to remarshal the PubSub message without the underscored fields before it hits GRPC Gateway logic:

```golang
func GCPPubSubPushMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {

		defer next.ServeHTTP(w, r)

                // can filter your requests more tightly here (e.g. the request path matches the push path)
		if r.Header.Get("from") == "noreply@google.com" {
			pubSubMsg := &struct {
				Message struct {
					Data        string `json:"data"`
					MessageID   string `json:"messageId"`
					PublishTime string `json:"publishTime"`
				} `json:"message"`
				Subscription string `json:"subscription"`
			}{}
			if err := json.NewDecoder(r.Body).Decode(&pubSubMsg); err != nil {
				log.Printf("err decoding body: %s", err)
				return
			}

			newBodyBytes, err := json.Marshal(pubSubMsg)
			if err != nil {
				log.Printf("err marshalling new body: %s", err)
				return
			}

			r.Body = ioutil.NopCloser(bytes.NewBuffer(newBodyBytes))
			r.ContentLength = int64(len(newBodyBytes))
		}

	})
}
```

any better alternatives would be greatly appreciated!
