### ISSUE TITLE
Is there a way to pass a fixed-size array between the client and server?

### ISSUE THREAD

**Issue by rkapka** [golang/protobuf#1368]
I have the following type:

```
type CustomType [4]byte
```

I would like to use this type for a proto field that is declared as `bytes`. Changing the types in the generated `.pb` file is not a problem, but since protobuf does not support arrays I receive this error:

```
invalid Go type data.CustomType for field main.Test.value
```

I tried implementing `Marshal` and `Unmarshal`:

```
func (c *CustomType) Marshal() ([]byte, error) {
	return c[:], nil
}

func (c *CustomType) Unmarshal(b []byte) error {
	if len(b) != 4 {
		return errors.New("invalid array length")
	}
	*c = [4]byte{b[0],b[1],b[2],b[3]}
	return nil
}
```

Unfortunately this does not work and the methods are not even executed. Their docs say that they are deprecated, but they do not say what to use instead. Is there a way to make this work?

**Comment by dsnet** [comment]
Hi @rkapka, unfortunately this is not possible. The Go implementation of protocol buffers aims to be a faithful implementation of the [protobuf language](https://developers.google.com/protocol-buffers/docs/proto3). Since the protobuf type system has no concept of a fixed-length repeated field, there is no way to correlate a protobuf type with a Go array type.

**Comment by neild** [comment]
> Changing the types in the generated .pb file is not a problem

I'm afraid we only support generated code produced by `protoc-gen-go`. Modifying the generated files in any way is not supported.
