### ISSUE TITLE
Mark struct internal fields as JSON non-serialized

### ISSUE THREAD

**Issue by torkve** [golang/protobuf#1379]
**Is your feature request related to a problem? Please describe.**

Some popular tools like k8s controller-gen[[1]](https://github.com/kubernetes-sigs/controller-tools/issues/609) inspect structs and can fail if struct has fields that are not explicitly exported or unexported to JSON:
```
/.../google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go:180:2: encountered struct field "state" without JSON tag in type "Timestamp"
/.../google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go:181:2: encountered struct field "sizeCache" without JSON tag in type "Timestamp"
/.../google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go:182:2: encountered struct field "unknownFields" without JSON tag in type "Timestamp"
```

This happens both for internal protobuf messages and user-defined ones.

It appears that old golang protobuf generator marked[[2]](https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L2034) internal struct fields with JSON no-export tag, while this newer one doesn't, which leads to a problem described.

**Describe the solution you'd like**
I propose to add `json:"-"` tag to generated internal fields.

**Describe alternatives you've considered**
Other solution is to ignore internal fields in generators, but controller-gen developers are clearly not interested[[3]](https://github.com/kubernetes-sigs/controller-tools/pull/584#issuecomment-940459870) in using any protobuf structs as source.

**Comment by neild** [comment]
It's unfortunate that we have any `json:` tags in generated structs at all, because the `encoding/json` package cannot correctly serialize a protobuf message to/from the canonical JSON encoding. The supported way to JSON encode/decode a protobuf message is with the [`protojson`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) package.

I'm dubious that we should make any changes to make it easier to accidentally misuse a generated protobuf struct with `encoding/json`.

**Comment by dsnet** [comment]
> It appears that old golang protobuf generator marked[2] internal struct fields with JSON no-export tag, while this newer one doesn't, which leads to a problem described.

Those were explicitly marked with `json:"-"` because the fields were exported. The new generator keeps internal fields unexported.

Honestly, I think this is a bug with `controller-gen`. The fact that the field is unexported should itself be a proper signal that the field should be ignored from the perspective of JSON.

**Comment by torkve** [comment]
Thank you, I see your point.

In my case, the problem is that we have some common structures we would like to reuse in k8s CRDs, and while our own k8s controller would know what part of spec must be parsed with `protojson`, the `controller-gen` tool which generates OpenAPI schemas, operates with just structs, knowing nothing about protobuf itself.

While I strongly agree with the opinion, that it would be best to fix in the `controller-gen`, the [3] above shows that its developers unfortunately antagonize this idea :-(

From the other point of view I see no drawbacks from the adding unexported tag to internal fields itself.
So I have made a PR after all to add the tag: https://go-review.googlesource.com/c/protobuf/+/360454
I hope it still can be accepted, even though it is not the best way to fix the issue.  :-)

**Comment by neild** [comment]
Closing: This may or may not be a bug in controller-gen, but what's definite is that the `json:` field tags are not something we want to encourage use of. The supported ways to serialize a protobuf message are the `proto`, `protojson`, and `prototext` packages.
