### ISSUE TITLE
oneof's field missing json tag

### ISSUE THREAD

**Issue by chenjie199234** [golang/protobuf#1427]
**What version of protobuf and what language are you using?**
Version: `v1.28.0`
**What did you do?**
this message
```
message test{
	oneof data {
		int32 number = 1;
		string str = 2;
	}
}
```
will be generated to
```
type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*Test_Number
	//	*Test_Str
	Data isTest_Data `protobuf_oneof:"data"`
}

type isTest_Data interface {
	isTest_Data()
}

type Test_Number struct {
	Number int32 `protobuf:"varint,1,opt,name=number,proto3,oneof"`
}

type Test_Str struct {
	Str string `protobuf:"bytes,2,opt,name=str,proto3,oneof"`
}

func (*Test_Number) isTest_Data() {}

func (*Test_Str) isTest_Data() {}
```
There's no json tag.So i can't control the json field's name by control the proto message's filed's name.

**What did you expect to see?**
has json tag like the normal proto message's field
**What did you see instead?**
no json tag

**Comment by puellanivis** [comment]
Please use [google.golang.org/protobuf/encoding/protojson](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) and not `encoding/json` using `json` tags is now considered something of a mistake. We rushed to implement a JSON mapping because it would be so easy to just add `json` tags, but now it’s incompatible with the defined standard.

If you find you cannot control the name of the `oneof` field, this is because in protobuf, a `oneof` is not properly a field. It’s syntactic sugar around ensuring that only one of the contained fields will be set in any given message. Thus, its proper JSON encoding is compatible with the fields occurring flatly in the message, not encapsulated in something else.

That is, the data producible by the proto you present would be: `{ "number": 42 }` or `{ "str": "foo" }` Note that there is nothing here that corresponds to the `oneof` construct.

**Comment by chenjie199234** [comment]
the performance of protojson is ......
![捕获](https://user-images.githubusercontent.com/29348971/159940692-a55fa693-a150-402b-b8c2-fa9d5b5a58c4.PNG)

**Comment by chenjie199234** [comment]
> Please use [`google.golang.org/protobuf/encoding/protojson`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) and not `encoding/json` using `json` tags is now considered something of a mistake. We rushed to implement a JSON mapping because it would be so easy to just add `json` tags, but now it’s incompatible with the defined standard.
> 
> If you find you cannot control the name of the `oneof` field, this is because in protobuf, a `oneof` is not properly a field. It’s syntactic sugar around ensuring that only one of the contained fields will be set in any given message. Thus, its proper JSON encoding is compatible with the fields occurring flatly in the message, not encapsulated in something else.
> 
> That is, the data producible by the proto you present would be: `{ "number": 42 }` or `{ "str": "foo" }` Note that there is nothing here that corresponds to the `oneof` construct.

the performance of protojson is ....
![捕获](https://user-images.githubusercontent.com/29348971/159941049-e827dea7-99b8-471e-b3db-86e6ad760750.PNG)

**Comment by puellanivis** [comment]
We are aware of the performance issues https://github.com/golang/protobuf/issues/1285

However, we will not be adding a `json` tag to the `oneof` fields, that would fundamentally violate the standards that we have to hold to. And `encoding/json` is known to produce a non-standard encoding, in part because of this particular case.

I’m sorry that probably no answer I’m able to give here will be acceptable to you.
