### ISSUE TITLE
-devel suffix in release build

### ISSUE THREAD

**Issue by amenzhinsky** [golang/protobuf#1434]
**What version of protobuf and what language are you using?**
v1.28.0

**What did you do?**

Link is taken from [v1.28.0](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.28.0) release page.

```sh
wget -O- https://github.com/protocolbuffers/protobuf-go/releases/download/v1.28.0/protoc-gen-go.v1.28.0.linux.amd64.tar.gz | tar xzf -
./protoc-gen-go --version
```
**What did you expect to see?**
```
protoc-gen-go v1.28.0
```

**What did you see instead?**
```
protoc-gen-go v1.28.0-devel
```

And this makes our codegen linters fail.

**Comment by stapelberg** [comment]
Thanks for the report. This seems to have been an issue with the release binaries. We have updated the release binaries on GitHub, and now the reported version is `protoc-gen-go v1.28.0` as expected.

**Comment by stapelberg** [comment]
Thanks for letting us know. We’ll investigate tomorrow.

**Comment by martijnjanssen** [comment]
I have found that the issue was on my side. Using a `go get` on this repo resulted in the `-dev` suffix. Correctly installing with `go install google.golang.org/protobuf/cmd/protoc-gen-go@latest` yielded a non-dev suffix.

Finding the correct way to install is a bit hard to find, I expected this repo to have an installation instruction. Maybe a nice change to make since the `go get` method is replaced with `go install` over the last year.

**Comment by stapelberg** [comment]
Thanks for the follow-up.

This repository’s README contains a pointer to the documentation:

> See the [developer guide for protocol buffers in Go](https://developers.google.com/protocol-buffers/docs/gotutorial) for a general guide for how to get started using protobufs in Go.

…which in turn contains the `go install` command you need: https://developers.google.com/protocol-buffers/docs/gotutorial#compiling-your-protocol-buffers
