### ISSUE TITLE
structpb: NewValue returns error if it receives int8

### ISSUE THREAD

**Issue by aculage** [golang/protobuf#1463]
**What version of protobuf and what language are you using?**
protobuf: 1.28.0
go: 1.18

**What did you do?**
[This function](https://github.com/protocolbuffers/protobuf-go/blob/fc44d00d5a99973a6deb0863d6aaa7446c016066/types/known/structpb/struct.pb.go#L316) returns "invalid type: int8" when int8 is fed into it.

Seems that int16, uint8 and uint16 would produce similar behavior. I guess simply adding cases for the previously mentioned types would do the trick?

```
@@ -321,12 +321,20 @@ func NewValue(v interface{}) (*Value, error) {
                return NewBoolValue(v), nil
        case int:
                return NewNumberValue(float64(v)), nil
+       case int8:
+               return NewNumberValue(float64(v)), nil
+       case int16:
+               return NewNumberValue(float64(v)), nil
        case int32:
                return NewNumberValue(float64(v)), nil
        case int64:
                return NewNumberValue(float64(v)), nil
        case uint:
                return NewNumberValue(float64(v)), nil
+       case uint8:
+               return NewNumberValue(float64(v)), nil
+       case uint16:
+               return NewNumberValue(float64(v)), nil
        case uint32:
                return NewNumberValue(float64(v)), nil
        case uint64:```

**Comment by puellanivis** [comment]
The document pretty clearly indicates that these types are not supported. I’m not saying this change isn’t a good idea, just that we would need to update the documentation as well.

**Comment by aculage** [comment]
It's not a bug then, but a little proposal. 
I was just quite surprised to encounter this, and it seems that nothing prevents us from introducing these four types, so if there is no particular reason to exclude them, I'd gladly make a contribution.

**Comment by zishang520** [comment]
Is there any progress? We also hope that `json.Number` of `encoding/json` can be supported.

**Comment by dsnet** [comment]
Note that this adds a new dependency on the "encoding/json" package. This is probably okay since `structpb` exists to interoperate with JSON.

If [the v2 "json" package](https://github.com/golang/go/discussions/63397) lands in stdlib, we may also want to support [`jsontext.Value`](https://pkg.go.dev/github.com/go-json-experiment/json/jsontext#Value) and [`jsontext.Token`](https://pkg.go.dev/github.com/go-json-experiment/json/jsontext#Token). Note that v2 drops support for the v1 `json.Number` since it's functionality is captured by the v2 `jsontext.Token`.

The v2 "json" migration will be taking a migration approach similar to the "github.com/golang/protobuf" to "google.golang.org/protobuf" in that the former will be implemented in terms of the latter. Thus, a persistent dependency on v1 "json" is okay since most of v1 will be implemented in terms of v2, anyways.
