### ISSUE TITLE
golang-protobuf allows to use the bytes type as string

### ISSUE THREAD

**Issue by xausky** [golang/protobuf#1467]
**Is your feature request related to a problem? Please describe.**
Now bytes is []byte in golang it does not support equal operation, it cannot be used as key in map.

**Describe the solution you'd like**
Optionally map bytes to string in golang

**Describe alternatives you've considered**
I tried to use string to replace bytes in proto file, but since protobuf's string is explicitly defined to use UTF8 text, it will generate an error when using non-UTF8 binary text.

**Additional context**
Envisaged solution:
First, in the proto file, you can enable `option go_bytes_as_string = true;`.
The corresponding field in the go file generated by protoc is of type string.
Therefore, it is the goal of bytes type to implement equal operator and as the key of map in golang.
There are the following comments in the golang code.
```
// string is the set of all strings of 8-bit bytes, conventionally but not
// necessarily representing UTF-8-encoded text. A string may be empty, but
// not nil. Values of string type are immutable.
type string string
```
Does this mean that it is perfectly possible to treat string as a ByteString-like implementation.

**Comment by puellanivis** [comment]
So, this proposal I think has come up before https://github.com/golang/protobuf/issues/922

Unfortunately, for a proto file wide option of `option go_bytes_as_string = true;` we would really want this buy in to happen at the master protobuf side, rather than Golang implementors unilaterally adding in a new potentially sometimes incompatible initiative.

While sort-of frustrating, you can always convert a `[]byte` into a string with an explicit cast in order to use it as a hash key. I don’t know just how feasible that would be though.

**Comment by stapelberg** [comment]
@puellanivis got it right — this would need to be addressed at the protobuf level, not at the protobuf go level: https://github.com/protocolbuffers/protobuf
