### ISSUE TITLE
structpb: NewValue input a big int64 number return value will loss accuracy

### ISSUE THREAD

**Issue by jiongjohn** [golang/protobuf#1479]
**What version of protobuf and what language are you using?**
protobuf: 1.28.0
go: 1.19

**What did you do?**
[This function](https://github.com/protocolbuffers/protobuf-go/blob/fc44d00d5a99973a6deb0863d6aaa7446c016066/types/known/structpb/struct.pb.go#L316) returns "err number with loss accuracy" when input a big int64 number

eg:
```golang
var num int64
num = 3364326223160287232

pbValue, err := structpb.NewValue(num)
if err == nil {
   fmt.Printf("num:%v, pbValue:%v", num, pbValue.AsInterface())
}
```

output
```
num:3364326223160287232, pbValue:3.364326223160287e+18
```

**Comment by puellanivis** [comment]
> The messages (i.e., Value, Struct, and ListValue) defined in struct.proto are used to represent arbitrary JSON.
— https://pkg.go.dev/google.golang.org/protobuf/types/known/structpb

Since JSON defines its Numbers as only requiring up to the precision of a double-precision floating point, the underlying protobuf itself was defined with [`double number_value = 2;`](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto#L68)

So, unfortunately, there is nothing we can do about this. The structpb-defining protobuf file explicitly only permits `float64` which only have 53 bits of precision.

I’m sorry, but I will also be closing this with “unactionable”. If you wish to address some way to encode `structpb` values without requiring that your `int64` values must be wrapped in strings, then you will need to raise [an issue with the upstream protobuf team itself](https://github.com/protocolbuffers/protobuf/issues), as this project is only for the Go implementation in specific.

**Comment by jiongjohn** [comment]
Thank you for your answer
