### ISSUE TITLE
unmarshall loses data for int64 value conversion when use proto struct.pb

### ISSUE THREAD

**Issue by apal60** [golang/protobuf#1501]
**What version of protobuf and what language are you using?**
Version: proto3 and Golang

**What did you do?**
Hello, I have declared a message like:
**import "google/protobuf/struct.proto"
message Template{
google.protobuf.Struct.parameters = 1;
}**

**my parameter consumes a json like:
{
"floatValue": 1234.5657,
"int64Value": 9223372036854775807
}**
- when parameters object unmarshall then it loses data for int64 value and by default wrap by the float64.
-
**What did you expect to see?**
9223372036854775807
**What did you see instead?**
9223372036854770000

**Comment by puellanivis** [comment]
This is an unavoidable consequence of how the WKT `Value` is defined. https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/well-known-types/value

It is also a well-known complication of JSON that the standard only requires a minimum bit-depth of 53 bits from the IEEE definition of double-precision floating point values. There is no way to guarantee that a proxy will not mangle a number value that has more bits of precision than that, which is why the [standardized proto3 JSON mapping](https://developers.google.com/protocol-buffers/docs/proto3#json) also requires 64-bit depth values to be stored as strings.

Any change to the behavior here would require coördination with the main protobuf community to redefine or rework how all languages treat these values. So, I will unfortunately close this issue as the code as is is performing to required standards.
