### ISSUE TITLE
encoding/protojson: ignore json field

### ISSUE THREAD

**Issue by vahid-sohrabloo** [golang/protobuf#1502]
By setting the JSON name to "-" in Golang, this field will be ignored. However, by setting ` [json_name="-"];` it won't be ignored in encoding/protojson

**Comment by puellanivis** [comment]
Because this protobuf library has to keep feature parity with the other languages supported by protobuf as well, this is an issue that must be brought to [the main protobuf project](https://github.com/protocolbuffers/protobuf).

I’m going to close this as “not planned”, if/when the main project approves this feature and other languages implement it as well, then we can reopen this issue to implement.
