### ISSUE TITLE
UseProtoNames=false doesn't seem to use "lowerCamelCase name in JSON field names."

### ISSUE THREAD

**Issue by horacimacias** [golang/protobuf#1507]
**What version of protobuf and what language are you using?**
protoc-gen-go v1.28.1
protoc        v3.21.9

**What did you do?**
I'm marshaling a protobuf message using `protojson`

The message `User` has an `EmployeeNumber` field:
```proto
// (optional) employee number
EmployeeNumber *string `protobuf:"bytes,2,opt,name=EmployeeNumber,proto3,oneof" json:"EmployeeNumber,omitempty"`
```

I'm using the following go code to create such a User and marshal it:
```go
        number := "number"
	user := User{
		EmployeeNumber: &number,
	}
	options := protojson.MarshalOptions{
		EmitUnpopulated: true,
		UseProtoNames:   false,
		UseEnumNumbers:  true,
	}
	json_bytes, err := options.Marshal(&user)
	println(string(json_bytes))
```

**What did you expect to see?**
Some json containing `"employeeNumber":"number"`. That is, using lowerCamelCase, given I opted for `UseProtoNames: false`
The description is (from https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#MarshalOptions):
```go
// UseProtoNames uses proto field name instead of lowerCamelCase name in JSON
// field names.
UseProtoNames [bool]
```

since I'm using `false` I expect lowerCamelCase.

**What did you see instead?**
Some json containing `"EmployeeNumber":"number"`. That is, not using lowerCamelCase because I used `false` for UseProtoNames and the description for that field (as I understand it) indicates `lowerCamelCase name in JSON field names` will be used.

**Comment by puellanivis** [comment]
Unfortunately, it seems you’ve hit upon an interesting corner-case condition. This apparent misbehavior results from not matching up with the style guide in the naming of fields. It is expected that field names will always be `snake_case`, and as such, there is no need to waste cycles lowercasing the first character, which should already always be lowercased. The algorithm then capitalize each letter after seeing and skiping an `'_'`.

So, in the case of `CamelCase` field names, this means that the entire field name ends up being returned as is. This behavior is also consistent with the C++ and Java implementation.

**Comment by horacimacias** [comment]
thanks for the quick and detailed response. 
Would it make sense to at least update the text around `UseProtoNames` to mention this?

**Comment by puellanivis** [comment]
Since this is behavior consistent across all protobuf implementations, it might be worth bringing up to the wider protobuf project. If you propose a Gerrit change, then this project would considered it as appropriate to the project.

Unfortunately, there are a lot of known issues that come up when not following the style guide. It’s a bit of a weird situation where protos written outside of the style guide are really only supported at best-effort level. It’s not treated like a standards violation, but it’s definitely not a supported path.

An important thing to remember is that protobuf is an inter-language standard, and the style guide is there to help code be more consistent with best practices in many different languages. Converting the `snake_case` to the local-language preferred `camelCase`, `CamelCase` or even keeping the `snake_case` is one part of that. And that’s why sometimes these sorts of “you’re not following the style guide” can end up outside of support.
