### ISSUE TITLE
types/known/structpb doesn't merge as expected in go

### ISSUE THREAD

**Issue by swist** [golang/protobuf#1517]
**What version of protobuf and what language are you using?**
Version: (proto v3, go proto `github.com/golang/protobuf v1.5.2`)

**What did you do?**
See attached test case:
```go
import (
    "testing"
    "google.golang.org/protobuf/types/known/structpb"
)

func TestNestedProtoMerge(t *testing.T) {
	// this shows why we can't do merge on strucpb.Struct
	v := map[string]interface{}{
		"foo": map[string]interface{}{
			"qux": "quux",
		},
	}
	dst, err := structpb.NewStruct(v)
	require.NoError(t, err)
	v2 := map[string]interface{}{
		"foo": map[string]interface{}{
			"bar": "baz-updated",
		},
		"qux": map[string]interface{}{
			"updated": "updated",
		},
		"bar": []interface{}{float64(2), float64(3)},
	}
	src, err := structpb.NewStruct(v2)
	require.NoError(t, err)

	proto.Merge(dst, src)

	exp := map[string]interface{}{
		"foo": map[string]interface{}{
			"bar": "baz-updated",
			"qux": "quux",
		},
		"qux": map[string]interface{}{
			"updated": "updated",
		},
		"bar": []interface{}{float64(2), float64(3)},
	}
	assert.NotEqual(t, exp, dst.AsMap())

	realResult := map[string]interface{}{
		"foo": map[string]interface{}{
			"bar": "baz-updated",
		},
		"qux": map[string]interface{}{
			"updated": "updated",
		},
		"bar": []interface{}{float64(2), float64(3)},
	}
	assert.Equal(t, realResult, dst.AsMap())
}
```

**What did you expect to see?**
Expected to see that nested `struct.Value` are also merged

**What did you see instead?**
The merge instead replaced the maps in the root `Struct.Fields` with the one from the target, ignoring the fact that some fields are mappings

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

**Comment by puellanivis** [comment]
It looks like maps are not being filled recursively. This should be the case for any map of maps, and nothing special about `structpb` itself, except that it is a very ready example of this.

The documentation is clear what it does here: `The entries of every map field in src is copied into the corresponding map field in dst, possibly replacing existing entries.` Does this behavior differ from the C++ or Java implementations?

**Comment by puellanivis** [comment]
Reviewing the documentation for C++ and Java, neither specifically state how they handle merging maps. Since maps are syntactic sugar on top of a `repeated KeyValuePairMessage` I imagine that they will handle maps the same as they treat `repeated` except with the condition that repeated keys will overwrite previous keys.

So far, the semantics of “Merge” has been that it is semantically equivalent to concatenating the protowrite format together and then unmarshalling that into a new struct. Under this semantics, the current behavior, while unfortunate, is consistent. However, we do also recursively merge singular messages, so… 🤷‍♀️ But if we take it as each singular message gets recursively concatenated together then unmarshalled, the current behavior is entirely consistent. (And again, repeated map keys then overwrite previous keys.)

Summary: this behavior is likely identical to how C++ and Java handle merges with maps of maps. This gives two paths forward:
1) If you or anyone can demonstrate that C++ and Java do not overwrite map values for existing keys, and instead recursively merge maps, then we will fix our implementation to match C++/Java implementation.
a) Raise an issue with the main protobuf project and… [you already have](https://github.com/protocolbuffers/protobuf/issues/11794). Good job! When the main project decides on defining a specific behavior for recursive map merging, then we will fix our implementation to meet the new standard.

I understand that you might find this answer disappointing. A workaround at this point may be to `AsMap` both, and then merge those maps recursively, then `NewStruct` the merged map.

**Comment by stapelberg** [comment]
> * When the main project decides on defining a specific behavior for recursive map merging, then we will fix our implementation to meet the new standard.

Feel free to file a new issue when/if this happens. Until then, I’ll close this issue as there’s nothing we can do immediately.
