### ISSUE TITLE
ProtoBuf Support For M1 chip

### ISSUE THREAD

**Issue by aksrazor** [golang/protobuf#1538]
proto generate throws and error
**"unsupported value for runtime.GOARCH: arm64
make: *** [proto-generate] Error 1"**
any fix for this

**Comment by puellanivis** [comment]
What does `go version` print?

**Comment by puellanivis** [comment]
Is your Makefile trying to run a binary named `prototool`? I ask, because this error does not appear in any protobuf code, and only apparently appears in `github.com/uber/prototool` and forks.

So far as I can tell, this has nothing to do with any code under support of any protobuf team, but is rather a bug in that specific project.
