### ISSUE TITLE
How to redefine the json tag?

### ISSUE THREAD

**Issue by fayfive** [golang/protobuf#1630]
```proto
message A {
  int64 now_time = 11; 
}
```
After I generated with `protoc`
```go
type A struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

        NowTime       int64  `protobuf:"varint,11,opt,name=now_time,json=nowTime,proto3" json:"now_time,omitempty"`
}
```
I want to redefine the second  JSON tag from `now_time` to `nowTime`.
Can protoc-gen-go do it? Thanks!

**Comment by puellanivis** [comment]
This question has come up quite often: https://github.com/golang/protobuf/issues?q=is%3Aissue+is%3Aclosed+json+tag

The decision every time has been: we do not intentionally support this feature. It was a misstep to ever support this. (Because when a proper canonical proto3 JSON mapping was eventually established, it disagreed with the ad hoc choices that had been made here.)

You should be using `protojson` to marshal protobuf messages to JSON anyways, which will default to `nowTime` rather than `now_time`.

**Comment by cybrcodr** [comment]
Also, if you want to change the default value for JSON serialization, you can use the `json_name` field option.  The `protojson` package recognizes that field option and will use it.
