### ISSUE TITLE
proto3 jsonpb differs from json field names since protoc-3.0.0-beta2

### ISSUE THREAD

**Issue by mwitkow** [golang/protobuf#183]
Recently `jsonpb` started respecting the [proto3 spec](https://developers.google.com/protocol-buffers/docs/proto3#json) for JSON names in conjunction with protoc `3.0.0 beta2` through (~Feb 2016):
- https://github.com/golang/protobuf/commit/d20896fc31fb0e955e57970d61eb6eea054ff048
- https://github.com/golang/protobuf/commit/001690d39bd620847bb265d93a7c5e1bd3737308

However, the normal `json` package still uses `OrigName` for field name. 

For example:

``` proto
syntax = "proto3";
package exampletest;

message SomeMessage {
  string snake_case = 1;
  string CamelCase = 2;
  string lowerCamelCase = 3;
  string Mixed_Stuff_With_Underscores = 4;  
}
```

produces 

``` go
type SomeMessage struct {
    SnakeCase                    string `protobuf:"bytes,1,opt,name=snake_case,json=snakeCase,proto3" json:"snake_case,omitempty"`
    CamelCase                    string `protobuf:"bytes,2,opt,name=CamelCase,json=camelCase,proto3" json:"CamelCase,omitempty"`
    LowerCamelCase               string `protobuf:"bytes,3,opt,name=lowerCamelCase,proto3" json:"lowerCamelCase,omitempty"`
    Mixed_Stuff_With_Underscores string `protobuf:"bytes,4,opt,name=Mixed_Stuff_With_Underscores,json=mixedStuffWithUnderscores,proto3" json:"Mixed_Stuff_With_Underscores,omitempty"`
}
```

This means that `jsonpb` will serialize `{"snakeCase": "foo"}` while `json` will serialize `{"snake_case": "foo"}`. 
`jsonpb` will accept what `json` serialized `{"snake_case": "foo"}` (thanks to `acceptedJSONFieldNames` method, @dsymonds props for that).
`json` will not read what `jsonpb` serialized.

I agree there is an argument to be made: always use the same deserializer that you used to serialize with... but there is no way for users to easily figure out whether this is `jsonpb` or `json` if it's stored somewhere, leading to massive confusion.  Especially since in our codebase, we use `.proto` as schemas for JSON files that we can't avoid, leading to even more confusion.

Also, this behaviour only exhibits when `protoc-3.0.0-beta-2` is used, not `beta-1`, leading to even more confusion.

Can we either:
- have a switch on `protoc-gen-go` that ensures `json` fields have the same name as `jsonpb` fields
- have a file-level `.proto` option similar to `go_package` controling the `json` field serialization?

@awalterschulze since GoGo proto has the same problem.

**Comment by dsymonds** [comment]
I don't think there's anything to do. You need to use jsonpb. The field names are only the first point of divergence. There's several other parts of the proto3 JSON spec that make it impossible to use the standard encoding/json package, like WKTs,

**Comment by mwitkow** [comment]
Can we add warnings about the change in behaviour or somehow document it?

How about generating Marshal and Unmarshal methods that use jsonpb under
the hood so that  calls from normal json are the same? ☺️

**Comment by dsymonds** [comment]
It wasn't really a "change" in behaviour, per se. The JSON spec was new with proto3; before that, the use of proto messages with encoding/json was best effort and only a rough approximation.

I don't want to have generated protos grow any extra dependencies, so depending on the jsonpb package isn't appropriate.

**Comment by awalterschulze** [comment]
If the generated code does not have the dependency, but simply all the code that is necessary the dependancy and two json libraries problems goes away.
This is an interesting idea.

**Comment by steckel** [comment]
Hi all — I see that this issue is still open and hasn't had much activity in some time. Is there a new status of the issue (or is it not relevant any longer)?

I found myself here as I was investigating why my attempt to replace a struct alongside JSON marshaling with a protobuf Message and jsonpb's marshaling wasn't working as I immediately assumed (this is the camelCase vs original snake case name).

I thought I saw that there was an option in the Marshaler for using the original name, but there didn't seem to be a mirrored feature for the Unmarshaler. Is adding that option something that would be considered with a pull request?

**Comment by dsnet** [comment]
As Dave mentioned earlier, the use of `json` tags was an approximation of what the JSON<->PB specification says. However, since the full spec is not implementable using the `json` package, this gives users the false impression that the two are interchangeable. I would like to see protos move towards a world where the `json` tags are not generated.

Secondly, the use of `json` tags presumes that generated messages are always structs are fields, which may or may not be always true.

As an alternatively to provide some bit of interplay with the standard library's `json` package, #256 is still on the table.
