### ISSUE TITLE
Expose registered message types on generated code

### ISSUE THREAD

**Issue by thinxer** [golang/protobuf#194]
Currently generated code registers with `proto.RegisterType` and we can retrieve the type based on a string name.  However, it is not possible to list all registered types.  The types map is there but not exposed.

I'd suggest

1. Add `ListTypes()` and `ListEnums()`  to `golang/protobuf/proto` to get all the type names.
2. Or add the above methods to the generated package to list local types.

**Comment by zombiezen** [comment]
This is something I'm looking at, but it would help to know what you're using the listing for.

**Comment by thinxer** [comment]
I'm writing a data management service, and the data schemas are defined in proto files.  Our service accepts data in JSON format and stores them in Protobuf.  We want to expose what formats we accept (and possibly their definitions) via an API.  That's why we need to list types of one generated protobuf package.

I'm currently using a custom protoc plugin for this.  The plugin will list all types being compiled into a .go file.  It could be better if the official protoc-gen-go can generate this.

**Comment by zombiezen** [comment]
It seems like your application should use an explicit registry, where you mark each proto that you accept.  You can use the generated `Descriptor()` method to grab the `FileDescriptorProto`. This is the approach taken by gRPC, for instance.

**Comment by thinxer** [comment]
The grpc example uses `pb.RegisterXXXServer` which is generated by the `grpc` plugin built into `protoc-gen-go`. I cannot embed my plugin into `protoc-gen-go`. I have to write my custom generator, which is somewhat hard to implement.

However, if the registered types could be exposed (which IMHO is very simple to implement), I don't have to write the custom generator anymore. This might be helpful to other users as well.


On the `FileDescriptorProto` part, yes I can get one `FileDescriptorProto` for one message. However my package is generated by several proto files (and this list is changing). This isn't an API to list all registered `FileDescriptorProto` neither.

**Comment by zombiezen** [comment]
You don't need to hook into `protoc-gen-go`.  gRPC uses this to add extra metadata, but if you just need a list of filenames, you can set up a registry yourself.  Slightly tweaking the code from gRPC:

```go
var filenames map[string]bool

func register(msg proto.Message) {
  d := msg.(interface {
    Descriptor() ([]byte, []int)
  })
  desc, _ := d.Descriptor()
  fd := new(descriptor.FileDescriptorProto)
  if err := proto.Unmarshal(decompress(desc), fd); err != nil {
    panic(err)
  }
  filenames[fd.GetName()] = true
}

func init() {
  register((*mypb.Message)(nil))
}

// later in app...
for _, fname := range filenames {
  fdBytes := proto.FileDescriptor(fname)
  // ...
}
```

I realize that exposing the map is not a difficult change, but it does lock the package's implementation into always using a map as the data structure.  The file descriptor map is lists all of the file descriptors present at link-time.  The reason we generally don't export this is because that list can change depending on what protos your dependencies bring in, which can cause action-at-a-distance.  The benefit of the more explicit registry I propose in that code snippet is that it ensures that all of the types and files that you expect are linked in, because you have a reference in code, and doesn't bring in additional types.

**Comment by thinxer** [comment]
Thanks for the detailed response.  However, my use case is that I don't want to reference all the types in my code. The protobufs I'm using are for user data, not the program itself. The definitions of the user protobufs are also changing rapidly. I'm willing to recompile the program every day (which can be done automatically) but do not want to touch the code that frequently.

Please feel free to close this issue if exposing registered types is not a good idea for general users.

**Comment by zombiezen** [comment]
Yes, this seems more dynamic that what we're aiming to support for general users.

**Comment by vimalk78** [comment]
@thinxer , if possible can you share the protoc plugin you use? i am also looking for something similar as you have asked for in this issue.
i want to be able to lookup the input and output types of an API by name.
since this info is not readily available in the generated pb.go code, i thought of using a protoc plugin to generate this information.
thanks in advance,

**Comment by festum** [comment]
@thinxer Could you share how you retrieve the type based on a string name?
