### ISSUE TITLE
Vendorizing and Releases

### ISSUE THREAD

**Issue by yanfali** [golang/protobuf#195]
Is there a plan to support vendor/ to have consistent build releases? One issue we're struggling with locally is figuring out what version of the go plugin is running. Each developer pulls from tip, because no releases and then potentially gets incompatible go code generated.

Should we just vendorize the proto-gen-c directory? Should I just checkout a specific SHA for golang/protobuf and ensure that every developer is running the same SHA before trying to build proto-gen-c?

Some guidance on how to use this tooling at scale beyond 1 would be appreciated. Most companies are not google and no have monorepos with all their code in a single repository.

**Comment by zombiezen** [comment]
As background, we did recently bump the version number of the generated code to fix a deep, common race condition around extensions we were seeing in many packages.  This is the first time we did this, so apologies for the rough edges.

The runtime library expects that your protoc-gen-go binary and generated code are built at the same commit as the runtime library.  We may need to document this assumption better, but we do not intend to bump the version often.  Since protobuf is a library, it would be inappropriate for us to add a vendor/ directory, since binaries are the ones that should "pin" the versions of the libraries they need.

**Comment by yanfali** [comment]
Thanks @zombiezen this helps my understanding. So in order to ensure devs have the correct version I effectively have to do something like this then:
```
rm -fr $GOPATH/src/github.com/golang/protobuf
go get github.com/golang/protobuf
cd $GOPATH/src/github.com/golang/protobuf/protoc-gen-go
git checkout 0c1f6d65b5a189c2250d10e71a5506f06f9fa0a0
go install
```

**Comment by zombiezen** [comment]
Or you can copy 0c1f6d65b into your project using the [vendor/](https://blog.gopheracademy.com/advent-2015/vendor-folder/) directory.  There's a variety of tools to help you do this, such as Godeps or govendor.  Then your devs won't have to do the checkout manually, although they may have to ensure their installed protoc-gen-go is the one in the vendor/ directory.

Hope that helps!

**Comment by yanfali** [comment]
Thanks @zombiezen. I am using govendor, this script is basically to ensure that people updating the proto files have the correct tooling.
