### ISSUE TITLE
Proto3 repeated field not packed by default

### ISSUE THREAD

**Issue by cygery** [golang/protobuf#197]
### Message definitions 

`proto3_test.proto`:
```
syntax = "proto3";

package test;

message Test3Int32RepDefault {
    repeated int32 repeated_int32 = 1;
}

message Test3Int32RepPackedTrue {
    repeated int32 repeated_int32 = 1 [packed = true];
}
```
Compiled via:
```
$ protoc --version
libprotoc 3.0.0
$ protoc --go_out=. *.proto
```

### Result

`proto3_test.pb.go`:
```
// ...
type Test3Int32RepDefault struct {
	RepeatedInt32 []int32 `protobuf:"varint,1,rep,name=repeated_int32,json=repeatedInt32" json:"repeated_int32,omitempty"`
}
// ...
type Test3Int32RepPackedTrue struct {
	RepeatedInt32 []int32 `protobuf:"varint,1,rep,packed,name=repeated_int32,json=repeatedInt32" json:"repeated_int32,omitempty"`
}
// ...
```

The repeated field with default `packed` setting compiles to a non-packed field although it should be [packed by default](https://developers.google.com/protocol-buffers/docs/encoding#packed).

**Comment by rikuayanokozy** [comment]
The bugs seems points to  https://github.com/golang/protobuf/blob/545732fb9671625a62a399186a066c4f8b942bc5/protoc-gen-go/generator/generator.go#L1554

As Proto3 specified, repeated fields of scalar numeric types use packed encoding by default. We should add some check here.

** This is an urgent bug because the official Protobuf Javascript implementation doesn't read tag to detect binary is packed or not. **

Both declared proto3 syntax.
repeated int64:
![image](https://cloud.githubusercontent.com/assets/10336620/16981736/807623b6-4e9e-11e6-9bb0-3959e4b9d4f8.png)

repeated int64 [packed=false]:
![image](https://cloud.githubusercontent.com/assets/10336620/16981714/6184fd60-4e9e-11e6-8789-94f7048b5941.png)

**Comment by cygery** [comment]
Thanks for your comment. Yeah, I've also submitted [an issue regarding the JavaScript parser](https://github.com/google/protobuf/issues/1701) which was labelled as a bug.
For now I'm explicitly defining the packed option as a workaround but I hope both issues will be fixed eventually.

**Comment by rikuayanokozy** [comment]
I made a pr https://github.com/golang/protobuf/pull/203 to fix this problem. @cygery give it a try.
