### ISSUE TITLE
XXX_InternalExtensions makes code generation quite hard

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#204]
Its not impossible for gogoprotobuf
https://github.com/gogo/protobuf/commit/6abcf94fd4c97dcb423fdafd42fe9f96ca7e421b
, but there are users that would like to have code generation, but still import golang/protobuf.
gogoprotobuf allows this using the gofast_out protoc option.

Having the extensions private makes it hard to do some things without more library functions:
 - marshal: EncodeInternalExtension
 - calculate marshaled size: SizeOfInternalExtension
 - string: StringFromInternalExtension
 - ...
 - or even generate a GoString method that will be able to reproduce that instance of the structure: NewUnsafeXXX_InternalExtensions

**Comment by zombiezen** [comment]
cc @matloob 

I don't think that we particularly want to export any more implementation details than we already do.  This new approach to extensions has eliminated an entire class of subtle race conditions, so I'm not inclined to roll it back.  Is there a deficiency in `proto`'s public API that prohibits you from iterating over the extensions?

**Comment by awalterschulze** [comment]
I don't think you need to roll back, but I would like the proto package to contain some extra functions.

**Comment by zombiezen** [comment]
Acknowledged.  I don't understand what these functions would do that can't be done with walking over the extensions using `proto.ExtensionDescs` and `proto.GetExtensions`.

**Comment by awalterschulze** [comment]
Lets say for instance generated code that unmarshals the extensions as fast as possible.

**Comment by zombiezen** [comment]
This seems like premature optimization: you would only need to generate code to walk over extensions if the message declares that it has an extension range (which is not the majority of messages).  Besides, what these internal methods would do is very close to what the approach I just described would do, since the vast majority of the time would be occupied by the mutex acquisition.  I don't see a need for the `proto` package to export more functions that tie us to a particular implementation.

If you're worried about the code bloat, seems like gogoprotobuf should provide these common functions and then call into them from its generated code.

**Comment by awalterschulze** [comment]
My majority of messages is different from your majority of messages.

While unmarshaling the mutex is unnecessary and should not be part of the execution path.

I am not too worried about code bloat, but gogoprotobuf has common functions, like AppendExtension, that is used during Unmarshaling.
https://github.com/gogo/protobuf/commit/6abcf94fd4c97dcb423fdafd42fe9f96ca7e421b#diff-a53e6beefff5a04e637d07e9223b569fR205
The problem is how would I go about unmarshaling using the golang/protobuf library and my generated code, since some users might decide to do this.

My only other option is to say gofast_out and extensions are not supported and to reference this issue.

**Comment by awalterschulze** [comment]
Or maybe I have missed another way that I can still achieve this?

**Comment by zombiezen** [comment]
I don't know enough about gogoprotobuf to be able to comment on what is the optimal solution here.  I've gleaned enough from glancing at the code to realize you use extensions even for messages that don't have them, so I can see how this has more of an impact for gogoprotobuf.  In the short-term, you should be able to generate code that was compatible with the old extension mechanism and have it work: we do type-assert to use the older interface.

As for performance of the new-style functions: you are correct that unmarshaling does not acquire the mutex.  It would be best to minimize the number of calls to `ExtensionDescs` and `GetExtensions` during marshaling, because that will acquire a mutex.

**Comment by awalterschulze** [comment]
I don't see how use extension unmarshaling for messages that don't have extensions.  I wasn't talking about the extensions used in gogoprotobuf, but the extensions used by the users of gogoprotobuf, like the company where I currently work.  We used extensions in our core messages, that need to serialized and deserialized a lot.  So much that I had to write and maintain gogoprotobuf, because it is a huge bottleneck.  I am worried about other users of gogoprotobuf that still want to import golang/protobuf.

I can't generate the old extension mechanism, because I wan't people that don't activate any gogoprotobuf extensions (gogoproto.proto) to have almost exactly the same code as golang/protobuf.  Also this causes a digression which is not ideal.  If this is your short term solution, what is the long term solution?

I am not clued in on how I would unmarshal without running into mutex code?  I think I might have missed how to do that?

**Comment by zombiezen** [comment]
For mutexes: if you examine the source, `extensionsWrite`does not acquire the mutex, which is what is used when setting extensions.

I don't really have any advice for a solution because I do not understand what is broken here.  We made a change to our code generation that has had no significant change in our marshal/unmarshal benchmarks.  It seems like there's a hypothetical concern here that this may cause applications using gogoprotobuf to be slower: I'd like to see exactly what is becoming slower, because then this would be a good data point to see if our API is deficient in general.  Exporting new functions mean that we will need to maintain them indefinitely, so the barrier-to-entry for that kind of change is higher.

That being said, we are aware that golang/protobuf is not where it should be on performance.  We are actively investigating how to make it better, so stay tuned.

**Comment by awalterschulze** [comment]
I think I should stop talking in hypotheticals and give some concrete code examples.  I'll work on that as soon as I get some time.

**Comment by awalterschulze** [comment]
Yes seems I won't have time for this for a long time and I think you might have a point.
Thanks again for your efforts and time.
