### ISSUE TITLE
Numeric types shouldn't be wrapped with `"`

### ISSUE THREAD

**Issue by janisz** [golang/protobuf#211]
Why numeric values like `int` are wrapped with `"` and passed in JSON as a String?

Test case for this situation: [jsonpb_test.go#L398](https://github.com/golang/protobuf/blob/af59feb4214c835e81558f78e88b58bf034a7319/jsonpb/jsonpb_test.go#L398)

**Comment by dsnet** [comment]
I haven't looked into it, but my conjecture is because we want to maintain (as much as possible) the ability to do a roundtrip JSON encode/decode.

In JSON, the numeric type is actually not an integer, but a float64 and is limited to 2^53 bits. By encoding as a string, it ensure that we can encode extremely large integers without loss of precision.

**Comment by zombiezen** [comment]
This is part of the proto3 spec for 64-bit ints for exactly the reason Joe
describes. https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by janisz** [comment]
I try to use golang protobuf to create Mesos framework and I go my requests rejected by server because of
> Failed to convert JSON into Call protobuf: Not expecting a JSON string for field 'value'
But in this case it looks like it's error on their side since proto2 spec does not specify JSON mappings.

Thanks for quick answer.
