### ISSUE TITLE
why all generated file is pointer field

### ISSUE THREAD

**Issue by guileen** [golang/protobuf#22]
I have proto file

```proto
message MsgErrCode {
    required int32 err_code = 1;
    optional string reason = 2;
}
```

After generated, I got go file

```go
type MsgErrCode struct {
     ErrCode *int32 `....`
     Reason *string  `....`
}
```

Notice that the field generated is pointer, It make me hard to use the struct,

I can't do ``` &MsgErrCode{ErrCode: int32(12), Reason: "hello world"}```

I have to do ``` &MsgErrCode{ErrCode: proto.Int32(12), Reason: proto.String("hello world")}```

**Comment by dsymonds** [comment]
That's how the proto2 API works. Read the package docs. proto3 might suit you better if you don't want pointers.

**Comment by guileen** [comment]
You mean my generator is used proto2? or my proto file write in proto2 format?

I installed the latest potobuf-gen-go via "go get -u github.com/golang/protobuf/protoc-gen-go" 

And I  run command

```
proto --go_out=../proto-gen msg.proto
```

**Comment by dsymonds** [comment]
Yes, that's how it works. It is proto2 by default.

**Comment by yaodongen** [comment]
Because `proto2` has configs like `required` and `optional` while `proto3 field` are alway optional. In some cases in `proto2`, you need to know whether the optional field has been set to zero value manually or it's just an auto default value. With pointer, we can use `nil` to find out.

Sample Code:
```
m := &MsgErrCode{}
if m.Reason == nil {
     // the field not been set
} else if *m.Reason == "" {
    // the field has been set to "" manually
}
```
While the function `func (m *MsgErrCode) GetReason() string` in `*.pb.go` files will always return `""`.

More Info: [protobuf/proto](https://godoc.org/github.com/golang/protobuf/proto)
