### ISSUE TITLE
json_name field option not working

### ISSUE THREAD

**Issue by junghoahnsc** [golang/protobuf#248]
Hello,

I'm using 'json_name' field option, but it doesn't work.

My proto is

```
message GeoCoordinate {
  double latitude = 1 [ json_name = "lat" ];
  double longitude = 2 [ json_name = "long" ];
}
```
But in Go,
```
a := GeoCoordinate{}
a.Latitude = 1.2

b, _ := json.Marshal(a)
fmt.Printf("a=%s\n", string(b))
```

The output was
```
a={"latitude":1.2}
```
Thanks,

**Comment by dsymonds** [comment]
You need to use the `jsonpb` package instead of the `encoding/json` package from the standard library.

**Comment by junghoahnsc** [comment]
Oh, I see. It works.
It might be better to mention on this in https://developers.google.com/protocol-buffers/docs/proto3#json?

**Comment by bcmills** [comment]
Arguably the best fix would be to remove the distinction between `jsonpb` and `json` encoding (per #256).  Then there would be nothing unusual to document.

**Comment by cybrcodr** [comment]
Closing this issue as it is resolvable via jsonpb.  Discussion for using plain json encoding is at #256.

**Comment by kushubham** [comment]
Hi since (-) doesn't work with protobuf and if you really wanted to use it for some reason,
then a quick hack for this to add (json_names_for_fields=true) while compiling your code.
for e.g i used as --swagger_out=json_names_for_fields=true:path_to_your_dir, and in my case it worked without importing jsonpb package and extra effort.
