### ISSUE TITLE
How to get Message Descriptor proto?

### ISSUE THREAD

**Issue by junghoahnsc** [golang/protobuf#252]
Hello,

I'm trying to use MessageOptions in my proto like
```
extend google.protobuf.MessageOptions {
  MyOption my_option = 10000;
}
message MyOption { string name = 1; }

message MyMessage {
  option (my_option).name = 'snaps';
  ...
}
```

To access this option, I think I have to do something like

```
MyMessage.GetDescriptor().GetExtension(MyOption)
```

I know `proto` has `GetExtension()`, but I couldn't find how to get the descriptor.
I can see each generated message type has `Descriptor() ([]byte, []int)`, but I'm not sure whether this is the descriptor that I want and how to interpret the return values.

Thanks,

**Comment by bcmills** [comment]
See [this comment](https://github.com/golang/protobuf/issues/179#issuecomment-260789259).

We don't currently have a public API for this.  I don't think it could be provided via the `proto` package itself because the generated [`protobuf`](https://godoc.org/google.golang.org/genproto/protobuf) package depends on `proto`, but perhaps a subpackage would work.

**Comment by bcmills** [comment]
I have a fix pending for #179 that will address this.

**Comment by bcmills** [comment]
You can now use the [`descriptor`](https://godoc.org/github.com/golang/protobuf/descriptor) package for this.

**Comment by junghoahnsc** [comment]
cool! It works!
