### ISSUE TITLE
protoc-gen-go: add canonical import comment to generated files

### ISSUE THREAD

**Issue by pongad** [golang/protobuf#267]
This request originated from a discussion with @zombiezen about https://github.com/google/go-genproto/pull/17 .

If the proto file specifies `go_package` option with a fully qualified path, it should be possible to generate Go source files with the correct canonical import comments.

**Comment by vargup** [comment]
My generated file has a comment 
package foo // import "foo/api/foo"

When I try to import this package then I get an error.
code in directory "<$GOPATH/src repo>/.gen/foo/api/foo expects import "foo/api/foo"

**Comment by dsnet** [comment]
Another relevant questions: how are you invoking `protoc` and `protoc-gen-go` to generate the `pb.go` files?

**Comment by vargup** [comment]
I am using protoc to generate pb.go

**Comment by dsnet** [comment]
I meant, how you are invoking it? Does the proto file have a `go_package` option specified?

**Comment by vargup** [comment]
@cybrcodr we use go build

**Comment by dsnet** [comment]
With upcoming module support, we should remove generating this magic comment. See #678

**Comment by nilslice** [comment]
I, too, am having a difficult time with the addition of the import comment. Although, my use case may be within a more narrow set of needs... my output .pb.go files are used for both server and client packages, originating for the server package (whose path is designated by the `go_package` option) and then `cp`'d into a client package. 

This worked fine until upgrading from `925541529c1fa6821df4e44ce2723319eb2be768` (v.1.0.0) to `05f48f4eaf0e05663b562bab533cdd472238ce29`.. I have not done my homework to see where exactly this change was introduced. I've seen the discussion in #678 around removing the comment altogether, which I fully support 😄, and figured I'd throw my report here as well. 

Otherwise, I am faced with the decision to involve `sed` in my generate step, or revert to the older version of the plugin. If there is another recommendation yet to be published, or if I can help test a suggestion let me know. Thanks!

**Comment by puellanivis** [comment]
I’m curious as to why one would `cp` the files into a client package rather than just `import` them directly?

**Comment by nilslice** [comment]
@puellanivis - initially it was by design to fit the preferred the package layout provided to consumers. Later, there was code written around the generated types (additional methods with a generated type as a reciever, etc) that we wanted to keep associated exclusively with the types in the server package.
