### ISSUE TITLE
why int64 need ""

### ISSUE THREAD

**Issue by skadilover** [golang/protobuf#271]
needToQuote := string(b[0]) != `"` && (v.Kind() == reflect.Int64 || v.Kind() == reflect.Uint64)
	if needToQuote {
		out.write(`"`)
	}
	out.write(string(b))
	if needToQuote {
		out.write(`"`)
	}
	return out.err
why add quote here ??

**Comment by dsnet** [comment]
Hi. This is for two reasons:
* This is what the proto3 specification says int64 should be serialized as. ([Specification](https://developers.google.com/protocol-buffers/docs/proto3#json))
* On a more technical level, JSON specifies numbers as float64 values. This is problematic when serializing int64 since it is not possible to losslessly transform between an int64 and a float64. A float64 can only losslessly hold 53-bits of the integer.

See #211
