### ISSUE TITLE
How can I generate map[string]interface{} data type ?

### ISSUE THREAD

**Issue by wednesdaysunny** [golang/protobuf#272]
Now I want generate data type like map[string]interface{}, How can I do it?

Please help me.

**Comment by wednesdaysunny** [comment]
Hello anyone can help me ?

**Comment by bcmills** [comment]
I don't think that's possible with protocol buffers, since there is no type corresponding to `interface{}`.

Using proto3, the closest you can probably get is [`map`](https://developers.google.com/protocol-buffers/docs/proto3#maps)`<string, `[`Any`](https://developers.google.com/protocol-buffers/docs/proto3#any)`>`.

**Comment by c9s** [comment]
Kubernetes has one package doing this, a dynamic field for int or string k8s.io/apimachinery/pkg/util/intstr/intstr.go
