### ISSUE TITLE
protoc-gen-go is slower

### ISSUE THREAD

**Issue by kunalsomani** [golang/protobuf#321]
I have used protoc-gen-go to generate the code which slower than protoc-gen-gofast. I did benchmarking(marshal and unmarshal) on both and found protoc-gen-go is much slower than other. 

Can you please explain the difference?

**Comment by LMMilewski** [comment]
Are your referring to gogo/protobuf/protoc-gen-gofast (that's what I found by doing a Google search for "protoc-gen-gofast")? I'm not familiar with the details of this library. I suggest that you ask authors about the difference.

We are currently testing improvements to golang/protobuf that make it faster. Those changes will be on github in a few weeks.

**Comment by awalterschulze** [comment]
May I ask how you decide to improve the speed of golang/protobuf?

gogoprotobuf is currently faster then golang/protobuf because it does less memory allocations and uses code generation, which results in more inlining, calculations that can be done at generation time and less use of reflect.  I really don't see golang/protobuf catching this speed unless they finally decide to embrace some type of code generation.  I really hope these new speed improvements include a lot of code generation.

**Comment by LMMilewski** [comment]
We looked at various approaches. Most of the speedup comes from compact table representations, reducing allocations / data movement, caching of various structures, and inlining where it matters.

We also prototyped codegen to measure performance improvement and binary size increase. Results of that experiment don't support making codegen a default setting now, but this is an area to explore further.

**Comment by awalterschulze** [comment]
I am surprised.  I guess we'll have to run a benchmark.

**Comment by kunalsomani** [comment]
I ran lot of benchmarking with around 12 attributes struct type, which is much slower than binary protocol and gogo protobuf too. That makes me hard to use golang protobuf generator.

**Comment by LMMilewski** [comment]
> I am surprised. I guess we'll have to run a benchmark.
To clarify, codegen makes code faster. It also makes binaries large enough that it's not a clear win.

> I guess we'll have to run a benchmark.
Would you have any good benchmarks that you could share? We're especially interested in benchmarks modelling real environments.
One problem that we have is that using a tight loop around a simple proto operation is an easy to improve benchmark, but doesn't translate to improvements in context of running actual servers using protos.
If you have good benchmarks (if we improve the benchmark then real programs are actually improved) that we could use, then please share.

**Comment by awalterschulze** [comment]
Here are two real world anonymized proto messages.
It should be pretty simple to remove the gogoproto parts, since they are very little in the representation.

https://github.com/katydid/testsuite/blob/master/relapse/gen-relapse-tests/puddingmilkshake.proto
https://github.com/katydid/testsuite/blob/master/relapse/gen-relapse-tests/typewriterprison.proto

Here is an impartial golang serialization benchmark
https://github.com/alecthomas/go_serialization_benchmarks

**Comment by awalterschulze** [comment]
Since there is a trade off this is something that the protobuf user might want to decide.
Protobuf already has the concept of OptimizeMode, with which the user can specify which it prefers.

```
enum OptimizeMode {
    SPEED = 1;        // Generate complete code for parsing, serialization,
                      // etc.
    CODE_SIZE = 2;    // Use ReflectionOps to implement these methods.
    LITE_RUNTIME = 3; // Generate code using MessageLite and the lite runtime.
  }
``` 
- https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.descriptor.pb

**Comment by LMMilewski** [comment]
Thank you for sharing.
