### ISSUE TITLE
Import two .proto files in same package coz protoc generate two different import in go code

### ISSUE THREAD

**Issue by lnshi** [golang/protobuf#322]
In protobuf I have something like this:
```
import "lib/enums.proto";
import "lib/mobile_phone.proto";
```

Apparently it is same package, when generate the Go code, it should be:
```
import lib "lib"
```

But what the `protoc` output is:
```
import lib "lib"
import lib1 "lib"
```

It works, but just cannot understand why does the `protoc` need such kind of logic? Can someone help to explain?

**Comment by imjoey** [comment]
+1, I have the same issue.

**Comment by puellanivis** [comment]
So, golang itself will only allow one package in a directory. As protoc is building these protos in the "lib/" directory, it is placing both of the protos there as one single library.

Then, when you import both of the protos separately, protoc-gen-go is just naïvely treating them as if they were actually separate libraries, even if they aren’t.

As this is generated code, one can anticipate a number of redundancies in the code, because it is easier to just generate the simple naïve code, rather than complicate logic that could potentially do the wrong thing, just to produce “prettier” code, which was never _really_ supposed to be handled manually anyways.

**Comment by neild** [comment]
Nope, we now import each package only once.
