### ISSUE TITLE
[jsonpb] Do not marshal empty slices, maps and objects

### ISSUE THREAD

**Issue by fische** [golang/protobuf#323]
Hi,

The `Marshaler` from `jsonpb` does not marshal empty slices, maps and objects even with the `EmitDefaults` option.

For example, with following protobuf message:
```protobuf
message Message {
	message SubMessage {
		string str = 1;
	}
	repeated string arr = 1;
	map<string, string> m = 2;
	SubMessage sub = 3;
}
```

... and the following go code:
```go
func main() {
	var (
		msg       pb.Message
		marshaler = jsonpb.Marshaler{
			OrigName:     true,
			EmitDefaults: true,
		}
	)
	if s, err := marshaler.MarshalToString(&msg); err != nil {
		log.Fatalf("Could not marshal proto message : %v", err)
	} else {
		fmt.Println(s)
	}
}
```

I get:
```json
{}
```

Is that done by design? Or can/will it be fixed?

**Comment by SamiHiltunen** [comment]
I'm also running into the same issue. Would it be possible to have a fix for this merged? There are multiple pull requests (#338, #232, #287, #327) for this and also some issues filed along with this one. Only difference I see with most of the related PRs whether they output both nil and empty slices as ```null```,  ```[]``` or empty slices as ```[]``` and nil slices as ```null``` The proto3 JSON spec seems to accept both ways of handling as a valid solution although I would go for representing omitted/empty maps and slices always as ```[]``` and ```{}```. Maybe it would make sense to have a configuration option for always forcing the empty/omitted values to be outputted as empty values rather than nulls?

**Comment by AkihiroSuda** [comment]
PING @dsnet @nelid @dsymonds

**Comment by AkihiroSuda** [comment]
ping ping...

**Comment by dsnet** [comment]
\cc @cybrcodr
