### ISSUE TITLE
Oneof does not work when field name matches field type

### ISSUE THREAD

**Issue by peterciccolosc** [golang/protobuf#352]
The following proto:
```
message Foo {
  message Bar {}

  oneof myoneof {
    Bar bar = 1;
  }
}
```
And the following go code:
```
func getOneof(fooproto *protopackage.Foo) int {
        switch fooproto.Myoneof.(type) {
        case *protopackage.Foo_Bar:
                return 1
        }
        return 0
}
```

Gives this compile error:
`impossible type switch case: fooproto.Myoneof (type "foo_go".isFoo_Myoneof) cannot have dynamic type *"foo_go".Foo_Bar (missing "foo_go".isFoo_Myoneof method)`

But the problem disappears if the name of the field in the oneof is changed to `bar_field`.

**Comment by dsnet** [comment]
What version of protoc and protoc-gen-go are you using? I cannot reproduce this on:
* `protoc` v3.0.0
* `protoc-gen-go` `fec3b39b059c0f88fa6b20f5ed012b1aa203a8b4`

**Comment by junghoahnsc** [comment]
We're using bazel (https://github.com/pubref/rules_protobuf)

`protoc`: `52ab3b07ac9a6889ed0ac9bf21afd8dab8ef0014` (# Oct 4, 2016)
`protoc-gen-go`: `69b215d01a5606c843240eab4937eab3acee6530`

**Comment by dsnet** [comment]
This is an unfortunate case of naming conflicts. By convention, the protoc-gen-go produces sub-messages as "Parent_Child". Thus, the sub-message Bar is named "Foo_Bar". However, protoc-gen-go uses the exact same convention for naming oneof fields. So, the oneof "bar" field is also named "Foo_Bar". Since there are two types trying to be named "Foo_Bar", protoc-gen-go uses "Foo_Bar_" for the oneof field to avoid a conflict.

You can use the alternative name:
```go
func getOneof(fooproto *protopackage.Foo) int {
        switch fooproto.Myoneof.(type) {
        case *protopackage.Foo_Bar_: // Foo_Bar_ instead of Foo_Bar
                return 1
        }
        return 0
}
```

Fixing this to address this edge case is unlikely to happen as it would break all existing usages of oneof fields.
