### ISSUE TITLE
Strange behavior when unmarshal bytes.

### ISSUE THREAD

**Issue by disksing** [golang/protobuf#376]
The [doc](https://developers.google.com/protocol-buffers/docs/proto3#default) says:
> When a message is parsed, if the encoded message does not contain a particular singular element, the corresponding field in the parsed object is set to the default value for that field. 

and

> For bytes, the default value is empty bytes.

So I guess the following example should get empty bytes instead of nil.

```
package main

import (
	"fmt"

	"github.com/golang/protobuf/proto"
)

type M struct {
	B []byte `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
}

func (m *M) Reset()         { *m = M{} }
func (m *M) String() string { return proto.CompactTextString(m) }
func (*M) ProtoMessage()    {}

func main() {
	var m M
	err := proto.Unmarshal([]byte{}, &m)
	fmt.Println("err: ", err)
	fmt.Println("m.B==nil: ", m.B == nil) // Should it be '[]byte{}'?
}
```

**Comment by dsnet** [comment]
Thanks for the issue. This is actually working as intended. This is a case where the default values that the proto3 spec chose corresponds to several reasonable values in Go.

In Go, an empty `bytes` can either be `nil` or `[]byte{}`. Both are empty by definition since `len([]byte(nil)) == len([]byte{}) == 0`.

The original proto3 implementation in Go happened to choose nil, and so we will sticking with that for backwards compatibility reasons. It is also a convenient default value since the zero value of a proto3 struct *is* the default proto3 message.

The original proto3 implementation in Go happened to choose nil, and so we will sticking with that for backwards compatibility reasons. It is also a convenient default value since the zero value of a proto3 struct *is* the default proto3 message.
