### ISSUE TITLE
Error: foo/hoge.proto: "XXX" is already defined in file hoge.proto

### ISSUE THREAD

**Issue by NoahOrberg** [golang/protobuf#445]
Hi, I wrote some proto and golang files and compile.

that repository is [here](https://github.com/NoahOrberg/project)

please, clone this repository, and run `$ sh protoc.sh`, errors occur.

```
github.com/NoahOrberg/project/protobuf/other/a.proto:5:11: "other.A.a" is already defined in file "a.proto". 
github.com/NoahOrberg/project/protobuf/other/a.proto:4:9: "other.A" is already defined in file "a.proto".  
hoge.proto: Import "github.com/NoahOrberg/project/protobuf/other/a.proto" was not found or had errors.   
hoge.proto:7:5: "other.A" seems to be defined in "a.proto", which is not imported by "hoge.proto".  To use it here, please add the necessary import.                    
api.proto: Import "hoge.proto" was not found or had errors.                              
api.proto:9:5: "Hoge" is not defined.
```

maybe,  In protobuf/other/b.proto, import path is `a.proto`.
On the other hand, In protobuf/hoge.proto, import path is `github.com/protobuf/other/a.proto`.

Therefore, even the same file is recognized as a different file due to a different path.

Ideally, I want to compile well in each package without changing the file structure.

How can I solve it?

**Comment by savaki** [comment]
We're seeing the same issue.  

We have an app with numerous protobuf packages and we're starting to see duplicate proto type registered errors because gogo only uses a partial package name to identify the type. Instead, protobuf should use the entire package name to fully qualify the type.

Consider examples within the go pkgs that would cause this issue:

html/template
text/template

If these packages used gogo, they would have the issue because protobuf only uses template as the package name rather than html/template and text/template

**Comment by savaki** [comment]
Along these lines, is there any reason that the init func couldn't use a fully qualified import path rather than

`proto.RegisterType((*Activity)(nil), "appointment_table.Activity")`

?

**Comment by dsnet** [comment]
The error seen is generated by `protoc`, not `protoc-gen-go`. This should be filed with `google/protobuf`, which maintains `protoc`.
