### ISSUE TITLE
proposal: protoc-gen-go: generate MIN, MAX, ARRAYSIZE constants for enums

### ISSUE THREAD

**Issue by brtzsnr** [golang/protobuf#463]
For an enum `enum Foo {}` the C++ code [generates](https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#enum) `FOO_MIN`, `FOO_MAX` and `FOO_ARRAYSIZE`. 

These values are useful, but are [not created](https://developers.google.com/protocol-buffers/docs/reference/go-generated) automatically for the Go code. Would it be possible to add them?

**Comment by puellanivis** [comment]
`FOO_ARRAYSIZE` is not really necessary, because you can just use a `map[Enum]Type`, and you don’t really ever have to allocate an entire flat array to support the various values. Plus, Enums can also have negative values, so allocating a flat array like that isn’t really a good idea anyways…

If you stick to “no negative values” then you have an additional problem, in proto3, the FOO_MIN would always be 0 then. (The first Enum value has to be == 0.) So not much point of that.

This leaves FOO_MAX… which might sometimes have some value. But it also collides in namespace to someone defining an enum value `MAX`. Consider an enum defining operations, where MIN and MAX are now functions that you want to permit. :( Name collision with a builtin generated value.

If one really needs the maximal value of a particular enum, you could calculate it in an init()? “But if we know it at compile time, why not make it available?” … eh?

**Comment by brtzsnr** [comment]
Fair enough regarding MIN. ARRAY_SIZE is defined as MAX+1 afaik so I can leave without it.

With MAX you don't need to reuse the same key space. You can have FooMax instead of FooMAX to make it clear that is generated. The C++ does generated code does the same. The enum names are VALUE_A VALUE_B, but the max value is Foo_MAX.

**Comment by brtzsnr** [comment]
> “But if we know it at compile time, why not make it available?” … eh?

Right, it can be done at runtime, but MIN/MAX/ARRAY_SIZE are useful to generate efficient code.

**Comment by puellanivis** [comment]
> …useful to generate efficient code.

Eh, preemptive optimization, though… http://wiki.c2.com/?PrematureOptimization

I mean, this would be a few lines of code executed at the start of a program only for enums that you know you care about the maximum value for. In particular, proto3 code should allow for enum values outside of the currently known defined values.

This is mostly because protobuf handling code should be as forward/backward compatible as possible. And since an enum may be expanded, and your executing code just has not yet been updated to know about it, but it need be able to anticipate this. And just like the expectation is that code will pass on proto fields that it doesn’t otherwise know about, it’s expected that unexpected enum values would be preserved as well.

So, short of any particular profiling that shows that calculating the value at init time is a bottleneck, you’re not really endangering efficiency of code…

**Comment by dsnet** [comment]
The generated APIs have grown in complexity over time and every added change needs to be carefully considered. While I can see benefit to the constant being added, can you calculate the value at init time like @puellanivis suggested?

**Comment by dsnet** [comment]
I'm going to close this. I don't see a strong need for this. We can revisit in the future given evidence for a strong need. As much as possible, we want the generated APIs to be clean and lean, which is unfortunately not the case already. Adding more cruft is not the a step in that direction.
