### ISSUE TITLE
jsonpb: with EmitDefaults=true and proto2 messages, unset primitive fields marshal to "null"

### ISSUE THREAD

**Issue by wcadrin** [golang/protobuf#465]
The [proto2 language guide](https://developers.google.com/protocol-buffers/docs/proto#optional) states that "if a default value is not specified for an optional element, a type-specific default value is used instead".  Given that, I would expect optional primitive fields to be emitted with their implicit default.  Is the current behavior intended?

**Comment by dsnet** [comment]
\cc @cybrcodr

**Comment by cybrcodr** [comment]
The JSON serialization behavior is intended in order to preserve the "unset" information.  I believe this is consistent with proto serialization.  An optional field that is not set is not serialized out with any default value.

The statement that you quoted is about accessing default values from generated code.  Go generated protobuf code does include getter method that provide the default value if the field is not set.
