### ISSUE TITLE
protoc v3.5.0 not working as expected

### ISSUE THREAD

**Issue by athreya92** [golang/protobuf#470]
# **Version 3.3.0**
**Execution environment:** Windows 7
**Command:** `protoc --go_out=. *.proto`
**Outcome:** Proto files are generated

# **Version 3.5.0**
**Execution environment:** Windows 7
**Command:** `protoc --go_out=. *.proto`
**Expected Outcome:** Proto files must be generated
**Issue found:** _*.proto no such file or directory_

**Comment by puellanivis** [comment]
Thank you for reporting this, but the issue is isolated to protoc not to the golang/protobuf library or generator. As noted in this similar report: https://groups.google.com/forum/#!topic/protobuf/wfTV9KhyqXg Windows and POSIX shells work differently. i.e. Windows expects programs to glob() their own wildcards, while in POSIX, the shell is expected to glob() these, and pass matched files on the command-line itself.

I am unsure where your specific issue is creeping in, but the https://github.com/google/protobuf project is where you should be reporting.

**Comment by dsnet** [comment]
Agreed. If the same version of `protoc-gen-go` is used both times and only `protoc` has changed, then by definition this is a regression in behavior for `protoc`. The report is appreciated, but should be filed in the main `github.com/google/protobuf` repo.
