### ISSUE TITLE
protoc-gen-go: contextPkgPath should use "context"

### ISSUE THREAD

**Issue by hzxuzhonghu** [golang/protobuf#537]
[As of Go 1.7 this package(`golang.org/x/net/context`) is available in the standard library under the name context. https://golang.org/pkg/context. ](https://godoc.org/golang.org/x/net/context) So we should replace contextPkgPath  golang.org/x/net/context with context

**Comment by awalterschulze** [comment]
I am going to wait for golang/protobuf to fix this first
https://github.com/golang/protobuf/issues/537

**Comment by dsnet** [comment]
This is a trivial change, but requires us to be certain that certain users are definitely on Go 1.9 and above. It's not sufficient simply that we the `context` standard library, but that there is also support for type alias (in Go1.9) in order to consider the `context` and `golang.org/x/net/context` packages to absolutely identical.

My understanding is that we should be able to switch soon (but I've been saying for some time now). I want to see this switched as well.

**Comment by dsnet** [comment]
Merged into dev branch. See #479 for merging into master.

**Comment by hzxuzhonghu** [comment]
@dsnet Thanks

**Comment by dfawley** [comment]
@dsnet I don't see how this is OK.  We must continue to support Go 1.6-1.8.  In fact, this repo's Travis tests 1.6, and any tests of the grpc plugin (which are notably absent! :angry:) will fail because of this.

#579

**Comment by scharissis** [comment]
Where are we at with this?
I have a Go 1.11.1 application which, after generating protos with protoc-3.6.1, needs a "go fix", as it outputs the old `golang.org/x/net/context` with which my tests fail/panic.

**Comment by dsnet** [comment]
https://github.com/golang/protobuf/pull/580#issuecomment-431644276

**Comment by scharissis** [comment]
@dsnet - Cheers!

**Comment by thaJeztah** [comment]
Looks like this was implemented now through https://github.com/golang/protobuf/pull/742
