### ISSUE TITLE
proto: make RequiredNotSetError.field exported

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#58]
Would it be possible to add this function to proto/encode.go ?

```
func NewRequiredNotSetError(field string) *RequiredNotSetError {
    return &RequiredNotSetError{field}
}
```

That way generated code can also return a RequiredNotSetError with a field string.
Currently I have to:

```
return new(RequiredNotSetError)
```

Which is cool since then users can still type check the error, but it is pretty useless for debugging purposes.

**Comment by dsymonds** [comment]
I think I'd be more inclined to export the `field string` struct field instead. I'm not sure why that's unexported in the first place.

**Comment by awalterschulze** [comment]
That would also work for me :)

**Comment by dsnet** [comment]
Since gogo/protobuf already forked its own declaration of `RequiredNotSetError`, it seems that their is low utility is fixing this now. We have to address how to get multiple different `RequiredNotSetErrors` to cooperate and report itself as such an error.

https://github.com/golang/protobuf/commit/9834a7df51fdd420be3dd665299e474007f7f856 in the new API attempts to fix this by checking for a method that every custom error can implement.
