### ISSUE TITLE
proto: upstream changes breaking compatibility with Kubernetes

### ISSUE THREAD

**Issue by pbarker** [golang/protobuf#617]
https://github.com/golang/protobuf/commit/8cc9e46429bfb16289d40d30b2ee3f4923b47345 breaks compatibility with kubernetes. 

https://github.com/golang/protobuf/blob/master/proto/table_unmarshal.go#L331 mandates that all struct fields have proto tags. The `TypeMeta` fields in kubernetes structs do not contain a proto tag, https://github.com/kubernetes/apiserver/blob/master/pkg/apis/audit/v1beta1/types.go#L145 is a typical example.

If this change is necessitated we should work to put it in a major revision and allow `v1` to be compatible without tags.

**Comment by dsnet** [comment]
This struct is clearly not generated by `protoc-gen-go`. How is this generated?

**Comment by pbarker** [comment]
as I understand kubernetes generates the proto files from the go code, I'm not clear on the reasoning behind that, but this is a fairly breaking change to the project

**Comment by ncdc** [comment]
Kubernetes has support for a `protobuf:"-"` tag which indicates "ignore this field". Is there a similar convention here for ignoring a field for protobuf encoding/decoding?

**Comment by dsnet** [comment]
> Kubernetes has support for a protobuf:"-" tag which indicates "ignore this field". 

What does this mean? Does kubernetes have their own fork of the `proto` package?

**Comment by ncdc** [comment]
It has a tool that generates `protobuf:"..."` tags for the `types.go` files so humans don't have to manually keep them up to date. It parses the file, adding the tags to any new fields that were added since the last time the tool was executed. If we want to tell the tool not to serialize a specific field, we can add `protobuf:"-"` to it.

https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/code-generator/cmd/go-to-protobuf/protobuf

**Comment by thockin** [comment]
The history is awkward - gRPC didn't exist yet, so we did things the way "everyone else" did - JSON.  Then gRPC and proto hit the big time (outside G of course), and we were left holding the bag.

I don't know which cases go through this codepath any more.

@lavalamp @smarterclayton

**Comment by lavalamp** [comment]
We generate proto definitions from go source files. As a favor to authors, we then update the go source file (to e.g. add proto field numbers, so they don't change). We have some special handling for TypeMeta. Our protos are an envelop system, where typemeta determines the type of the message.

(No, I wouldn't do it this way again, and I bet @smarterclayton wouldn't, either.)

I'd have to go refresh my memory (reread our code) before I could say what our strategy should be. We vendor our dependencies so it shouldn't be an emergency until we need to get a security patch or something.

**Comment by smarterclayton** [comment]
We can generate an arbitrarily high tag for ignored fields like typemeta and make that an exclusion range, the continue to rely on gogoproto to skip those during generation of the marshallers.  We explicitly skip typemeta because we ignore it and it’s slightly faster.

**Comment by smarterclayton** [comment]
The IDL we generate can continue to omit those fields, which then results in marshallers that also ignore those fields.

**Comment by awalterschulze** [comment]
gogoprotobuf has not merged these changes yet, so then I assume you only use gogoprotobuf for generating the marshalers and unmarshalers, otherwise I don't know how you reached a golang/protobuf/proto code path?

If it is your intention to use gogo/protobuf/proto then there is a new [grpc-example](https://github.com/gogo/grpc-example) to show you how to use grpc and gogoprotobuf in a compatible way.

When gogoprotobuf merges these changes we are considering also adding new options to not generate these new XXX fields, since it does cause problems for users.  So please let me know if this would help?

**Comment by dsnet** [comment]
I don't think the issue here is with having the new XXX fields.

The proto library was originally designed to only support `protoc-gen-go`'s generated messages. However, there are increasingly more use cases (like `protoc-gen-gogo` and what Kubernetes has here). In this situation, the `proto` package is making the assumption that every field in a generated message either has a `protobuf` tag or one of the special `XXX_` fields, which is always the case with `protoc-gen-go` generated messages. However, this is apparently not true with `go-to-protobuf`.

The challenge with supporting use-cases other than `protoc-gen-go` is that this does not scale as we don't test whether other use cases continue to work and the assumptions other generators make is not known by us, so it is easy for us to break them (as evident by this issue). The proper solution for interoperability is #364, but that is still a ways away.

That said, I don't mind dropping the [the check here](https://github.com/golang/protobuf/blob/3a3da3a4e26776cc22a79ef46d5d58477532dede/proto/table_unmarshal.go#L331) and elsewhere in the equivalent logic in marshal (and merge?), so that your use case continues to work. However, this is not a statement that there is strong support for maintaining other use-cases. In the long run, I believe it is better to focus engineering efforts on #364 to avoid issues like this.

**Comment by pbarker** [comment]
@dsnet we're still struggling with this issue, would you accept a PR adding the [check](https://github.com/golang/protobuf/blob/3a3da3a4e26776cc22a79ef46d5d58477532dede/proto/table_unmarshal.go#L331) you mentioned above?

**Comment by dsnet** [comment]
Feel free to send a PR. I can review.

**Comment by dsnet** [comment]
The [v1.20.0 release](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0) completely overhauls the internal implementation such that this probably isn't an issue. If it is, we can open a new issue and take another look.

Long term, the custom protobuf types used in the Kubernetes project should implement the [`proto.Message`](https://pkg.go.dev/google.golang.org/protobuf/proto?tab=doc#Message) interface with their own protobuf runtime implementation.
