### ISSUE TITLE
jsonpb: incorrect nullability of repeated wrappers 

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#661]
(bug discovered from a question asked on Slack)

Consider the following:
```proto
message Dummy {
    repeated google.protobuf.DoubleValue hello = 1;
}
```
and
```go
func TestToJson(t *testing.T) {
    h := Dummy{Hello: []*wrappers.DoubleValue{&wrappers.DoubleValue{Value: 1}, nil}}
    m := jsonpb.Marshaler{}
    s, _ := m.MarshalToString(&h)
    fmt.Println(s)
}
```
this outputs:
```
{"hello":[1,null]}
```

However, this is incorrect as nullability is not a property on a per-message basis when the field is repeated.

**Comment by jozuenoon** [comment]
Would be great also to see non-pointer list for clarity!

**Comment by puellanivis** [comment]
@jozuenoon I am confused. Do you mean it should be: `[]wrappers.DoubleValue{}` instead of `[]*wrappers.DoubleValue{}`?

I don‘t think there is any way to know the element length of a repeated message field prior to processing it, and as such we cannot be sure how long of a `[]wrappers.DoubleValue` to allocate. And while right now `wrappers.DoubleValue` is small, how do we programmatically recognize “small” message structs from large ones, which need to remain pointers as each `a = append(a, …)` could end up needing to copy the entire allocated space?

**Comment by jozuenoon** [comment]
I think it's just trade-off.

With `[]wrappers.DoubleValue{}` you clearly express protobuf limitation that it's not allowed to have `nil` values in slice. However as you mentioned there is possible allocation problem when appending and reallocating with big structures.

With `[]*wrappers.DoubleValue{}` you avoid any allocation problems. However with `nil` values you run (even unintentionally) into run-time error from protobuf marshaller which is hard to recover from.

Our use case is that we pass vector data which is allowed to have `nil` values when no "reads" were found and yet I have no idea how to express it in valid protobuf (anyone?).

Truly preferable solution would be to keep  `[]*wrappers.DoubleValue{}` and enable proto marshaller to consume `nil` values (as it works now with `jsonpb`).

And seems that [`C#`](https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/collections/repeated-field-t-#class_google_1_1_protobuf_1_1_collections_1_1_repeated_field_3_01_t_01_4_1a7b8e1737b43e97f7bfa7b983ba2947ff) and [`C++`](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.repeated_field) API express that limitation by having overlay classes which are guarding user from throwing in `null` pointers into repeated fields as in contrast to `Go` API  where we have `- Repeated fields are slices.`

**Comment by puellanivis** [comment]
Yeah, it‘s hard. But there is literally no way to represent a `nil` message in a repeated message field, because on the wire the only way to represent a `nil` message is by its absence, but in a repeated field, an absent message would just simply not exist.

We could perhaps handle the allocation problem by handling internally a slice of pointers to messages, as we build the slice, but then at the end, we allocate a slice of non-object pointers, and then copy in the values into each element. This would keep the memory copying close to O(N)…

But then there remains a question of a possible breaking change, in which complex literals are changing type from a slice-of-pointers to a slice-of-objects. :confused: 

So, no good answers, without complicating things enormously. I’m usually for the case of keeping the happy-path simple, and then say… throwing away the `nil` values as if they don’t even exist while Marshaling… or throwing an error. “We cannot stop you from building these complex literals, but they will error.”

**Comment by dsnet** [comment]
You are correct that `[]T` is all you need to represent repeated messages. However, a major detriment of the `[]T` representation is the number of bugs that arise from doing the following:
```go
for _, m := range m.MyRepeatedMessages {
    m.FieldFoo = proto.String("hello")
}
```
Here, there is no compile-time safety that you a mutating a value, as opposed to a pointer. Arguably this is a weakness with the language, but we should avoid APIs that allow users to shoot themselves in the foot as much as possible.

**Comment by dsnet** [comment]
> throwing away the nil values as if they don’t even exist while Marshaling… or throwing an error. “We cannot stop you from building these complex literals, but they will error.”

Alternatively, we could treat a nil message as if it were an empty message. That would be consistent with the fact that calling the `Get` methods on a nil message is indistinguishable from calling them on an empty message.

**Comment by dsnet** [comment]
The new [`protojson`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) package addresses this issue and has been released as part of [`google.golang.org/protobuf@v1.20.0`](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0).
