### ISSUE TITLE
protoc-gen-go: should not generate invalid package names

### ISSUE THREAD

**Issue by nicks** [golang/protobuf#680]
Using protoc-gen-go at HEAD, the tool doesn't really do any validation of package names. For example, if you have,

```
option go_package = "hi this is an invalid package name";
```
then protoc ignores the file quietly and produces no output. Worse, if you have a subtly invalid package name like:

```
option go_package = "github.com/typo-two-slashes//foo";
```

protoc will happily generate code that doesn't compile.

Would you accept a PR to add some validation here?

**Comment by dsnet** [comment]
This is a reasonable request, but I don't think we can do this for backwards compatibility reasons. There's already a [`cleanPackageNames` function that sanitizes bad names into valid ones](https://github.com/golang/protobuf/blob/89a0c16f4dc2a70c0ed864d8ef64878f24fdaa51/protoc-gen-go/generator/generator.go#L588-L599). It could be argued that `cleanPackageNames` should never have been added, but it already too late. At best, we should figure out why `protoc-gen-go` is not generating a valid package name and fix `cleanPackageNames` in a backwards compatible way.

\cc @neild

**Comment by nicks** [comment]
can you elaborate a bit on the backwards compatibility concerns?

for the first case (where protoc ignores the file), it seems like we could add a warning, see how bad the issue is, and maybe upgrade it to an error when there's a major version bump?

for the second case (where it generates bad code), it seems like is there's no backwards compatibility concerns? the code already doesn't compile, so it'd just be moving the compile error earlier in the process?

**Comment by dsnet** [comment]
> can you elaborate a bit on the backwards compatibility concerns?

Sure. Your earlier statement that "protoc ignores the file quietly" isn't quite correct. When `protoc` shells out to `protoc-gen-go`, the code uses the `cleanPackageNames` function to derive a valid package name from the `go_package` option. Since it already does this today, changing it into an error would breaking people already relying on this sanitization logic.

> it seems like we could add a warning, see how bad the issue is, and maybe upgrade it to an error when there's a major version bump?

Warnings almost never work. C++ has been warning that you should use invalid UTF-8 with string fields, yet that is still a pervasive problem years later.

> for the second case (where it generates bad code), it seems like is there's no backwards compatibility concerns? the code already doesn't compile, so it'd just be moving the compile error earlier in the process?

If it is generating invalid code as a result of these poorly formatted `go_package` options, then that's probably a bug, but it's not clear from the original post exactly what the error is.

**Comment by nicks** [comment]
When people say, "warnings don't work", they're usually saying "warnings aren't a good mechanism to nudge people to fix minor issues." 

I've never heard someone use that point to argue "tools should fail silently and give no diagnostic output on why they're failing". I hope that's not what you're saying here.

Question: It sounds like the team's position is "we can't ever add new errors because that would break backwards compatibility". Is my understanding correct? Would that position change with vgo and the ability to do major version bumps?

To answer your question: protoc-gen-go will generate something like:

```
package proto // import "github.com/typo-two-slashes//foo"
```

which will fail to compile due to import path checking (https://golang.org/pkg/cmd/go/#hdr-Import_path_checking)

**Comment by dsnet** [comment]
> Question: It sounds like the team's position is "we can't ever add new errors because that would break backwards compatibility". Is my understanding correct? Would that position change with vgo and the ability to do major version bumps?

Correct. As much as I believe the defaults chosen in `protoc-gen-go` are somewhat problematic, they are what exists today and many people have already built tooling infrastructure around `protoc-gen-go`. I agree with you that complaining about invalid package names up-front is ideal, but gutting out `cleanPackageNames` is not something that we can do now. Also, while `cleanPackageNames`'s behavior is surprising, it is consistent and thus not "silently failing". 

> Would that position change with vgo and the ability to do major version bumps?

The new modules support doesn't really make major version changes easier. It makes dependency management easier for *minor* versions, but not *major* versions since you are still required to rename per the "import compatibility rule" (which is something you can always do today pre-modules). Major version bumps are very costly and should only be done if the benefits greatly outweigh the costs. If we ever do a major version change of `protoc-gen-go`, I would love to see this addressed, but this alone does not justify a v2.

> which will fail to compile due to import path checking

That failure is not a problem with the import path per-say, but rather import path checking. The Go specification says that the [import path can be any arbitrary string](https://golang.org/ref/spec#Import_declarations), and thus, there is no such thing as a "valid" import path. There are common guidelines around what a valid import path is, but guidelines aren't quite the same as hard rules. 

Given that:
1) We can't change the logic to validate package *names* for compatibility reasons.
2) The issue of "invalid" package *paths* seems to be due to [import path checking](https://golang.org/pkg/cmd/go/#hdr-Import_path_checking), which is a separate issue.

Are you okay with closing this issue in favor of #678 (which I filed yesterday to strip out generation of the magic import path comment)?

**Comment by dsnet** [comment]
Thinking about this more, even with the removal of the magic import path comment, the generated code is still going to be broken, and the fundamental reality is that import path points to a package that does not exist. Unfortunately, `protoc-gen-go` cannot know whether the place that it generated the `.pb.go` file is really represented by the import path claimed in the `.proto` file. The tool that has this information is the Go compiler, so letting the Go compiler complain is the right place for the error to arise.

**Comment by nicks** [comment]
i meant it's failing silently in the `option go_package = "hi this is an invalid package name";` case, no?

in any case thanks for considering, feel free to close this issue.

**Comment by dsnet** [comment]
It's not silently failing. That option gets converted into a Go package named `hi_this_is_an_invalid_package_name`, which is valid. It silently transforms bad names into valid ones, but it's certainly not silently failing.
