### ISSUE TITLE
protoc-gen-go: JSON struct tags are generated with the wrong naming convention

### ISSUE THREAD

**Issue by bmhatfield** [golang/protobuf#698]
**What version of protobuf and what language are you using?**
% go version
go version go1.11 darwin/amd64

**What did you do?**
Observed that generated code looked funny:

```
InviterUserId string `protobuf:"bytes,2,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
```

**What did you expect to see?**
I expected the `json=` output in the `protobuf:` tag to match the `json:` tag field name.

**What did you see instead?**
JSON tag field naming that doesn't match JSON field norms.

The problem is that g.goTag uses `GetJsonName` but the actual JSON tag generation uses `*field.Name`.

Reccomendation:
Switch https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L2488 to use `GetJsonName` just like https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L1548

**Comment by dsnet** [comment]
The situation is unfortunate and can't be changed without breaking existing code. The generation of the `json` tag pre-dated the formalization of the [JSON<->PB specification](https://developers.google.com/protocol-buffers/docs/proto3#json). In it's current state, using `encoding/json` does not produce JSON that conforms to any particular pre-defined schema.

The [`jsonpb` package](https://godoc.org/github.com/golang/protobuf/jsonpb) exists to implement the aforementioned JSON specification since it is not possible to do so using the `json` tags alone. Rather than fixing the `json` tag, it should probably be removed entirely and have #256 addressed instead.

**Comment by dsnet** [comment]
Closing as there's not really any actionable to do here without breaking compatibility. The best we can do is #256.
