### ISSUE TITLE
second order plugins no longer execute after c22ae3cf

### ISSUE THREAD

**Issue by naelyn** [golang/protobuf#7]
I have a second order plugin written in Go and after updating my golang/protobuf code and compiler locally, my plugin is no longer called.

I traced it down to a somewhat innocuous part of c22ae3cf:
```
diff --git a/protoc-gen-go/generator/generator.go b/protoc-gen-go/generator/generator.go
index af0e15f..49f91d7 100644
--- a/protoc-gen-go/generator/generator.go
+++ b/protoc-gen-go/generator/generator.go
@@ -484,7 +484,7 @@ func (g *Generator) CommandLineParameters(parameter string) {
        }
 
        g.ImportMap = make(map[string]string)
-       pluginList := "" // Default list of plugin names to enable (empty means all).
+       pluginList := "none" // Default list of plugin names to enable (empty means all).
        for k, v := range g.Param {
                switch k {
                case "import_prefix":
```

Why the change from ```s/""/"none"/```?  How (short of striking the above line) can I cause my second order plugin to continue to execute?

**Comment by dsymonds** [comment]
We now have a standard plugin ("grpc") that is linked into the binary. If you're linking against this code to add one or more other plugins then it is too chaotic to run every plugin by default, since they aren't necessarily coordinated and are writing to the same file. What you do is select which plugins you want to run from the command-line, overloading the --go_out argument to protoc:
```
protoc --go_out=plugins=foo:. path/to/whatever.proto
```
That will enable the `foo` plugin.
