### ISSUE TITLE
Add method that wraps oneof messages in their wrapper struct

### ISSUE THREAD

**Issue by nhooyr** [golang/protobuf#727]
**Is your feature request related to a problem? Please describe.**
oneof fields are annoying and clunky to use at the moment. In particular wrapping the actual type of the message with the wrapper struct is clunky.

**Describe the solution you'd like**
I want to write a function like this:

```go
func (c *client) write(m proto.Message) {
	msg := mypbpackage.MasterMessage{
		Msg: mypbpackage.WrapMyOneOfField(m),
	}
	// Write the message to the client...
}
```

(I have a "master" message that contains all of the messages I can send to the client as a oneof field and this function is supposed to write one of those oneofed messages)

What's missing is the `mypbpackage.WrapMyOneOfField` method. I'd like that to be auto generated. It would take a `proto.Message` and return the interface implemented by all of the `oneof` wrapper structs (this interface would now have to become exported).

**Describe alternatives you've considered**
Manually writing this function. I'm doing this for now but it'd be nice if it was autogenerated. The other alternative is to manually wrap oneof messages every time which is annoying.

Somewhat related #708

**Comment by puellanivis** [comment]
Given:
```
message A {
  oneof my_oneof {
    string name = 1;
    string alt_name = 2;
  }
}
```

How does your proposal work?

**Comment by nhooyr** [comment]
That is very unfortunate. I was not aware that was a possibility.

**Comment by dsnet** [comment]
This is unrelated to #708 as that issue is regarding hiding internal details of oneof, and has nothing to do with the public API.

It seems that your use-case is more in line with the purposes of the [Any message type](https://github.com/protocolbuffers/protobuf/blob/d2d4b403b580690b3cb25cb3d2b32d567044619e/src/google/protobuf/any.proto#L122-L155) given that you have a field in the "master" message can be only oneof a bunch of different messages.

As @puellanivis noted, oneofs do not seem to be what you want since:
* They function as tagged unions where multiple members of the oneof may be of the same type, but with different names.
* They types permitted in a oneof are not always messages.

Closing as working-as-intended. We can't add this functionality as it assumes some specific semantic of oneofs that isn't true.

**Comment by nhooyr** [comment]
Thanks for the link to the Any message, that seems perfect.

**Comment by puellanivis** [comment]
Glad you’re able to find a forward path. :+1:
