### ISSUE TITLE
CamelCasing of identifiers with digits produces unexpected underscores and caps

### ISSUE THREAD

**Issue by macmason** [golang/protobuf#734]
**What version of protobuf and what language are you using?**
Version: `d7fc20193620986259ffb1f9b9da752114ee14a4`

**What did you do?**
Defined a protobuf field named `laser_scan_2d_dense` and used it.

**What did you expect to see?**
A field named `LaserScan2dDense`.

**What did you see instead?**
`LaserScan_2DDense`. There's an extra underscore, and an extra capitalization, too (2D, not 2d). That's wacky. 

What's going on here (I think) is that `CamelCase` from `generator.go` defines digits to be "uppercase", so it sees `_2d_` like it would see `_FOO_`.

This behavior is poorly-documented (cf https://developers.google.com/protocol-buffers/docs/reference/go-generated#fields), and is deeply surprising.

**Comment by dsnet** [comment]
Hi Mac, thank you for the report.

The logic in the came-case function is indeed strange. I wish we could change it, and we actually considered changing it for the v2 API, but came to the conclusion that we simply cannot. Doing so would break too much of the world. When a given proto package depends on another proto package, it needs to exactly know the names of the types in the other package. It accomplishes this because it knows that the same camel-case function was used to name types in that other package.

The situation is unfortunate, but we can't change it. We could document the exact behavior better, but it does contain an example with an underscore-followed-by-number already.
