### ISSUE TITLE
Extracting custom option info from Protobuf message

### ISSUE THREAD

**Issue by munukutla** [golang/protobuf#794]
I have declared the below Protobuf schema for declaring some sensitive fields in a `CardInfo` message.

```protobuf
extend google.protobuf.FieldOptions {
    GdprPolicy gdprPolicy = 50001;
}

message GdprPolicy {
    GdprPolicyType type = 1;
    int32 allowedLength = 2;
}

enum GdprPolicyType {
    TRUNCATE = 0;
    MASK = 1;
}

message CardInfo {
    string cardType = 1;
    string ccv = 2 [(gdprPolicy).type = TRUNCATE];
    string card_number = 3 [(gdprPolicy).type = MASK, (gdprPolicy).allowedLength = 4];
}
```

The relevant Golang Proto extension registered in the generated code is the below
```go
var E_GdprPolicy = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*GdprPolicy)(nil),
	Field:         50001,
	Name:          "gdprPolicy",
	Tag:           "bytes,50001,opt,name=gdprPolicy",
	Filename:      "NotificationRequest.proto",
}
```

In my Go code, I have the below struct
```go
cardInfo := &lib.CardInfo {
    CardType: "VISA",
    CCV: "456",
    CardNumber: "123456789",
}
```

My use case is to find out all GDPR sensitive fields in my struct and mask/truncate them accordingly (say, before dumping it into my data lake, or outsourcing for analytics). From the documentation, I would do the following.

```go
import "github.com/golang/protobuf/proto"

policy, err := proto.GetExtension(cardInfo, lib.E_GdprPolicy)
if err != nil {
	panic(err)
} else {
	fmt.Println(policy.(gw.GdprPolicy))
}
```

It throws the below error
```
panic: proto: not an extendable proto.Message
```

I tried checking `proto.HasExtension(cardInfo, lib.E_GdprPolicy)` and it returns `false` as well.

Wondering if I'm using the correct API for this?

**Comment by neild** [comment]
The problem is that you're looking at the wrong message: The `gdprPolicy` extension is extending `google.protobuf.FieldOptions`, not `CardInfo`.

The v2 proto API will provide an easy way to get at this information, but it won't be available until later this year so that unfortunately isn't much help to you right now. For the moment, you should be able to use the [`"github.com/jhump/protoreflect/desc"`](https://godoc.org/github.com/jhump/protoreflect/desc) package.

**Comment by lukesneeringer** [comment]
Has the "v2 proto API" been released yet? I too am trying to read an extension and have utterly failed in doing so.

Side note: The developer experience on this issue is utterly miserable. There are two protoreflects (not Google's fault as one is independent), at least four different descriptor packages (1000% Google's fault), the protos themselves are in non-obvious locations (_ibid._), and so on and so forth. Everything requires guess and check and has no useful documentation or examples, and no library seems to work with any other library.

**Comment by dsnet** [comment]
v2 is released when all `blocks-v2` labels are closed: https://github.com/golang/protobuf/issues?q=is%3Aissue+is%3Aopen+label%3Ablocks-v2

**Comment by neild** [comment]
> I too am trying to read an extension and have utterly failed in doing so.

Can you describe what you're trying to do in more detail? "Read an extension" covers a lot of ground. Using the example in the original post here, in the new API (`google.golang.org/protobuf`, unreleased) you'd do something like:

```go

func f(m *somepb.CardInfo) {
        m.ProtoReflect().Range(func(fd protoreflect.FieldDescriptor, value protoreflect.Value) bool {
                opts := fd.Options().(*descriptorpb.(FieldOptions))

                // Fetch extension using github.com/golang/protobuf/proto package:
                var policy *somepb.GdprPolicy
                if x, err := protoV1.GetExtension(opts, somepb.E_GdprPolicy); err != nil {
                        policy = x.(*somepb.GdprPolicy)
                }

                // Fetch extension using google.golang.org/protobuf/proto package, once GetExtension is added
                policy = protoV2.GetExtension(opts, somepb.E_GdprPolicy).(*somepb.GdprPolicy)

                // Do something with the policy info.
        })      
}       
```

**Comment by lukesneeringer** [comment]
My current (non-working) code is [here](https://github.com/googleapis/api-linter/blob/aip-131-annotation/rules/0131.go#L97).

Essentially, given an RPC...

```proto
rpc GetBook(GetBookRequest) returns (Book) {
  option (google.api.http) = {
    get: "/v1/{name=publishers/*/books/*}"
  };
}
```

...I want to read the `google.api.http` annotation for linting purposes (I want to make sure it follows the right pattern).

My method receives a `MethodDescriptor`, and I can import the extension itself. I just can not figure out how to say, "Give me the value assigned to the option."

**Comment by neild** [comment]
The problem you're running into is admittedly extremely confusing, and is a result of the unreleased state of `google.golang.org/protobuf`.

The problem is that the `"google.golang.org/protobuf/types/descriptorpb"` package you're using isn't compatible with the version of the `github.com/golang/proto` package that you're using. As a result `proto.GetExtension` fails because it doesn't know how to fetch an extension from that message.

If you're using Go modules, you can fix this by depending on the unreleased branch of the `github.com/golang/protobuf` repository that includes the necessary compatibility support:

```
go get github.com/golang/protobuf@api-v1
```

Sorry; I realize that this is very confusing. This is one example of why `google.golang.org/protobuf` isn't released yet.

**Comment by lukesneeringer** [comment]
Thank you for the help. I am a little closer...

    > fmt.Printf("%v", httpRule)
    < get:"/v1/{name=publishers/*/books/*}"

But apparently `httpRule` is a type `interface {}` with no methods (I get that in an error message whenever I try to call anything.

**Comment by neild** [comment]
`proto.GetExtension` returns an `interface{}` which can be type asserted to correct concrete type; from my example above:

```go
                // Fetch extension using github.com/golang/protobuf/proto package:
                var policy *somepb.GdprPolicy
                if x, err := protoV1.GetExtension(opts, somepb.E_GdprPolicy); err != nil {
                        policy = x.(*somepb.GdprPolicy)
                }
```

**Comment by lukesneeringer** [comment]
I figured it out. Thank you _so_ much for your help.
