### ISSUE TITLE
APIv2: encoding/textpb: nil messages

### ISSUE THREAD

**Issue by cybrcodr** [golang/protobuf#798]
If repeated field item or map field value is a pointer to a message type and value is nil, it currently produces empty message {}.  I think this is incorrect.
Sample proto definition --
```
message M {
    repeated N list = 1;
    map<string, N> mmap = 2;
}
```
Sample code to construct message --
```
m := &M{
    List: []*N{nil},
    Mmap: map[string]*N{"nil": nil},
}
```
Textproto output --
```
list: {}
mmap: {
  key: "nil"
  value: {}
}
```

We can opt to have this return an error, but should it be a nonfatal error in order to still produce an output for debugging purposes.  If so, what should the value be?  v1 produces \<nil\> (for repeated item) or "nil" (for map value).  That will of course not round-trip, but probably OK since it returns an error.

I can't seem to figure out though from the protoreflect API on how to tell if a List item or a Map value item contains a nil message or not -- https://go-review.googlesource.com/c/protobuf/+/161717.

Related to this is unmarshaling textproto where map is missing value, e.g.
```
list: {}
mmap: {
  key: "nil"
}
```

v1 produces a map value of nil, while C++ constructs a map with single entry containing empty message value.

**Comment by dsnet** [comment]
The problem is that a nil message has no exact corollary in protobuf data model. Currently, the generated API sets the precedence that a nil message is functionally a read-only version of a message. That is:
```go
m := (*foopb.MyMessage)(nil)
m.GetMyField() // this works
m.MyField = 5  // this panics
```
The current implementation of reflection follows this pattern. Calling the reflective API on a nil message will present it as a read-only empty message.

> We can opt to have this return an error

In order to make this an error, we would need to expand the reflection API to be able to represent this. However, I'm not sure that's a good idea since this is an artifact of the implementation, not the way protobufs fundamentally work. Expanding the API for this use-case seems like more complexity for little benefit and also a slight violation of protobuf type system. 

> I can't seem to figure out though from the protoreflect API on how to tell if a List item or a Map value item contains a nil message or not

That's intentional per my explanation above.

> Related to this is unmarshaling textproto where map is missing value, e.g.

I think the unmarshaler should avoid ever producing an invalid situation. Thus, it should allocate a new empty message even if the value field is missing.

**Comment by cybrcodr** [comment]
I discussed this with @neild and agree on the following --

There is no concept of nil messages as proto repeated field item nor map item value.  So, it is ok to marshal out as an empty message.  This will allow for round-trip back or having the output be parsable in other language implementations as well.

Given that <nil> or "nil" is not a valid textproto input (one that v1 currently produces), v2 unmarshal should return an error.

We should also be consistent in v2 JSON marshaling and unmarshaling.  Marshal out empty message for nil message pointers as (1) it is not valid to have JSON proto repeated field to contain null, (2) it is not valid to have JSON map field message item be null.  Unmarshaling should return error when parsing these.
