### ISSUE TITLE
protoc-gen-go + omitempty JSON struct tags

### ISSUE THREAD

**Issue by evanfrawley** [golang/protobuf#799]
```
message GameData {
    uint32 kills = 1;
    uint32 assists = 2;
    uint32 deaths = 3;
    uint32 seconds = 4;
    uint32 minutes = 5;
}
```

`proto3` and `protoc-go-gen` generates this message into a struct with `json:...,omitempty` tags on them. Is there a way to prevent `,omitempty` tags from being generated on the structs?

For the data, it is important that `kill`, `deaths`, or `assists`, can be 0 -- and I'd like that to appear instead of being empty when I generate JSON from the struct.

**Comment by farzaa** [comment]
Same issue!

**Comment by cybrcodr** [comment]
Marshaling protobuf messages into JSON requires the use of the `github.com/golang/protobuf/jsonpb` package due to special rules and nuances around it.  The [Marshaler](https://godoc.org/github.com/golang/protobuf/jsonpb#Marshaler) has EmitDefaults field option that will produce zero values for fields that are not set.  Hope that works for you.

I'm curious though in terms of your use case, does the consumer require having those fields?  It would be nice if the consumer is more flexible to deal with missing fields.

**Comment by evanfrawley** [comment]
Thanks for the reply @cybrcodr !

When I ran into this problem, I was using a protobuf struct as a value in another struct's field (before sending it over to a client via http). I circumvented this issue by making a "client side" struct, that would take the protobuf's struct K/V pairs and translate them into the new struct, doing some data transformations as necessary. It would seem problematic to send over the raw decoded protobuf struct back up to a client via http, since protobuf fields can change and potentially break the client side code. Does this approach seem naive or have glaring issues?

I do agree with you that it would be nice if the consumer would be more flexible.

**Comment by dsnet** [comment]
I'm going to close this in favor of #256. At this point, we're unlikely to allow manual control of the `json` tags. Generation of them in the first place was a mistake. For the use-cases (like yours) where you want to nest a protobuf message as part of a larger type tree, having the messages implement `MarshalJSON` and `UnmarshalJSON` would fix your problem.
