### ISSUE TITLE
protoc-gen-go: allow specifying the enum datatype

### ISSUE THREAD

**Issue by CAFxX** [golang/protobuf#802]
**Is your feature request related to a problem? Please describe.**
When generating code for an enum, the go datatype is apparently hard-coded to int32. In some circumstances, e.g. when the resulting data structures are also used as interchange/storage format, it would be extremely convenient to allow the proto file to define which go type to use.

Another use case is, as the protobuf docs themselves mention, to improve backwards compatibility of the generated code when switching the field type from enum to another type that has the same wire encoding.

**Describe the solution you'd like**
It would be useful to be able to specify in the .proto file (as an option, maybe?) which datatype to use for a specific enum. As an example (other mechanisms or names are totally OK as long as the use-cases above are addressed):

```
enum MyEnum {
  // whatever
}

message MyMessage {
  MyEnum field_name = 1 [(go_enum_datatype) = "uint64"];
}
```

The only allowed types should be at least those for which the enum wire type is compatible ("enum is compatible with int32, uint32, int64, and uint64", https://developers.google.com/protocol-buffers/docs/proto3#updating), but ideally with any go integer type, i.e. `u?int(8|16|32|64)?`.

**Describe alternatives you've considered**
Not many alternatives short of not using enums and using an integer type.

**Comment by neild** [comment]
In what cases would this be useful? There are no automatic conversions between named types, so you still wouldn't be able to assign an int64 or whatever to or from the field without a type conversion.

Or are you suggesting that the type of the field literally be int64? i.e., instead of

```go
type MyEnum int32

type MyMessage struct {
  FieldName MyEnum
}
```

You'd have

```go
type MyMessage struct {
  FieldName uint64
}
```
?

That seems like a significant loss in type safety just to avoid a type conversion in some cases.

**Comment by CAFxX** [comment]
An example use-case is to minimize in-memory message footprint.

Another example is when turning an existing `intX` field into an enum (a change that is backwards-compatible on the wire, but not at the API level)

**Comment by puellanivis** [comment]
In-memory message footprint is a specious argument. Using a `uint8` will not necessarily save any space over `int32` because of memory-alignment mechanics: https://play.golang.org/p/ICIdzqDZ5lJ

While the presented case is pathological (1+8+2+4 = 24), the best-case ordering (B, H, W, D) is still 16-bytes, not the expected 1+2+4+8=15. Working within the memory-alignment rules, `int32` is really the best of all alternatives… even over letting the user specify it themselves.

As for turning an existing `intX` field into an `enum`, that will still require a code-change due to the strict type handling in Go. We cannot get the “magic” of enums having a `String()` receiver method that produces the enum’s string value without defining a type, and by defining a type, we will require a cast of any `intX`-typed value into that type. (NOTE: assigning un-typed constants already works now.)

**Comment by dsnet** [comment]
Our policy is to avoid any features or representation that's different from what the other major language implementations do. Since they (e.g., C++ and Java) don't allow specifying the underlying memory representation on an enum, we won't be providing such an ability to control this. If there's a change in the overall protobuf ecosystem regarding this, then we can revisit this.
