### ISSUE TITLE
proto: textproto marshal writes comments with invalid syntax

### ISSUE THREAD

**Issue by darkfeline** [golang/protobuf#814]
The textproto marshaller writes various comments using `/* */` syntax.  Example:

https://github.com/golang/protobuf/blob/f05648d464991ab1aa8cf6a499122c56f0f50f2f/proto/text.go#L597

This is invalid textproto format.  The parser respects comments starting with `#`

https://github.com/golang/protobuf/blob/f05648d464991ab1aa8cf6a499122c56f0f50f2f/proto/text_parser.go#L136

I couldn't find a spec for textproto, but the Python parser agress that comments start with `#`.

https://github.com/protocolbuffers/protobuf/blob/624a40a387e1b2da4c6bbde44ad3d0a5efb9879b/python/google/protobuf/text_format.py#L1060

**Comment by dsnet** [comment]
\cc @cybrcodr

**Comment by darkfeline** [comment]
(I'd be happy to help fix it if a dev agrees this makes sense, since it's easy.)

**Comment by dsnet** [comment]
The current `master` branch is more or less in maintenance mode as all effort is going towards the v2 implementation, which actually doesn't have this bug.

My concern with making this change is the amount of people it breaks that depend on the output of text proto to be stable. These are clearly invalid usages, but fixing them is not something we want to deal with right now.

@cybrcodr can decide whether it's worth changing in v1.

**Comment by puellanivis** [comment]
It seems like you’re right and the C and Python implementations only accept `#` as a comment style. However, the reason you cannot find any standard for the plain text representation of protobufs is because there is intentionally no standard for the simple text format. It was always intended that this text format would only be used for debugging and quick-and-dirty editing, and not for any form of actual interchange. It was decided that the best way to ensure this was to not actually define any standard at all, and if someone objected to a lack of interoperability, one would then jsut point to the intentionally blank space where a standard should be.

Once a JSON encoding was established and standardized, this only further eliminated any need to standardize the simple text format.

So, general rule of thumb is the plain text formatting `SHOULD` attempt to conform to a common implementation, but that it `CANNOT` be relied upon to actually be compatible as an interchange format, because there is no actual standard. If one needs a guarantee of interoperability, one `MUST` rely upon one of the two standardized encodings: binary or JSON.

**Comment by cybrcodr** [comment]
That comment is only produced when there are unknown fields.  And afaik, unknown fields cannot be parsed back by either current Go or C++ parsers.  Hence, this hasn't been much of a priority.

If you care about producing a textproto output that can be parsed back, you can call `proto.DiscardUnknown()` before marshaling to textproto.

Anyways, I think we'll eventually have this fixed, but somehow you think this is important, feel free to send a PR.

**Comment by darkfeline** [comment]
> That comment is only produced when there are unknown fields. And afaik, unknown fields cannot be parsed back by either current Go or C++ parsers. Hence, this hasn't been much of a priority.

Understandable, however I think that if Marshal returns without errors, it's reasonable to expect that Unmarshal then does not return a syntax error, with the exact same version of the library.

**Comment by cybrcodr** [comment]
I'm not sure I understand, and I must admit that I'm not familiar with this codebase.  Producing wrong comment symbol is independent from returning errors, right?  i.e. I know that Marshal will produce the /* */ comment for unknown fields, but it doesn't return any error because of that.  However, Unmarshal will still return an error because it is unable to parse unknown fields.

I looked at your PR and noticed that there are other places where it produces the wrong comment symbol, not just for unknown fields, which I wasn't expecting.  I would rather remove these comments instead of simply changing the comment symbol.  Anyways, I'll  provide feedback on your PR.

As @dsnet mentioned, we are focused on getting v2 out and this is not an issue there.  We'd prefer to not make more updates on v1 unnecessarily in order not to introduce new issues.  If somehow your PR did introduce a new issue, we'd have to roll it back and I won't have much time to spend on this, just letting you know ahead.

**Comment by dsnet** [comment]
The new [`prototext`](https://pkg.go.dev/google.golang.org/protobuf/encoding/prototext) package addresses this issue and has been released as part of [`google.golang.org/protobuf@v1.20.0`](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0).
