### ISSUE TITLE
jsonpb: Allow limiting message depth and size

### ISSUE THREAD

**Issue by hewenyang** [golang/protobuf#815]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
When parsing google.protobuf.Any, allowing messages of arbitrary depth could exhaust the resources needed to parse the message since the complexity (in terms of both CPU time and memory) is O(depth * size). When the message is arbitrarily deep, the complexity could be square to the size of the message.

The issue is made further serious by the fact that it's not possible to abort parsing.

The example at <https://github.com/hewenyang/jsonpb_dos> creates a message of just 29029 bytes but it takes about 0.5 seconds to parse. Doubling the size of the message quadruples the resources needed for parsing.

**Describe the solution you'd like**
A limit on message depth and size and a way to abort parsing after a specified timeout (like a context).

**Describe alternatives you've considered**
Limiting message size doesn't help since 29KB is a reasonable size of message to expect.

**Additional context**

The same feature request might apply to other languages but I'm not sure where to post it.

**Comment by dsnet** [comment]
It is known that the parsing algorithm is O(n**2) for `jsonpb` (not just for Any). It seems that the solution to this is to fix `jsonpb` to stop being inefficient have a guaranteed runtime of O(n), rather than adding additional API to work around the current implementation's poor behavior.

The v2 implementation guarantees an O(n) runtime, so I dont think this is an issue in the near future.

**Comment by dsnet** [comment]
\cc @cybrcodr

**Comment by dsnet** [comment]
Closing this as the new implementation does not have this issue and will replace the v1 implementation.
