### ISSUE TITLE
jsonpb: Allow rendering extension field names without square brackets

### ISSUE THREAD

**Issue by zdicesare** [golang/protobuf#823]
**Is your feature request related to a problem? Please describe.**
Names of extension fields are rendered enclosed in square brackets. When serializing JSON we don't wish these fields to appear any different from non-extension fields.

This behavior is located [here](https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L364)

**Describe the solution you'd like**
I'd like to add a boolean configuration option to the `Marshaler` struct that will by default continue to emit extension field names in brackets, and if configured otherwise will emit the name without brackets.

**Describe alternatives you've considered**
Since I am dealing with an extension object on a third-party proto definition I don't believe I can just implement `JSONPBMarshaler`.

**Additional context**
If this is confirmed to be something people are open to I can put up a PR with this change

**Comment by dsnet** [comment]
The protobuf JSON specification lacks a formal definition of how proto2 extensions are handled, but the convention throughout the protobuf ecosystem is to serialize them with brackets. Go is not unique in handling them this way and the goal of the project is to maintain compatibility with other languages.

The usage of brackets has semantic purpose since it is what enables the parser to distinguish between a normal field and an extension without them, otherwise there'd be ambiguity. For that reason they can not be dropped.

**Comment by zdicesare** [comment]
Thank you for the insight, @dsnet !
