### ISSUE TITLE
APIv2: feature request: a go version of the protoc cli (simple version, for plugins only)

### ISSUE THREAD

**Issue by mikeleonard** [golang/protobuf#841]
## Feature suggestion: 

For the future v2 release (https://github.com/golang/protobuf/issues/364) would you consider including a version of the protoc cli tool written in go?

## More info
There is a pre-existing go implementation of protoc here:
https://github.com/jhump/goprotoc/blob/master/cmd/goprotoc/goprotoc.go

@jhump I hope you don't mind me making this feature suggestion.

I've been following the APIv2 branch of golang/protobuf. Among other things in v2, I'm excited about the golang/protobuf/protogen package and the new reflection capabilities... specifically how easy they make writing custom code generation plugins for protoc (for anyone less familiar with all this: see the plugins in golang/protobuf/cmd directory in the APIv2 branch).

I'd love to see something like jhump's goprotoc included and officially supported.

For code generation of go code this would result in a go-only installation path! 

## PS
Note that the tool need not include any code generation capabilities. It could just shell out to the standard protoc for generation of other languages like github.com/jhump/goprotoc does.

That said... one day it'd be cool to see a go version of protoc replace the existing c++ one. But that's the gopher in me talking.

**Comment by jhump** [comment]
The `goprotoc` I started on was really a toy. I was doing it just for fun. Also, as you'll quickly learn from examining the source or trying to run it, it is unfinished.

That repo was really more intended as a library to make it super easy to write `protoc` plugins in Go (that part actually *is* complete and works quite well IMO).

I spun up the `goprotoc` "pet project" in there since all `protoc` does (unless you're using a language that it knows how to generate sans plugin) is to parse proto sources into descriptors, feed them to plugins, and then create files based on the plugin responses (which is kind of simple to do, if given a package that already does the parsing, such as `"github.com/jhump/protoreflect/desc/protoparse"`).

TBH: I would not expect the Google protobuf team to take this feature request that seriously. (Sorry.)

**Comment by neild** [comment]
As jhump@ says, protoc doesn't really do very much when using a plugin--it converts proto files into descriptors and writes files and that's about it. So it wouldn't be tremendously difficult to write a replacement. 

On the other hand, a replacement doesn't seem to offer much aside from a potentially better build experience for Go users.  Which isn't insignificant, to be sure, but isn't transformative either. Is this the best place for us to expend engineering effort? Is "written in Go" really that much of a selling point, and if so why? (It's certainly gratifying if it is, but I'm dubious.)

**Comment by puellanivis** [comment]
I don’t see investing time in a protoc that will only really be used by the Go language to be worth any effort. Since there are no plugins for Java, C++, or python, because they’re already bundled into the protoc compiler directly, the narrow use case for a go-only protoc compiler is… unappealing.

**Comment by mikeleonard** [comment]
Hi again thanks a lot for the comments.

I completely understand your need to carefully focus engineering effort. That said... let me try to sell you on the idea one more time now that I've heard your initial thoughts:

## Imagine...

Say this repository had a goprotoc cli. This would, as you've said, be fairly easy to write and maintain as it just converts proto files into descriptors, calls out to plugins (notably the go and grpc ones in this repo) and then writes out the files. 

The cli usage would simply match the protoc cli. Anything outside of calling plugins (eg passing in the usual flags to generate python for example) would print out a nice console message informing the user to install the proper protoc cli with a link to online instructions.

Additionally, goprotoc could shell out to protoc if it is installed, like @jhump 's version does. Or not. Just a thought.
Additionally, goprotoc could have the go and grpc plugins built into it so these don't need to be installed separately. Or not. Just a thought.

## Here's why I think a goprotoc cli would benefit the go community:

Simply put: Users could install it and be good to go, especially if the code imports the go and grpc plugins in the binary so they don't need to install them separately.

### For beginners:
- better onboarding experience for new users to protobuf and grpc in go (no steps to download protoc, chmod +x, make sure it's in the path, etc).
- no 'which version of protoc do I need?' if their intention is just to generate go code
- would work nicely with go generate ie something like... `go:generate go install github.com/golang/protobuf/cmd/goprotoc && goprotoc ...`

### And for more advanced users:
- easier in CI/CD build environments as the go tool chain is all that is needed if you're only generating go code and/or running your own or 3rd party plugins. No need to have protoc binary on the build server (up-to-date version, with the right file permissions and in the path).
- it's more than just a cli tool... as it would need libraries to find includes, write out files, etc. This functionality is in protoc but not in this repo... having it here would standardise these things and let advanced users use these libraries and skip the command line altogether.

### Summary
I appreciate that one of the key reasons for protobuf is inter-language interoperability and for that you likely need to install protoc to generate the other languages. But protoc is also useful if you're only writing go, so why not make this use case that bit easier for folks?:
- even if you're just using go, protobuf encoding is a good replacement for the likes of encoding/gob and json or your own custom encoding
- grpc is a great rpc system (similar to net/rpc, go micro etc) between go microservices
- code gen is very common in go but very fragmented in its approach - with the new v2api's codegen library perhaps we'll see more plugins written in go (generating go code or anything else).


That's my pitch. No hard feelings if it's not to be. Just thought I'd suggest it while you're working on the v2api (which I've just started using by the way and it's a great improvement thanks for your hard work!).

### PS: Why not have it as a 3rd party tool?
Harder for people to discover. One less install instruction. Atomic updates with the plugins. Better testing. Official support. Confidence for people that it'll stay updated. More eyes. (More likely to make it into the official golang/tools go toolchain one day - a guy can dream).

**Comment by mikeleonard** [comment]
This grpc blogpost is relevant to the discussion I think: https://grpc.io/blog/installation/

**Comment by puellanivis** [comment]
protoc is currently the protobuf compiler for all languages. Siloing go users into a narrow-purpose goprotoc would likely end up doing more harm to the go community in the long run by isolating us away from the rest of the protobuf community. 🤷‍♀ 

It is unlikely that it will be better tested, because protoc currently has _all the other languages_ also testing through it. Official support would be _lost_ because the official maintainers would be cut out. More eyes, is equally unlikely because again, the current protoc has support from all the languages, even if it is, itself, written in C++.

Yes, protobuf is an incredibly good fit with Go, which is more because Go was designed and built in an environment with pervasive preexisting knowledge of protobuf. But cutting off ties with the rest of the protobuf community, and going our own way seems like a bad idea.

**Comment by mikeleonard** [comment]
Fair enough! Thanks for taking the time to consider the suggest in any case. Will close the issue.

Please note that I wasn't at all suggesting anything along the lines of "cutting off ties with the rest of the protobuf community, and going our own way". I was just looking to improve the protobuf onboarding experience for beginners in the go community.

Looking forward to the APIv2 release down the road. I'll raise any issues/pull requests if I come across anything while testing it out.

All the best.
