### ISSUE TITLE
APIv2: reflect/protoregistry: inconsistent behavior in mismatching types

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#873]
There is a minor inconsistency between `protoregistry.Files` and `protoregistry.Types` when looking up a descriptor.

Compare the following:
https://github.com/golang/protobuf/blob/4a539f4e0996d1ee27a24c4c1ee528b760f96274/reflect/protoregistry/registry.go#L141-L149

https://github.com/golang/protobuf/blob/4a539f4e0996d1ee27a24c4c1ee528b760f96274/reflect/protoregistry/registry.go#L440-L452

Notice how `Types.FindEnumByName` returns an error if something is found, but of the wrong type, whole `Files.FindEnumByName` returns nil in that situation.

I don't have an opinion which is the right behavior, but they should be consistent.

\cc @neild

**Comment by dsnet** [comment]
I'm inclined to say an error is the right behavior. I'm looking at `reflect/protodesc` right now, and it seems to be more desirable that an error is reported indicating a conflict in the namespace, than to treat a resolution as being "not found".

**Comment by neild** [comment]
Both return an error, no? It's just a question of what the error is.

I agree that "wrong type" seems better than "not found".

**Comment by puellanivis** [comment]
Indeed, semantically, “unexpected type” is a different error domain than “not found”. But the `Files.FindEnumByName` has a double duty on that conditional. Either the value is not in the map, so it returns a zero value which fails to type assert, or the value is in the map, but the type assert fails due to wrong type.

The later design, which distinctly breaks up these two possible conditions is much better. (Perhaps even more so with a little more early return.)

**Comment by dsnet** [comment]
https://go-review.googlesource.com/c/protobuf/+/183697 adds a `Files.FindDescriptorByName` and https://go-review.googlesource.com/c/protobuf/+/183700 removes all the `Files.Find{Enum,Message,Extension,Service}ByName` methods. Since the individual descriptor lookup methods are being removed, this issue is moot.
