### ISSUE TITLE
APIv2: consider replacing Message.NewMessage with Message.NewField

### ISSUE THREAD

**Issue by neild** [golang/protobuf#879]
You can construct a `protoreflect.Value` assignable to a non-repeated, non-message field with `protoreflect.ValueOf`.

You can construct a `protoreflect.Value` assignable to a non-repeated message field with `protoreflect.Message.NewMessage`:

```go
// NewMessage returns a newly allocated empty message assignable to
// the field of the given descriptor.
// It panics if the field is not a singular message.
NewMessage(FieldDescriptor) Message
```

However, there isn't a simple way to construct a `protoreflect.Value` assignable to a repeated field. There *is* a non-simple way; for a message `m`: `m.New().Mutable(fd)`. That is, construct a new, empty message, get a mutable `List` or `Map` value from it, and then throw out the empty message. The new value may be assigned to the original `m`.

We could change `NewMessage` to construct new list and map values as well (and maybe everything else as well, because at that point why not):

```go
// NewField returns a newly allocated empty value assignable to the field of the given descriptor.
NewField(FieldDescriptor) Value
```

Alternatively, perhaps we should drop `NewMessage` as unnecessary now that we have `Mutable`.

**Comment by puellanivis** [comment]
Probably :+1: for a `NewField` that “does it all”. Offload complexity from the callers to the library.

As you describe, callers would need to account for the numerous cases of “is message/non-message field? Is repeating/non-repeating?” I would point to parallels of just a simple constructor in Go’s `reflect`  library, but now I realize that it’s full of `MakeChan()` `MakeFunc()` `MakeMap()` `MakeSlice()` and `New()`… so, maybe not an ideal model for my argument for simplicity.

**Comment by dsnet** [comment]
> `NewField(FieldDescriptor) Value`

I like it. Several thoughts:
* What does it return for proto2 scalars? The zero value or the default? Currently `protoreflect.ExtensionType.New` returns the zero value for proto2 scalars (where the "zero" value of a proto2 enum is the first enum value), not the default value, whatever it may declared as. Presumably this would do the same thing.
* I assume we do the moral equivalent for lists and maps? That is to add `protoreflect.List.NewElement` and `protoreflect.Map.NewValue` methods? Alternatively, we could name all three as the `NewValue` method (based on what it returns, rather than what it is assignable to).
* I like the flexibility this buys us. Suppose protobuf one day allows lists of lists or lists of maps of lists, etc. The method you're proposing nicely handles that hypothetical extension.

> `protoreflect.NewValue`

Did you mean `protoreflect.ValueOf`?

**Comment by dsnet** [comment]
Tangentially related. `protoreflect.Message.Mutable` exists. Should `protoreflect.List.MutableAppend` and `protoreflect.Map.Mutable` also be added?

**Comment by neild** [comment]
> What does it return for proto2 scalars?

Probably the zero value, since it's simple and there's a good way to get the default if you need it.

> I assume we do the moral equivalent for lists and maps?

I hadn't thought about it, but yes. If we want to be very consistent we could have a `protoreflect.Map.NewKey`, but it's probably not worth it since keys can never be composite types.

I have a slight preference for `NewField`/`NewElement`/`NewValue`; it seems a bit clearer.

> Did you mean protoreflect.ValueOf?

Yes.

**Comment by dsnet** [comment]
It seems we're all in support of the new API, are you going to add it or me?

**Comment by dsnet** [comment]
This is done.
