### ISSUE TITLE
internal/encoding/wire: externalize the package

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#882]
We have a nice package for interacting directly with the protobuf wire format located in [`internal/encoding/wire`](https://godoc.org/google.golang.org/protobuf/internal/encoding/wire).

As I continue to migrate a number of internal users to v2, there are number of times where they directly interact with the wire format and I really want to use the use the `wire` package. The v1 API has `wire`-specific operations through [`proto.Buffer`](https://godoc.org/github.com/golang/protobuf/proto#Buffer) type. However, the API for that is clunky is to use for a variety of reasons.

Should we externalize this as `encoding/protowire`?

**Comment by dsnet** [comment]
Two questions:

1) The package currently does error reporting by coalescing error conditions into the length as a negative value and relies on [`wire.ParseError`](https://godoc.org/google.golang.org/protobuf/internal/encoding/wire#ParseError) to convert a bad-length into a principled error.
    * There is a performance benefit for this since, it saves 16B that would be needed to represent an error interface, which can make a non-trivial impact when these functions are called in hot loops.
    * As existing precedence, functions like [`strings.Index`](https://godoc.org/strings#Index) also uses the returned length to also represent error situations with a negative index.

2) The `Append` functions take the destination as the first argument, should this be moved to the end?
    * The current signature matches the built-in `append` function.
    * However, placing it at the end allows chaining multiple `Append` functions in a more readable manner:
```go
b, _ := proto.Marshal(m)
b = wire.AppendTag(1234, wire.BytesType, wire.AppendBytes(nil, b))
```

**Comment by puellanivis** [comment]
We should really try to avoid exposing in-band errors, but like you said, some of this could be hot-loop, where this sort of thing is critical.

We could potentially provide two interfaces, one (which is unimportable? or otherwise marked to discourage common use) that does the hot-loop in-band errors, and a second that wraps the hot-loop version but has much more user-friendly not-for-hot-loops out-of-band error returns.

This could allow us to continue using some API signatures for speed-important code, and freer form API that allows for clearer code when it needs to interact with the wire format outside of performance concerns.

**Comment by dsnet** [comment]
Done.
