### ISSUE TITLE
jsonpb: unexpected output for small negative google.protobuf.Duration

### ISSUE THREAD

**Issue by AlekSi** [golang/protobuf#883]
**What version of protobuf and what language are you using?**
Version: v1.3.1

**What did you do?**
https://github.com/AlekSi/go-bug/tree/master/jsonpb

```go
func TestDuration(t *testing.T) {
	d := -time.Nanosecond
	dp := ptypes.DurationProto(d)
	m := &jsonpb.Marshaler{}
	s, err := m.MarshalToString(dp)
	if err != nil {
		t.Fatal(err)
	}
	if s != `"-0.00000001s"` {
		t.Errorf("Unexpected result: %s", s)
	}
}
```

**What did you expect to see?**
`"-0.00000001s"`

**What did you see instead?**
`Unexpected result: "0.-00000001s"`

**Comment by dsnet** [comment]
Thank you for the report.

@cybrcodr, can you confirm whether this was fixed in v2?

**Comment by dsnet** [comment]
Also, if the fix is simple, it may be doing in v1 as well.

**Comment by cybrcodr** [comment]
This is fixed in v2.

Minor, I think the posted sample code is comparing with slightly wrong value, a negative nanosecond is "-0.000000001s"  (8 zeroes).

The bug in V1 is that it puts the negative sign after the decimal.  Yeah, I can look into fixing this for v1.  Logic can be carried over from --

https://go.googlesource.com/protobuf/+/refs/heads/master/encoding/protojson/well_known_types.go#651

**Comment by AlekSi** [comment]
Thank you. Do you plan to release v1.3.2 any time soon?
