### ISSUE TITLE
internal/benchmarks: cleanup redundant bench tests

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#886]
[CL/183245](https://go-review.googlesource.com/c/protobuf/+/183245) added a general purpose benchmark framework for all the various serialization formats.

Do we still need the others?
* [encoding/bench_test.go](https://github.com/golang/protobuf/blob/api-v2/encoding/bench_test.go)
* [proto/bench_test.go](https://github.com/golang/protobuf/blob/api-v2/proto/bench_test.go)

\cc @neild @cybrcodr

**Comment by neild** [comment]
Probably not, although `proto/bench_test.go` has been interesting for comparing the performance of very specific things (maps, oneofs, etc.) on a very micro level. It might be interesting to add some focused benchmarks for those to the benchmarks directory.

**Comment by cybrcodr** [comment]
I just checked out benchmark/bench_test.go.  That's neat.  Yeah, that can replace encoding/bench_test.go.

Btw, just a note that passing in -v1 to benchmark text marshal/unmarshal may produce the same results depending on which v1 is being used.  With the go.mod file checked in, I believe it is using the latest v1 where text marshal/unmarshal are already wrappers to the v2 implementation.

In order to properly get v1 values, one will need to adjust go.mod to point to the real old v1 implementation.

**Comment by dsnet** [comment]
I don't think there's much value in keeping an issue just for this. There's always a number of things that can be cleaned up.
