### ISSUE TITLE
APIv2: reflect/protoreflect: add Message.{HasOneof, ClearOneof}

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#906]
The C++ message reflection API has [`HasOneof` and `ClearOneof`](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message#Reflection.HasOneof.details) methods. Should we add them to our API as well?

I should note that we already have a [`Message.WhichOneof`](https://github.com/golang/protobuf/blob/74615a3960987b289525a30e98dec5800c11db16/reflect/protoreflect/value.go#L124-L127) method which is sufficient to implement `HasOneof` and `ClearOneof`:

```go
func HasOneof(m protoreflect.Message, od protoreflect.OneofDescriptor) bool {
    m.WhichOneof(od) != nil
}
func ClearOneof(m protoreflect.Message, od protoreflect.OneofDescriptor) {
    if fd := m.WhichOneof(od); fd != nil {
        m.Clear(fd)
    }
}

**Comment by puellanivis** [comment]
Looks clean enough to add, and they’re relatively useful convenience functions, since the person would likely already have to have the package imported where these would be available? Or is the idea to make them receiver methods parallel to `WhichOneof`?

If they’re going to be package-level convenience functions, then they’re only convenient if you would already have the package imported, otherwise it’s Yet Another Package To Import.

If they’re going to be receiver methods, then :thinking: we end up with Yet Another Convenience Receiver Method On A Type. At which point, I would less prefer to see the `HasOneof`, as it’s so simple, but the `ClearOneof` might still have some remaining amount of utility.

**Comment by neild** [comment]
These are so simple to implement in terms of `WhichOneof` that I don't think they're worth it. The main argument I see in favor is that they can be a little bit more efficient, but these don't seem like common enough operations for that to be important.

I suppose the other argument in favor is that a number of oneof operations are semantically described in terms of "first clear the oneof, then do X", so not having a method that clears the oneof is a bit surprising.

**Comment by dsnet** [comment]
Inside Google, the frequency of usage for C++ equivalents are as follows:
* `WhichOneof`: 221
* `HasOneof`: 59
* `ClearOneof`: 9

> If they’re going to be package-level convenience functions

I don't they are common enough to warrant being a package-level convenience function.

> These are so simple to implement in terms of `WhichOneof` that I don't think they're worth it.

I think I agree.
