### ISSUE TITLE
APIv2: proto/protoreflect: API for accessing unknown fields

### ISSUE THREAD

**Issue by Novitoll** [golang/protobuf#927]
I have a byte stream like `08 05 18 03 65 66 67` which is a basically encoded proto message of 2 fields:

- varint: 5
- string: "ABC"

I dont have a descriptor object that might describe me the Message and its fields number, types etc. so I am working only with this byte stream. So basically, I want to create dynamic structs with some custom Descriptor structs that will have `WireType, Value, Size?` fields. 

There is the CPP implementation of UnknownFieldSet that seems can solve this issue.

https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.unknown_field_set#UnknownFieldSet

Could not find how to do it with GoLang API of protobuf. If there is no such, let me know I can contribute.

**Comment by dsnet** [comment]
There is no stable API in the current API for directly interacting with unknown fields.

The [v2 implementation provides API for accessing the unknown fields](https://github.com/golang/protobuf/blob/16163b4f675b9ced03abc9157069d5dc76762213/reflect/protoreflect/value.go#L136-L148) (albeit the raw data only). You can then decode data to accomplish whatever you want with the unknown field set.

However, the v2 implementation is not release yet.

Marking as `pending-v2` since this is fixed but not yet released.

**Comment by dsnet** [comment]
The new [`protoreflect`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect) package provides access to unknown fields and has been released as part of [`google.golang.org/protobuf@v1.20.0`](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0).
