### ISSUE TITLE
APIv2: encoding/protojson: use group message name

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#935]
In `prototext`, there's logic to use the [name of the group message instead of group field](https://github.com/golang/protobuf/blob/3cda377ed232b6d7c0d641b7f2d0b92c2b4823aa/encoding/prototext/encode.go#L102-L105). Should similar logic exist in `protojson`?

\cc @cybrcodr

**Comment by dsnet** [comment]
It seems that `protoc` sets the JSON name for group fields to be equal to the field name (which is the lowercase of the message name). I guess that's the name we're always supposed to use?

**Comment by cybrcodr** [comment]
Yes.  `protoc` should supply the JSON name for all field names including group type, and group field type are serialized the same way as message fields.  This is different from the text format.

**Comment by dsnet** [comment]
For the default case, I've come to agree that the JSON name provided by `protoc` is authoritative even if its weird for groups.

In order for the v1 `jsonpb.Marshaler` to wrap v2, we'll need to provide [`OrigName`](https://godoc.org/github.com/golang/protobuf/jsonpb#Marshaler.OrigName) option in v2. Suppose we add that option, what is the behavior then for groups? It seems that it should follow similar rules as the text format.

**Comment by cybrcodr** [comment]
Note that the current C++ lib does not have the equivalent feature of using the proto field name in JSON.  It also does not support group fields.

But yes, if we really need to support that in v2, the [developer guide](https://developers.google.com/protocol-buffers/docs/proto3#json_options) has the following statement ...

> Use proto field name instead of lowerCamelCase name: By default proto3 JSON printer should convert the field name to lowerCamelCase and use that as the JSON name. An implementation may provide an option to use proto field name as the JSON name instead. Proto3 JSON parsers are required to accept both the converted lowerCamelCase name and the proto field name.

Even though the developer guide only describes proto3 fields, it can probably apply to proto2 as well as what we've followed and done in v1.

How much of these options are we willing to implement in v2?  Are these primarily for v1 compatibility only or are we willing to accept potentially other options that users may ask for?

Given that it is not difficult to write a JSON encoder/decoder now using protoreflect, I'd like to think that others who desire to have their own customizations can do so by implementing their own encoder/decoder rather than extending the default one.  Just a thought.

**Comment by dsnet** [comment]
Done in https://go-review.googlesource.com/c/protobuf/+/193998
