### ISSUE TITLE
APIv2: add protoreflect.Message.ExtensionFields

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#948]
Currently, there is no efficient way to lookup whether an extension field is populated in a message given only the name or the field number. The best you can do is to loop through all populated fields and look for that field.

Perhaps we should add the following method:
```go
type Message interface {
    ...

    // ExtensionFields returns a list of field descriptors for all extensions fields
    // that are populated in the message.
    ExtensionFields() ExtensionTypeDescriptors
}

type ExtensionTypeDescriptors interface {
	// Len reports the number of fields.
	Len() int
	// ByName returns the extension descriptor for a field named s.
	// It returns nil if not found.
	ByName(s FullName) ExtensionTypeDescriptor
	// ByNumber returns the extension descriptor for a field numbered n.
	// It returns nil if not found.
	ByNumber(n FieldNumber) ExtensionTypeDescriptor
	// Range iterates over all extension descriptors.
	Range(func(ExtensionTypeDescriptor) bool)
}
```

That allows you to:
* Quickly check whether any extension fields are populated in a message: `m.ExtensionFields().Len() > 0`
* Lookup a extension field by name or field number.
* Quickly range over only the extension fields without ranging over all the other populated fields.

EDIT: Added a `Range` method.

**Comment by neild** [comment]
That interface as written doesn't let you range over the extension fields; you'd also need a method to get the n'th ExtensionTypeDescriptor or one to range over all of them.

This API seems useful only when you're working with extensions and you know enough about the extensions that looking one up by name is meaningful, but you don't have the `ExtensionType` available. I wonder how often that comes up.

**Comment by dsnet** [comment]
> That interface as written doesn't let you range over the extension fields; you'd also need a method to get the n'th ExtensionTypeDescriptor or one to range over all of them.

I added a `Range` method.

> This API seems useful only when you're working with extensions and you know enough about the extensions that looking one up by name is meaningful, but you don't have the ExtensionType available. I wonder how often that comes up.

When I was porting legacy code to protobuf reflection, there were a number of cases where I only had field number of the extension on hand. Currently, all of those cases are implemented by for-looping through all the fields. To be fair though, had this code been completely re-written, I think the problem could have been entirely avoided.

**Comment by puellanivis** [comment]
As a bikeshed color comment: the `flag` package suggests `Visit` and/or `VisitAll` for a function that ranges over an opaque set, and calls a given function on each one.

But now that I think about it, perhaps `flag.Visit` should have been `Range` as well… it does match up reasonably well with the common syntax:
```
things.Range(func(v Value) {
})
// compared to
for v := range things {
}
```

Hm, not sure. It would be nice to have a common/agreed name for this pattern, but I’m not sure the `flag.Visit` choice is The Right Choice, and I do not want to pronounce it the Chosen Way just because it is already there. (Plenty of go libraries would be revisited if it were not for go1 compat guarantee.)

**Comment by neild** [comment]
Thinking about this, I don't like adding an `ExtensionTypeDescriptors` interface. Implementing `protoreflect.Message` previously required implementing several subtypes such as `KnownFields`. We've now moved to something which can be implemented by a single type, which I think is much nicer for a type which we expect to be implementable by users.

I'm also wary of complicating `protoreflect.Message` for efficiency purposes alone. This isn't providing any information that isn't already accessible.

Looking at the specific features being added here:

- Quickly check whether any extension fields are populated in a message. We could add a `Message.HasExtensions` method. I think that's clearly overspecialized, however.
- Efficiently look up an extension field by number. I'm curious about the case where someone would want to do this, but not want to look up the field in the registry. If we do want to support this, perhaps a new method on `Message`:
  GetByNumber(num protoreflect.FieldNumber) (protoreflect.FieldDescriptor, protoreflect.Value)
- Efficiently look up an extension field by name. I'm even more curious about this case. It does occur to me that it would be nice to be able to write `v := m.GetByName("some_field")` rather than looking up the `FieldDescriptor` first, but there are problems with that. (We'd need set, clear, and mutable by name as well, for one.)
- Range over the extensions alone. Ranging over all set fields and selecting the extensions is already simple, so this is purely for efficiency.

**Comment by dsnet** [comment]
We decided against this. It's already a wart that the Go implementation of extensions makes extension type information at the granularity of each concrete message value. This is different from how extensions work in the other major language implementations. This API would accentuate this inconsistency with respect to other languages.

The use-cases that wanted this behavior were actually better off looking at the global registry.
