### ISSUE TITLE
APIv2: internal/impl: fast path should optimize for large oneofs

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#950]
I'm in the process of migrating a number of targets that formerly used Go reflection to protobuf reflection, and I'm finding that a common source of slow down (after porting) is on messages with a oneof that has many many fields.

In several places, our naive implementation simply iterates through all the known fields checking for presence. This is functionally correct, but is O(n) where n is the number of fields in a oneof, when it could be O(1). In one target, the performance gains was as high as 12x with this change.

I already did some similar optimizations:
* https://golang.org/cl/196358
* https://golang.org/cl/196121

We should do something similar for the fast path implementations.

**Comment by dsnet** [comment]
Tentatively marking as `blocks-v2` since we're aiming for performance parity relative to the v1 implementation, and the table-driven implementation of v1 has this optimization.

**Comment by puellanivis** [comment]
:cough: `oneof`s considered harmful :cough:

However, being that one cannot just flip the whole table and remove them, we really should try to handle them as efficiently as possible. Avoiding O(n) implementations is equally important, not just because it’s more inefficient than things should need to be, but also because it makes accidental O(n²) that much more likely.

**Comment by dsnet** [comment]
> :cough: `oneof`s considered harmful :cough:

I've heard of `required` considered harmful, but this is my first time hearing about `oneof` being harmful. Personally, I find it odd that they implemented them not as a first-class type, but as a property of a message. Is a there discussion about them you had in mind?

**Comment by puellanivis** [comment]
I’ve not really widely promulgated the idea, and it’s really more of an esoteric opinion than anything I would like to put down firmly. But it’s mostly centered around how unwieldy the semantics are, especially for Go.

You know how one can potentially raise efficiency massively by cutting out 20% of a standard, because the compromises necessary to meet those parts of the standard cover 80% of the expense? I see `oneof` as in that category.
