### ISSUE TITLE
Unmarshal *ptypes/struct.Struct to Go struct

### ISSUE THREAD

**Issue by bontibon** [golang/protobuf#957]
I have a `*ptypes/struct.Struct` field in one of my incoming messages. I would like to decode that value into a Go struct that I have defined. I am able to accomplish this by marshalling the Struct to JSON then unmarshalling it to my Go value:

```go
var b bytes.Buffer
if err := (&jsonpb.Marshaler{}).Marshal(&b, req.GetQueryResult().GetParameters()); err != nil {
	panic(err)
}
var params Parameters
if err := json.Unmarshal(b.Bytes(), &params); err != nil {
	panic(err)
}
```

However, this seems like a roundabout way of doing it. Is there a recommended way to do these types of conversions?

**Comment by dsnet** [comment]
That is the only way to do it. The way the `encoding/json` package unmarshals into an arbitrary Go type is surprisingly complicated. We won't be implementing a function to do it directly since it requires us to replicate the exact same complexity as the standard library package, and almost certainly in just as buggy a way.

**Comment by PxyUp** [comment]
May be help for some one :
https://gist.github.com/PxyUp/373565bc466193a98bed809c9cd50431
