### ISSUE TITLE
APIv2: consider Message.IsValidValue

### ISSUE THREAD

**Issue by neild** [golang/protobuf#958]
Should we have a way to test a Value for compatibility with a message field, along the lines of ExtensionType.IsValidValue?

This could either be a method on MessageType or Message.

**Comment by dsnet** [comment]
Marking as `blocks-v2` since this can't be changed after release.

Is this hypothetical, or did you have a real need for this?

I've seen the use for a semi-related validation function. Something like `Message.IsValidFieldDescriptor`, which takes in a `FieldDescriptor` and reports whether it is valid for that message or not.

**Comment by neild** [comment]
I was updating a bit of code (previously Go reflection, now protoreflect) that copies a list of named fields from one message to another message of a different type. There's no simple way to catch a field type mismatch; you can compare the descriptors, but that won't catch the (admittedly unusual) case where the descriptors are the same but the Go types aren't.

It's nothing you can't work around, but got me wondering whether there should be an easy way to do this for non-extension fields.

**Comment by dsnet** [comment]
Nice to have, but we both agreed that the use cases didn't seem all that compelling.
