### ISSUE TITLE
Converting Protobuf map<string, string> to json with array of key value pairs

### ISSUE THREAD

**Issue by thestephenstanton** [golang/protobuf#959]
So I have a proto message:

```
message User {
    int64 id = 1;
    string name = 2;
    map<string, string> details = 3;
};
```

So now I have this `User` struct and then I marshal that struct into bytes. Then I take those bytes and use the `jsonpb.Marshaler` to convert the bytes into JSON. Here is the code:

```
user := User{
	Id:   42,
	Name: "Stephen",
	Details: map[string]string{
		"Home":          "Charlotte",
		"FavoriteColor": "Black",
	},
}

buf := &bytes.Buffer{}
jsonMarshaller := jsonpb.Marshaler{}
jsonMarshaller.Marshal(buf, &user)

fmt.Println(string(buf.Bytes()))
```

With this I get this output:
```
{
    "id": "42",
    "name": "Stephen",
    "details": {
        "FavoriteColor": "Black",
        "Home": "Charlotte"
    }
}
```

So obviously this is a very contrived example because there are other factors at play. For context, I one application I just receive the proto bytes, then have to to that into JSON. Problem is that JSON is not to (json-schema)[https://json-schema.org] standards. What I would like is:

```
{
    "id": "42",
    "name": "Stephen",
    "details": [
        {
            "key": "FavoriteColor",
            "value": "Black"
        },
        {
            "key": "Home",
            "value": "Charlotte"
        }
    ]
}
```

Is there any settings for that in `jsonpb.Marshaler`? 

**BONUS QUESTION**: Why is the `id` in the JSON a string when the struct property is an int?

**Comment by dsnet** [comment]
The behavior of `jsonpb` is intended to be in strict compliance to the JSON to protobuf specification here: https://developers.google.com/protocol-buffers/docs/proto3#json

We (the Go implementation of this specification) are not at liberty to diverge from it.

> Why is the id in the JSON a string when the struct property is an int?

This is also dictated by the specification. The technical reason for this is because the JSON format cannot accurately represent integers larger than 2^53 because [numbers in JSON](https://tools.ietf.org/html/rfc7159) are defined to be a [IEEE 754 double-precision float](https://en.wikipedia.org/wiki/Double-precision_floating-point_format).
