### ISSUE TITLE
APIv2: drop dependency on github.com/golang/protobuf

### ISSUE THREAD

**Issue by neild** [golang/protobuf#962]
The `google.golang.org/protobuf` module currently depends on the `github.com/golang/protobuf` module for:

* Benchmarks.
* One test in internal/impl/extension_test.go still using the old `proto.Equal`.
* Generated messages in `internal/testprotos/legacy`.

We should clean these up and drop the circular dependency between these modules.

**Comment by dsnet** [comment]
Do you have proposed action items for these? My thoughts:
* We can isolate the the legacy tests via a sub-module OR move them to the v1 repo and modify our integration tests to run them.
* We can drop the v1 part of the benchmarks prior to release when we are confident that v2 is at performance parity or better than v1.

**Comment by dsnet** [comment]
Also, `proto.Equal` today [should be sufficient for this use case now](https://github.com/golang/protobuf/blob/6e40b32926f6edc22e192d963796aded92caf84b/internal/impl/extension_test.go#L20), right?

**Comment by neild** [comment]
Can we edit the legacy `.pb.go` files to depend on a stripped down local version of the old `proto` package with just the minimal required type definitions? A legacy version of `runtime/protoimpl`, essentially.

**Comment by dsnet** [comment]
That's a possibility. I think it comes down a question of test fidelity. How representative do we want our tests to be of ensuring that legacy code continues to work?

For example, the old generated code [has a dependency on the `proto.Buffer` type](https://github.com/golang/protobuf/blob/95d75b7143da12c51ade631e44b1d013e207d6e0/internal/testprotos/legacy/proto2.v0.0.0-20160225-2fc053c5/test.pb.go#L1760). We could drop in a stub type there since I'm certain we don't use it in v2. However, me saying that I'm certain isn't exactly a valid test.
