### ISSUE TITLE
Panic When Use Marshal to encode, out of index

### ISSUE THREAD

**Issue by phyhwj** [golang/protobuf#967]
I don't know which version is my protobuf. I Just use the proto.Marshal like Picture 2, It throw a panic like picture 1.In function enc_struct, the index in prop.order is out of range of the prop.Prop. But it is not always throw the panic, but appears after run my program half minute.Thank you for reading my question.
![1](https://user-images.githubusercontent.com/20330637/66562187-b28cd180-eb8d-11e9-88db-380b300679cf.png)
![2](https://user-images.githubusercontent.com/20330637/66562351-10b9b480-eb8e-11e9-8348-43954e519362.png)

**Comment by neild** [comment]
Hard to say without more information, but I note that the code in your second screenshot makes use of `unsafe.Pointer`. If you have a bug in your code related to unsafe pointers it could easily manifest as a panic in an entirely different location.

I'd be quite surprised if the root cause of the panic here is a protobuf bug, but it's always possible. The next step, whatever the root cause, should be to reduce the panic to the smallest possible reproduction case.

**Comment by phyhwj** [comment]
Thank you. It's realy because of wrong using of unsafe.Pointer. I forgot to delete line 282 in pic.2. After I delete it, it runs okay.
