### ISSUE TITLE
APIv2: fix size caching when size >2GB

### ISSUE THREAD

**Issue by agsci2017** [golang/protobuf#970]
I know that some protobuf-based solutions are suffering from 2GB limit.

Is there 2GB limit in v2 (as in protobuf v1)?
https://stackoverflow.com/questions/34128872/google-protobuf-maximum-size

**Comment by dsnet** [comment]
It is not a deliberate goal of v2 to support >2GB messages, but it is setting the groundwork for being able to support them.

Today, the problem is that the [`XXX_sizecache` field is generated as the `int32` type](https://github.com/golang/protobuf/blob/1680a479a2cfb3fa22b972af7e36d0a0fde47bf8/proto/proto3_proto/proto3.pb.go#L244), which fundamentally limits the maximum message size. The v2 generator generates this field [using an opaque `protoimpl.SizeCache` type](https://github.com/golang/protobuf/blob/3770776dcda07973020bb685737c77eb1ff16d2d/types/descriptorpb/descriptor.pb.go#L476). Since the `SizeCache` type is under the runtime library's control, it has the ability to specify whether it is a 32-bit or 64-bit integer under the hood.

**Comment by neild** [comment]
A simpler fix than changing the size of the sizecache might be to just not cache sizes >2GB.

**Comment by dsnet** [comment]
The purpose of the size cache is to avoid quadratic behavior in the runtime. Not using it for messages >2GB may be catastrophic if the message is deeply nested (likely to be true for messages that are >2GB). However, if the reason the message is >2GB is because it has a gigantic bytes field somewhere near the root, then it wouldn't be that bad.
