### ISSUE TITLE
Registration for protobuf entities is overly limiting, any plan to improve this?

### ISSUE THREAD

**Issue by sirkon** [golang/protobuf#982]
Let we have two *.proto files in two different catalogs

`a/pkg.proto`

```proto
syntax = "proto3";

package pkg;

message Message {};
```

and `b/pkg.proto`

```proto
syntax = "proto3";

package pkg;

message Message {};
```

Unfortunately, we cannot import both in the one program as this will cause registration panic, where we would have two `pkg.Message` registration attempts.

The problem is we can't just compile 

```
schema/service → example.com/schema/service
schema/service@v2 → example.com/schema/service/v2
```
and import them. We need to change package names which is against proposed go modules workflow.

As soon as I understand, a code generated for C++ does not have such a problem. 

Is there any way to avoid this collision? Plans may be?

**Comment by neild** [comment]
C++ will encounter a link error due to duplicate symbols in this case.

You can't have conflicting versions of a given protocol buffer type in either a C++ or Go program. If you want to include two versions of some protocol buffer package, those packages will have to have different names. For example, `pkg.v1` and `pkg.v2`.
