### ISSUE TITLE
About protobuf reflect new garbage collect slowly

### ISSUE THREAD

**Issue by phyhwj** [golang/protobuf#989]
![memory record](https://user-images.githubusercontent.com/20330637/69117629-43c76000-0acb-11ea-9fa6-bc83d9bb88d2.png)
![battle heap(1)](https://user-images.githubusercontent.com/20330637/69117904-44142b00-0acc-11ea-8c0c-62f3e86ea4f6.jpg)
Hello. I use pprof heap to debug my server program and found that memory cost large when I use protobuf unmarshal, it looks like the reflect new allocs large of memory(pic2).  Because the GC is very slowly to deal it, so the memory will be used up finally. Even I stop the client , the memory needs 1 hour to return to normal level(pic 1). I can't understand how it works, please help me, thank you!

**Comment by dsnet** [comment]
Are you using proto2 or proto3?

**Comment by phyhwj** [comment]
> Are you using proto2 or proto3?

proto2

**Comment by dsnet** [comment]
This is a known issue and unfortunately there's not much we can do in the protobuf runtime. There needs to be drastic change to the generated API.

Essentially, the generated API represents scalars as a pointer to a primitive (e.g., `*int` or `*string`) so that it can represent presence based on whether the pointer is nil or not. This puts significant pressure on the GC both allocating those values on the heap (as your profile suggests), and also scanning all of the pointers later on.

At Google, this is a fairly significant performance problem and we're considering whether to add a different generated API that unexports all fields in a struct and only exposes accessor methods (e.g., `HasFoo`, `GetFoo`, `SetFoo`, and `ClearFoo`). This allows us to use a bitmask to represent field presence in proto2 and also brings the generated API to be closer to that of C++ and Java.

**Comment by phyhwj** [comment]
> This is a known issue and unfortunately there's not much we can do in the protobuf runtime. There needs to be drastic change to the generated API.
> 
> Essentially, the generated API represents scalars as a pointer to a primitive (e.g., `*int` or `*string`) so that it can represent presence based on whether the pointer is nil or not. This puts significant pressure on the GC both allocating those values on the heap (as your profile suggests), and also scanning all of the pointers later on.
> 
> At Google, this is a fairly significant performance problem and we're considering whether to add a different generated API that unexports all fields in a struct and only exposes accessor methods (e.g., `HasFoo`, `GetFoo`, `SetFoo`, and `ClearFoo`). This allows us to use a bitmask to represent field presence in proto2 and also brings the generated API to be closer to that of C++ and Java.

Thank you for answering
